### ISSUE TITLE
Add Java linter for code formatting

### ISSUE THREAD

**Issue by edwinzhng** [castorini/anserini#1004]
As mentioned in #1003, might be worth it to add a pre-commit hook for automatically formatting any modified files using https://github.com/Cosium/maven-git-code-format.

Code consistency would be nice to have without really sacrificing development speed :)

**Comment by nikhilro** [comment]
I find pre commit hooks to be annoying. I much prefer to code, commit, pull PR, see it fail a linter test, send a lint commit at the end lol. This is in combination with setting lint on save in code editor. So, if we just have a lint test and no pre commit hooks, that should help with not comprising development speed when you are actually developing; but also provide nice consistency before pushing stuff to master.

**Comment by edwinzhng** [comment]
Yeah good point, I used https://github.com/checkstyle/checkstyle so we can just add it to the project
