### ISSUE TITLE
Refactor Solr schema scripts for ACL and CORE collections

### ISSUE THREAD

**Issue by edwinzhng** [castorini/anserini#1009]
Currently, JSON data for our Solr schemas are put directly into the setup scripts. There are two ways we can refactor this:

1. Put JSON data in a separate file and have different schema files for adding or replacing fields, and allow our bash setup script to take the JSON data as a command line argument. In other words, we have a single setup script but multiple schema data files

2. Keep JSON data in the bash setup scripts as-is, but support different flags such as "--replace" to replace existing fields or "--add" to add new fields. Here, we have multiple setup scripts for each specific collection (ACL, CORE).

We will also need to update documentation after this is done.

Option 1 seems cleaner to me but would like to hear other opinions @nikhilro @lintool

**Comment by nikhilro** [comment]
1. sounds good

**Comment by lintool** [comment]
Issue resolved in #1069 and and #1068.
