### ISSUE TITLE
Index and search fields other than fields present in TREC dataset OR Multi_match query(Elasticsearch)perform in Elasterini 

### ISSUE THREAD

**Issue by Aayushpatel007** [castorini/anserini#1011]
How can I perform a multi-match query and index documents with multiple fields from elasterini?
Or how can i change the default search query when using elasterini?
In other words index and search fields other than fields present in TREC dataset. Is this possible right now?

**Comment by lintool** [comment]
Hi @Aayushpatel007 - not exactly sure what you mean, can you give a concrete example wrt to a TREC dataset?

**Comment by Aayushpatel007** [comment]
Hii @lintool  Sure. 
In addition to fields like "content", "title" from TREC documents, I am also extracting some Named Entities and keyphrases from TREC documents. Currently, I am using elasticsearch to index documents with additional fields(Named Entities/Keyphrases and metadata) and performing search operations on top of that using Elasticsearch "multi-match" query. 
Now, my question is:
1. How can I use Anserini to index additional fields other than the fields present in TREC datasets? 
2. Is it possible to search on multiple fields (2 or more fields) and adjusting the weight for each field?

As my final aim is to evaluate search results performance on the TREC dataset, Can you please let me know if I can perform the above-mentioned operations using Ansireni?

If using, Elasterini I guess I would need to change the config file (https://github.com/castorini/anserini/blob/master/src/main/resources/elasticsearch/index-config.robust04.json) and also the default search query. 

Thank You.

**Comment by lintool** [comment]
Yup, you'll have to tweak this: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexCollection.java#L409

and also the config file, as you've indicated above.

**Comment by Aayushpatel007** [comment]
Thanks @lintool I will try it out.

**Comment by lintool** [comment]
Having heard no follow up, I'm closing. Reopen if necessary.
