### ISSUE TITLE
Add option to change Analyzers in SimpleSearcher

### ISSUE THREAD

**Issue by Chriskamphuis** [castorini/anserini#1013]
This can be implemented similarly as setting and unsetting RM3.
This will allow for different analyzers to be used when using the SimpleSearcher through Pyserini, for example when no tokenization is desired.

**Comment by lintool** [comment]
There are two approaches to doing this that I can see:

1. pass in the analyzer in the `SimpleSearcher` constructor. Currently, the constructor hard codes the analyzer: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SimpleSearcher.java#L110


2. Extend `search` related methods to be able to pass in an analyzer.

BTW, there's already `setLanguage` in `SimpleSearcher` we should figure out how this integrates.

Approach 1 is easier to code up but less flexible... for example, you couldn't search with two different analyzers... although I'm not sure there's a use case for this? And I suppose if you really wanted to do this, you could do the analysis externally and then pass in the analyzed tokens?

Approach 2 is more flexible.

I'm leaning towards Approach 1, and `setLanguage` can just be folded in.
