### ISSUE TITLE
Grab Semantic Scholar data for ACL papers

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1014]
Seems like Semantic Scholar provides API access, direct to ACL papers! https://api.semanticscholar.org/

Can we see what goodies we can get? Would be awesome to get citation stats - how many times the paper has been cited.

**Comment by lintool** [comment]
Oh nice!

For example:
https://api.semanticscholar.org/v1/paper/ACL:J07-1005
for https://www.aclweb.org/anthology/J07-1005/

**Comment by lintool** [comment]
Even better, there's a dump: https://api.semanticscholar.org/corpus/download/

**Comment by edwinzhng** [comment]
Should I be doing this in a separate repository? Or just write a script and put this in here

**Comment by lintool** [comment]
Closing this issue - moving discussion to https://github.com/castorini/ura-projects/issues/1
