### ISSUE TITLE
compile error: dependency not found

### ISSUE THREAD

**Issue by jianzhu** [castorini/anserini#1025]
After I clone this project and compile it, I came across the following error:

[ERROR] Failed to execute goal on project anserini: Could not resolve dependencies for project io.anserini:anserini:jar:0.7.3-SNAPSHOT: The following artifacts could not be resolved: io.anserini:anserini-fastutil:jar:6.5.6, com.github.TREMA-UNH:trec-car-tools-java:jar:13: Could not find artifact io.anserini:anserini-fastutil:jar:6.5.6 in aliyunmaven (https://maven.aliyun.com/repository/public)

Does anyone know how to fix the above error?

**Comment by jianzhu** [comment]
I have fixed the above problem with the right maven settings.xml configuration

**Comment by Hugapud** [comment]
@jianzhu  I met the same problem .Could you please tell more detail about the solution ?Gratefully !

**Comment by cslzhl** [comment]
@jianzhu  @Hugapud I met the same problem.  Could someone of you please tell more detail about the solution ? Gratefully !

**Comment by lintool** [comment]
Sorry, I've never encountered this problem before, so you'll have to ask @jianzhu

**Comment by mam10eks** [comment]
Just in case someone else ends up here: Adding the following repositories (probably the configuration mentioned by @jianzhu) solved the issue for me:

```
    <repository>
      <id>AnseriniMaven</id>
      <url>https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/</url>
    </repository>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
```
