### ISSUE TITLE
Add Resources + Regressions for TREC Million Query Track (2007 - 2009)

### ISSUE THREAD

**Issue by mam10eks** [castorini/anserini#1034]
Is there a reason why `src/main/resources/topics-and-qrels` does not contain qrels/prels + topics for the Million Query Tracks?

I can include the million query resources together with regressions (because I would need them).

**Comment by lintool** [comment]
Yup, contributions would be welcome! Let me know if you need any help hooking into our setup.

**Comment by mam10eks** [comment]
The pull request #1036 would add all the required resources. (Although we may discuss whether it is ok to add the "inofficial" qrels.)

**Comment by mam10eks** [comment]
Done with #1036
