### ISSUE TITLE
java.lang.ClassNotFoundException: io.anserini.index.IndexCollection

### ISSUE THREAD

**Issue by wuyaoxuehun** [castorini/anserini#1039]
When I try to do "nohup sh target/appassembler/bin/IndexCollection ..." after I have done "mvn clean appassembler:assemble", I just get the ClassNotFound Exception. I have tried on WIndows and ubuntu, but the same problem remains.  I am using maven 3.6.3 and java 11.
This is my project hierarchy.
![4PP3A268B}PJANZ3 8SGH$F](https://user-images.githubusercontent.com/26178145/77110334-64df9380-6a60-11ea-9eca-562cad9acc93.png)
Thanks!

**Comment by lintool** [comment]
Does Maven build give any errors? It appears that you have files left over from the test cases, which should have been cleaned up automatically... this suggests that the build might not have completed successfully?

**Comment by wuyaoxuehun** [comment]
I used "mvn clean appassembler:assemble" without parameter "package", Many Thanks!@lintool

**Comment by rossbrown9879** [comment]
I tried running this without param package, but I'm also getting the same error @lintool

**Comment by wuyaoxuehun** [comment]
You should run with that package.

**Comment by Arlo10veSu** [comment]
i meet the same problem. But how to run it with param package?

**Comment by lintool** [comment]
If you post your command and errors here, we can try to help you debug.
