### ISSUE TITLE
Do you have indexer for CLEF-IP Collection

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#1041]
Dear Sir 
I have a collection called CLEF-IP - Patents Documents Collection

this is a paper that clarifies this collection 
[http://ceur-ws.org/Vol-1176/CLEF2010wn-CLEF-IP-PiroiEt2010.pdf](http://ceur-ws.org/Vol-1176/CLEF2010wn-CLEF-IP-PiroiEt2010.pdf)

these are some sample XML Files
[trymini_xml.zip](https://github.com/castorini/anserini/files/4358310/trymini_xml.zip)

The question is Can Anserini index these files ?

**Comment by lintool** [comment]
Looks like you have need to write a custom `Collection` class to process it directly; see examples here: https://github.com/castorini/anserini/tree/master/src/main/java/io/anserini/collection

You're other option is to write a Python script to convert the files into JSON, and then you can use the same instructions for MS MARCO: https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md

**Comment by ABDULAZIZALQATAN** [comment]
Thanks sir 
Supportive as usual 👍
