### ISSUE TITLE
COVID-19 collection: Implement passage indexing

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1044]
As discussed: an article = ID, TITLE + ABSTRACT (+ P1 + P2 + P3)?...

Decompose into:

+ ID, TITLE + ABSTRACT
+ ID.0001, TITLE + ABSTRACT + P1
+ ID.0002, TITLE + ABSTRACT + P2

**Comment by lintool** [comment]
Additional thought: we probably only want to store the raw docs in `ID`? Otherwise, we'd blow up the index size by a lot...

For, for example, if we retrieve `ID.0001`, we'd look up the raw doc in `ID`?

**Comment by nikhilro** [comment]
Makes sense
