### ISSUE TITLE
ValueError: chr() arg not in range(0x110000)

### ISSUE THREAD

**Issue by Erdene-Ochir0417** [castorini/anserini#1057]
Is there any example on japanese dataset?

I tried msmarco code on japanese dataset but there is encode error. Python reads correctly and java couldn't read correctly.
```
File "jnius/jnius_conversion.pxi", line 24, in jnius.release_args
  File "jnius/jnius_conversion.pxi", line 288, in jnius.convert_jarray_to_python
ValueError: chr() arg not in range(0x110000)
```

**Comment by lintool** [comment]
See this issue: https://github.com/castorini/pyserini/pull/50
