### ISSUE TITLE
queries for DOIs on Covid experiments shouldn't include partial matches

### ISSUE THREAD

**Issue by tteofili** [castorini/anserini#1076]
this is probably due to DOIs in CovidCollection to be tokenized.

**Comment by lintool** [comment]
@tteofili this appears to be indexed correct: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/generator/CovidGenerator.java#L121

I think the issue is that searching over fields isn't being properly exposed on the Python side?

**Comment by tteofili** [comment]
agreed.

**Comment by lintool** [comment]
This issue has been addressed.
