### ISSUE TITLE
TF_IDF for dumped document vector(s), NONE or TF_IDF difference? 

### ISSUE THREAD

**Issue by Narabzad** [castorini/anserini#1085]
I am trying to get the TF_IDF vector of dumped documents but I get tf of terms instead of tf-idf of terms using following command:

target/appassembler/bin/IndexUtils -index /data/anserini/lucene-index.robust04.pos+docvectors+rawdocs/ -dumpDocVector FBIS4-40260 -docVectorWeight TF_IDF  

How can I get the tf-idf vector of documents?

**Comment by lintool** [comment]
Hi @Narabzad - it appears that dumping individual doc vectors is only TF, based on code here: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java#L194

this: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java#L208 however, does appear to compute TD-IDF.

Alternative, if it's more convenient for you, use Python:
https://github.com/castorini/pyserini/#usage-of-the-index-reader-api : get tf from doc vector, compute idf separately:

> df, cf = index_utils.get_term_counts(term)

**Comment by lintool** [comment]
Having heard no follow up, closing. Reopen if necessary.
