### ISSUE TITLE
Elasticsearch regressions for MS MARCO documents

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1087]
We have MS MARCO documents regressions working for Solr, we should get it working on ES also.

**Comment by HangCui0510** [comment]
I will work on this one

**Comment by lintool** [comment]
Code merged with #1151 

@HangCui0510 can you update the documentation? https://github.com/castorini/anserini/blob/master/docs/elastirini.md

**Comment by HangCui0510** [comment]
Yes, I will update it.
