### ISSUE TITLE
add commit hash in release history

### ISSUE THREAD

**Issue by hscells** [castorini/anserini#1095]
Thank you for all the amazing work with this search tool, I am very keen to get started using it. One problem that has just caused me some frustration is installing anserini and pyserini at the same time. It seems there was a class called `JsoupGenerator` in anserini which was removed some time ago, but pyserini still looks for it. This caused pyserini to give an class not found exception. I managed to resolve this issue by building anserini from an older commit, instead of the master branch. I think maybe one thing that could reduce friction for others starting to use anserini and pyserini is to make it clear exactly which commit to clone from to keep both libraries in sync in the release history.

**Comment by lintool** [comment]
hey @hscells thanks for the feedback.

As we write in the Pyserini README:

> Pyserini versions adopt the convention of X.Y.Z.W, where X.Y.Z tracks the version of Anserini, and W is used to distinguish different releases on the Python end. 

We are careful to make sure the PyPI modules and Maven artifacts work seamlessly in the official releases, and, in general, we try to make sure HEAD of anserini works with HEAD of pyserini. You stumbled on a case where changes in anserini HEAD broken pyserini.

Sorry about that! I'm working on fixing right now...
