### ISSUE TITLE
Store CSV record in JSON in raw()

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1105]
Hi @edwinzhng - as I understand, in the current design of the Covid collections, if a document does not have full text, the CSV record is converted into a JSON and stored as the `raw()`. If there's full text, the full text itself is stored in the `raw()`. Right?

However, in the case of full text, there seems to be information in the CSV record (e.g., `cord_uid`, `pmcid`, etc.) that gets lost? Shouldn't we serialize the CSV record and add into the full-text JSON, e.g., under attribute `csv_metadata` (since `metadata` is already taken).

**Comment by edwinzhng** [comment]
Yeah good point, it would be a good idea to standardize the raw field to be the same format across the board:

```
{
    "full_text": {...} or null,
    "csv_metadata": {...}
}
```

**Comment by lintool** [comment]
I propose something like this following, minimal modifications wrt original JSONs:

For abstract only:

```
{
   "cord_uid": ...
   "full_text": false,
   "csv_metadata": { ... }
}
```

For full-text:

```
{
   "cord_uid": ...
   "full_text": true,
   "csv_metadata": { ... }
   ... // rest of fields, inline as is - i.e., no additional layer of nesting
}
```

Thoughts? Can we get this in place in time for tonight's data drop?
