### ISSUE TITLE
Simplify solr loading

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1113]
I'm wondering if the managed schema can be simplified: https://github.com/castorini/anserini/blob/master/src/main/resources/solr/anserini/conf/managed-schema

In particular, there's all this non-English text fields that's not being used... along with lots of dynamic fields...

Could also eliminate the need to upload all the stopwords lists:
https://github.com/castorini/anserini/blob/master/src/main/resources/solr/anserini/conf/lang.zip

**Comment by eribeiro** [comment]
Hi, you could use the Alexander Rafalovitch's simple Solr config as a basis for this issue: https://github.com/arafalov/simplest-solr-config

References: 

* http://www.slideshare.net/lucidworks/rebuilding-solr-6-examples-layer-by-layer-presented-by-alexandre-rafalovitch-search-stack-solutions

* http://www.slideshare.net/arafalov/rapid-solr-schema-development-phone-directory
