### ISSUE TITLE
Replicate 20 newsgroup classification w/ scikit-learn + Anserini

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1120]
Let's try and replicate 20 newsgroup classification w/ scikit-learn using Anserini:
https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html

That is, use Anserini to extract the tf-idf vectors that feed the classifiers in scikit-learn.

Whoever is interested in taking this on, I can guide step by step, but the first step is to write Collection class to index 20 newsgroup in its raw original format.

**Comment by yuki617** [comment]
Currently working on this.

**Comment by yuki617** [comment]
This is the link for the jupyter notebook which replicated the 20newsgroup https://github.com/yuki617/anserini/blob/tfidf/20newgroup_replication.ipynb

**Comment by lintool** [comment]
Closing this issue and move over to https://github.com/castorini/pyserini/issues/99

The Anserini side has been completed, the rest to be done on the Pyserini end.
