### ISSUE TITLE
Phrase queries in Pyserini

### ISSUE THREAD

**Issue by Chriskamphuis** [castorini/anserini#1125]
We would like to be able to issue phrase queries using Pyserini. For this a few updates are needed on Anserini's side. I propose to implement the following:

- A phrase query generator
- A `phraseSearch` function in the `SimpleSearcher.java` class

**Comment by lintool** [comment]
Hi @Chriskamphuis do you want phrase queries in general or do you want `df` for phrases specifically. If you want the former, then Pyserini already exposes this:

https://github.com/castorini/pyserini/blob/master/pyserini/search/pysearch.py#L75

You can pass in your own query generator...

On the other hand, if you want `df` for phrases, the point of modification should be this: https://github.com/castorini/pyserini/blob/master/pyserini/index/pyutils.py#L127

**Comment by Chriskamphuis** [comment]
I want to get the `df`, so I thought this would be a first step. Great that it is already possible. Thanks for the links, I will modify the `IndexReaderUtils` instead. Do you think the best way would be to traverse the postingslist of the phrase terms (in the `df` function) to see whether they form a phrase?

**Comment by lintool** [comment]
I don't have any insight on what the best implementation is going to be... traverse postings ourselves or push off into a Lucene phrase query... but the latter is easier, so try first?

**Comment by Chriskamphuis** [comment]
Made available through https://github.com/castorini/anserini/pull/1154
