### ISSUE TITLE
Loading CORD-19 in Elasticsearch

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1150]
Might be interested in build the bindings to load CORD-19 into Elasticsearch - that we can get visualizations from Kibanna basically "for free".

**Comment by lintool** [comment]
@HangCui0510 You might be interested in working on this?

**Comment by HangCui0510** [comment]
Sure, I will look into it.

**Comment by lintool** [comment]
With ELK, I think we can replicate some of the views here directly out of the box?
https://scisight.apps.allenai.org/

**Comment by HangCui0510** [comment]
@lintool By indexing cord-19 into ElasticSearch, we are able to get visualizations from Kibana
<img width="748" alt="Screen Shot 2020-05-22 at 9 49 35 PM" src="https://user-images.githubusercontent.com/64120158/82719198-7dde0e00-9c76-11ea-9a75-4985765a9110.png">
<img width="890" alt="Screen Shot 2020-05-22 at 9 43 21 PM" src="https://user-images.githubusercontent.com/64120158/82719199-80406800-9c76-11ea-93e4-bf6311b23271.png">
<img width="811" alt="Screen Shot 2020-05-22 at 9 49 10 PM" src="https://user-images.githubusercontent.com/64120158/82719200-833b5880-9c76-11ea-82ec-e241402c2920.png">

**Comment by lintool** [comment]
cool!

Do you want to write up instructions and add to this doc? https://github.com/castorini/anserini/blob/master/docs/elastirini.md

@stephaniewhoo might be interested in playing with this also...

**Comment by HangCui0510** [comment]
Sure

**Comment by lintool** [comment]
Done: https://github.com/castorini/anserini/blob/master/docs/experiments-cord19-extras.md

Closing issue! Thanks @HangCui0510 !
