### ISSUE TITLE
Write a script that takes a run and subtracts qrels

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1157]
For generating residual runs for TREC-COVID. Takes:

+ a run
+ qrels

Generates a new run that has the qrels removed, up to a particular _k_ per topic. Reorders ranks to be consecutive, sanity check for score ties.

Put it in `src/main/python/trec-covid`?

**Comment by lukuang** [comment]
I wrote one for myself already. Will make some changes and do a PR

**Comment by x65han** [comment]
Oh nice!
