### ISSUE TITLE
MAP for ES regression on MS MARCO doc slightly different from Lucene values

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1173]
Follow up to #1167 

I ran this:

```
$ python src/main/python/run_es_regression.py --regression msmarco-doc --input /tuna1/collections/msmarco/doc
...
2020-05-08 14:34:32,376 INFO - [SUCESS] 0.2308 MAP verified as expected!
```

In the end I got .2308 MAP, but that doesn't actually match the .2310 MAP reported here: https://github.com/castorini/anserini/blob/master/docs/regressions-msmarco-doc.md

@HangCui0510 @eiston

**Comment by HangCui0510** [comment]
I ran this:
https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-doc.md

Instead of 0.2310 or 0.2308, I got:
<img width="487" alt="Screen Shot 2020-05-09 at 12 30 50 AM" src="https://user-images.githubusercontent.com/64120158/81464019-56724600-918c-11ea-9e03-d36b31703fa3.png">

**Comment by lintool** [comment]
@HangCui0510 hrm... can you debug and see what's going on?

**Comment by HangCui0510** [comment]
okay

**Comment by HangCui0510** [comment]
I think the problem is in [msmarco-doc config](url). I am making adjustments on mapping parameters to see what's going on. It takes a very long time for each run.

**Comment by HangCui0510** [comment]
@eiston Can you please help me with this? I have tried different mappings. they all give the same result 0.2308. I compared output run files among Solrini, Elastirini and Anserini, solrini and anserini are exactly the same, elastirini has the same doc ranking but double the scores.

**Comment by lintool** [comment]
@HangCui0510 Are the rankings (ordering of the documents) the same? Are the differences only isolated to a few different queries?

**Comment by eiston** [comment]
@HangCui0510 I am looking into this

**Comment by HangCui0510** [comment]
@lintool about 1000 out of 5000000 are different on retrieval with [topics.msmarco-doc.dev.txt](https://github.com/HangCui0510/anserini/blob/master/src/main/resources/topics-and-qrels/topics.msmarco-doc.dev.txt)

**Comment by HangCui0510** [comment]
@lintool the differences are on many topics but only 2-3 rankings are different on these topics.

**Comment by HangCui0510** [comment]
@lintool Oh, I think I know what the problem is. Please refer to the picture, it's the rounding that makes differences
<img width="716" alt="Screen Shot 2020-05-15 at 8 05 23 PM" src="https://user-images.githubusercontent.com/64120158/82105066-6be4f400-96e7-11ea-812d-891a124eb8f0.png">

**Comment by lintool** [comment]
Ah, I see. The rounding causes scoring ties, and that changes the map ever so slightly. I wonder why this same issue doesn't affect Solr? There, we can replicate results exactly, right?

**Comment by HangCui0510** [comment]
right, it seems like solr and anserini have the same score scales, they have the same ranking score values. Elastirini's score is higher, nearly double.

**Comment by HangCui0510** [comment]
@lintool Is this problem fixable? I noticed that elasticssearch with msmarco-passage also has a different value (slightly different) from [lucene regression](https://github.com/castorini/anserini/blob/master/docs/regressions-msmarco-passage.md)

<img width="436" alt="Screen Shot 2020-05-17 at 2 47 38 AM" src="https://user-images.githubusercontent.com/64120158/82137789-201a7380-97e9-11ea-95cc-5ce4ad399d35.png">

<img width="844" alt="Screen Shot 2020-05-17 at 2 51 02 AM" src="https://user-images.githubusercontent.com/64120158/82137820-4a6c3100-97e9-11ea-9563-86ff046e5c7b.png">

**Comment by lintool** [comment]
I don't think there's much we can do about this issue. Good to document, though, for future reference. Closing.
