### ISSUE TITLE
LuceneIndexing errors on lateset repo?

### ISSUE THREAD

**Issue by DylanJoo** [castorini/anserini#1178]
I have tried to reproduce the doc2query related experiment.  I cloned the lastest master repo, but indexing parts failed with the following errors. 
But I found out that it works on older branches.(say fastutil-removal) 
It's little bit confusing, not sure what the real problem is. 
(p.s. I run indexing on google colcab vm, and now it worked)

> 2020-05-10 07:52:42,088 ERROR [pool-2-thread-7] index.IndexCollection$LocalIndexerThread (IndexCollection.java:241) - pool-2-thread-7: Unexpected Exception:
java.lang.NoSuchMethodException: io.anserini.index.generator.LuceneDocumentGenerator.<init>(io.anserini.index.IndexArgs)
	at java.lang.Class.getConstructor0(Class.java:3349) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2553) ~[?:?]
	at io.anserini.index.IndexCollection$LocalIndexerThread.run(IndexCollection.java:158) [anserini-0.9.1-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

And the indexing results like this:(no indexing)
![螢幕快照 2020-05-10 下午6 10 58](https://user-images.githubusercontent.com/39515279/81496375-e679d200-92e9-11ea-963a-2161d33ea24e.png)

**Comment by lintool** [comment]
What instructions have you been following? Can you send link?

Should be `DefaultLuceneDocumentGenerator` instead of `LuceneDocumentGenerator`. Maybe we have outdated documentation that needs to be updated?

**Comment by DylanJoo** [comment]
@lintool Big thanks! `DefaultLuceneDocumentGenerator` works;)
Yes, it seems that the [dttttq](https://github.com/castorini/docTTTTTquery) & [doc2query](https://github.com/nyu-dl/dl4ir-doc2query) instructions need to be updated.

**Comment by lintool** [comment]
Can you please send PR with updates? That way we can acknowledge your contributions!

**Comment by DylanJoo** [comment]
@lintool OKay, I have PR the updates!
