### ISSUE TITLE
tests fail when under non UTF8 LANG setting

### ISSUE THREAD

**Issue by cmacdonald** [castorini/anserini#1199]
```
Failed tests:   testNonEnglishTopics(io.anserini.search.topicreader.TopicReaderTest): expected:<[?????????????????]> but was:<[《千里走单骑》和张艺谋是什么关系？]>
  testNonEnglishTopics_TopicIdsAsStrings(io.anserini.search.topicreader.TopicReaderTest): expected:<[?????????????????]> but was:<[《千里走单骑》和张艺谋是什么关系？]>
```

my LANG is en_GB.
if my LANG is en_GB.UTF-8 it works fine.

**Comment by lintool** [comment]
Ah, good call. We had related issues before, thought I whacked all the moles. Will go back to whacking more... The crux is UTF-8, since tests have non-Roman script.

**Comment by lintool** [comment]
Another mole whacked.

For future reference, since I had to "re-discover" the solution:

```
import java.util.Locale;
...

Locale.setDefault(Locale.US);
```
