### ISSUE TITLE
CORD-19 full-text JSON without title and abstract are not indexed

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1207]
@x65han discovered at least two documents that were not indexed:

```
egrep '(j36mqpus|enj5xt49)' metadata.csv
```
The issue can be verified in the 5/12 in data dump but exists in previous version as well. If we, for example, look at:

```
less document_parses/pdf_json/9f089d009338c25da7711ee4e6336ebdcad42a7a.json
```

We'll see that the full-text JSON has neither title nor abstract, and thus is not indexed. It seems like this is the correct course of action, but opening up issue to note this finding.

**Comment by lintool** [comment]
@x65han can you describe how you found these two ids?

They don't appear to be in the TREC-COVID round 1 qrels:

```
$ egrep '(j36mqpus|enj5xt49)' src/main/resources/topics-and-qrels/qrels.covid-round1.txt
```
Above command finds nothing...

**Comment by x65han** [comment]
I'm using the May 01 dataset, which should go beyond round 1 qrels, right?

**Comment by lintool** [comment]
The current indexer behavior seems to be reasonable. I don't think there's an action item, so closing issue.
