### ISSUE TITLE
Passage reranking for custom collection

### ISSUE THREAD

**Issue by dpr101** [castorini/anserini#1209]
Hi, 

It might be good to complete the [custom collection doc](https://github.com/castorini/anserini/blob/master/docs/custom-collections.md) with light instructions on passage reranking, after seeing [this issue](https://github.com/huggingface/transformers/issues/580). 

[pygaggle](https://github.com/castorini/pygaggle/tree/master/pygaggle) has been a well-bundled and transparent resource for the CORD-19, and for other text ranking in the future. Below is a bottom-up snapshot from what it provides. It is however free-style and therefore less formalized.

<br /><br />

### Rerank with monoBERT

Optionally, you could rerank the above retrieval results. We provide a minimum working example [`rerank_custom_collection.py`](https://gist.github.com/egzhbdt/3f74b8b7dfb855711682ddb0036bdbf5) for this.

The example follows [pygaggle](https://github.com/castorini/pygaggle/blob/master/pygaggle/run/evaluate_passage_ranker.py) and [duoBERT](https://github.com/castorini/duobert) (up to monoBERT in the figure below, figure source [here](https://github.com/castorini/duobert/blob/master/duobert_architecture.svg)), less the part to evaluate with ground-truth. 

It calls a reranker to score (query, passage) pairs. The reranker is a pre-trained transformer model on a general passage retrieval task such as MS MARCO. 

![monoBERT](https://user-images.githubusercontent.com/65098404/82335047-c5cf0d80-99b6-11ea-9e8f-1b18585231ba.png)

<b>Prepare Input Files from the `QuickStart` Step</b> 

* The initial retrieval result file, named above as `[OUTPUT_PATH]`.
* The query file, named above as `[QUERY_FILE_PATH]`.
* A mapping file between the passage id and the raw content mapping, named as `[PASSAGE_ID2TEXT_PATH]`.
    * This mapping file does not exist above. Write a simple script to convert the initial collection to this mapping file. 
    * Each line has the format of `docid[\t]passage_raw_text[\n]`. No header. We don't differentiate a document and a passage in this use case, so `docid` refers to the passage id. 

<b>Install Requirements</b>

Download the `requirements.txt` from [pygaggle](https://github.com/castorini/pygaggle/blob/master/requirements.txt), then do `pip install -r requirements.txt`.
 
<b>Download the Pre-trained Reranker</b>

Download [BERT_Base_trained_on_MSMARCO.zip](https://drive.google.com/open?id=1cyUrhs7JaCJTTu-DjFUqP6Bs4f8a6JTX) (roughly 1.1 G) from [nyu-dl/dl4marco-bert](https://github.com/nyu-dl/dl4marco-bert).

Unzip and save to a path called `[BERT_BASE_PSG_RETRIEVAL_MODEL_PATH]`.

<b><em>Note:</em></b> Different transformer version tends to read pre-trained model names slightly differently. You might need to tweak file names a bit for error message such as `file not found`. For example, rename `[BERT_BASE_PSG_RETRIEVAL_MODEL_PATH]` as lowercased, `bert_config.json` to `config.json`, and `model.ckpt-100000.index` to `model.ckpt.index`.

<b>Run Reranker with [`rerank_custom_collection.py`](https://gist.github.com/egzhbdt/3f74b8b7dfb855711682ddb0036bdbf5)</b>

    python rerank_custom_collection.py --search_output_file [OUTPUT_PATH] \
                --qid2query_file [QUERY_FILE_PATH] \
                --passage_text_file [PASSAGE_ID2TEXT_PATH] \
                --model_name_or_path [BERT_BASE_PSG_RETRIEVAL_MODEL_PATH] \
                --device [your_device_setting] --output_path [RERANKER_OUTPUT_PATH]

`[RERANKER_OUTPUT_PATH]` is the rerank output file. 

Each line has the format of `qid[\t]query_text[\t]docid[\t]passage_text[\t]score[\n]`.

<b>Screen results again, and iterate on this workflow!</b>

**Comment by lintool** [comment]
hey @egzhbdt cool, thanks for this!

After chatting with the team, we think this doc might be best in pygaggle itself? Maybe you could start a `docs/` directory for us and drop this in there? Please send PR. We could have mutual pointers between docs in anserini and pygaggle?

**Comment by lintool** [comment]
ref: https://github.com/castorini/pygaggle/issues/21

**Comment by lintool** [comment]
With the recent addition of bindings for the indexer in Python, I think this is resolved.

**Comment by Fatima-200159617** [comment]
Hi,
I am trying to find the **rerank_custom_collection.py**. It seems the page is not available. Please advice.

**Comment by lintool** [comment]
@ghost ?

**Comment by Fatima-200159617** [comment]
I appreciate if you can update on my request above.

**Comment by xeniaqian94** [comment]
Hi @Fatima-200159617 , are you looking for [rerank_custom_collection.py](https://gist.github.com/xeniaqian94/02a33ae450b3d53047b205525d4d09e6)?

**Comment by Fatima-200159617** [comment]
> 
> 
> Hi @Fatima-200159617 , apologize for the confusion and thanks for [this](https://github.com/castorini/pygaggle#a-simple-reranking-example). It was [rerank_custom_collection.py](https://gist.github.com/xeniaqian94/02a33ae450b3d53047b205525d4d09e6).

Great thanks.
