### ISSUE TITLE
Using Anserini from Python?

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#121]
Given the popularity of Python, would make sense to explore how Anserini could be called from Python. One option might be [Py4J](https://www.py4j.org/index.html), which is what Spark uses.

**Comment by lintool** [comment]
We should look at: http://lucene.apache.org/pylucene/index.html

**Comment by lintool** [comment]
Based on meeting today, @rosequ is assigned the lead on this task.

**Comment by salman1993** [comment]
To start, I have two functionalities in mind:

[4:58]  
(1) issue query from Python, get back ranked list.

[4:58]  
(2) fetch a particular document id and get back raw text.

**Comment by lintool** [comment]
Initial try with py4j as part of #139

**Comment by lintool** [comment]
We seem to have a workable solution, as part of #144 
Closing for now. Will reopen if we have issues with py4j.

**Comment by rosequ** [comment]
@lintool please reopen this issue

**Comment by lintool** [comment]
Assigning to @MeowFei

**Comment by lintool** [comment]
If we can't get PyLucene to work, maybe we can try alternatives?

I found [pyjnius](https://github.com/kivy/pyjnius) - maybe give that a try?

Just to explicitly lay this out: the annoying thing about Py4J is this:

>Note that the Java program must be started before executing the Python code above. In other words, the Py4J does not start a JVM.

From [Py4J homepage](https://www.py4j.org/) - this means that we first have to start a Java program, then start Python to connect to it. It would be nice if we could directly embed the JVM inside Python to avoid this step.

**Comment by MeowFei** [comment]
We tried to use Pyjnius to call RetrieveSentences, but we got the following exception:
`  File "src/main/python/RetrieveSentences.py", line 15, in <module>
    test = autoclass("org.apache.lucene.index.DirectoryReaders")
  File "/Users/mengfeiliu/anaconda/lib/python3.6/site-packages/jnius/reflect.py", line 158, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 25, in jnius.find_javaclass
jnius.JavaException: Class not found b'org/apache/lucene/index/DirectoryReaders'
`
We did some debugging but it didn't seem to help. We are still looking into this issue.

**Comment by lintool** [comment]
Classpath issue? http://pyjnius.readthedocs.io/en/latest/api.html#jvm-options-and-the-class-path

**Comment by MeowFei** [comment]
The CLASSPATH is set to "./target/anserini-0.0.1-SNAPSHOT.jar"
