### ISSUE TITLE
Multi-threaded Search

### ISSUE THREAD

**Issue by davidmrau** [castorini/anserini#1211]
I am trying to run a multi-threaded search using `SearchCollection` with `-threads` > 1, eg. 5. However, looking at the CPU load I see only one core is fully occupied and therefore the search is really slow. Is there something additional I need to take care of besides setting the  number of `threads` as a flag?

Thanks in advance!

**Comment by lintool** [comment]
Hi @davidmrau for `SearchCollection`, `-threads` provides parallelism at the run level, for tuning parameters. I.e., it _doesn't_ run queries on multiple threads, it runs _all_ queries on a single thread, but parallelizes across different parameter settings.

If you want to run queries in parallel, we've been writing our own driver programs - see, for example: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SearchMsmarco.java

**Comment by davidmrau** [comment]
Thanks for the clarification. I'll have a look!

**Comment by lintool** [comment]
We're in the processing of building equivalent search functionality from the Python end: https://github.com/castorini/pyserini/blob/master/pyserini/search/__main__.py

Adding multi-threading support at the query level there is a possibility. You're welcome to contribute... or wait for us to (eventually) implement it! :)
