### ISSUE TITLE
Eval tools for anserini/pyserini

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1216]
As we expose more functionalities in pyserini, it becomes useful to do evaluations directly from that repo, without needing to clone anserini. What about our standard eval tools like `trec_eval`?

There are few options:
1. put all eval tools in `anserini` repo
2. put all eval tools in `pyserini` repo
3. put all eval tools in separate repo
4. keep copies in both? (sync manually?)
5. git submodules? (never used this feature before but seems appropriate?)

I suppose this applies to pygaggle as well...

@rodrigonogueira4 @edwinzhng @ronakice thoughts?

**Comment by rodrigonogueira4** [comment]
git submodules seem the right choice, but I used it only once, so maybe someone with more experience can comment about it?

If not, keeping copies in both anserini and pyserini would be my next choice.

**Comment by ronakice** [comment]
Yes, this does apply to pygaggle too. In fact, I was debating what I should do for the instructions yesterday with regards to `msmarco_eval.py` and temporarily decided to just go with a separate copy. However, it does seem like 5 is most appropriate (which I've never used to haha)!

**Comment by edwinzhng** [comment]
Yep git submodules are good! I think you still need to sync them manually occasionally using `git submodule update` (so that everyone who clones will get the same submodule commit). Other than that, it's pretty clean and simple for this use case.

**Comment by lintool** [comment]
I'll do this when I get a chance.
