### ISSUE TITLE
Implement neural retrieval models

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#124]
Mostly a placeholder, but we should implement the various neural retrieval models out there in Anserini

**Comment by lintool** [comment]
Eric Nalisnick, Bhaskar Mitra, Nick Craswell, and Rich Caruana. "Improving document ranking with dual word embeddings." WWW 2016 Poster.

**Comment by HTAustin** [comment]
A Deep Relevance Matching Model for Ad-hoc Retrieval
http://ciir-publications.cs.umass.edu/getpdf.php?id=1247

**Comment by lintool** [comment]
Per #239 - neural retrieval models should be implemented in Castor. Closing.
