### ISSUE TITLE
Move eval/measure_judged.py improvements over to anserini-eval repo

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1247]
Hey @adamyy can you remake your PR `[#1166] eval/measure_judged.py improvments (#1246)` against this repo? https://github.com/castorini/anserini-eval

We're in the process of migrating over to `anserini-eval` as a submodule shared across multiple repos, as in: https://github.com/castorini/pyserini/

**Comment by adamyy** [comment]
Sure thing! Will work on it soon.

**Comment by lintool** [comment]
Closed by https://github.com/castorini/anserini-eval/pull/3
