### ISSUE TITLE
TREC Car Tools Dependency error

### ISSUE THREAD

**Issue by MarcosFP97** [castorini/anserini#1249]
Hi! First of all, thank you for your awesome work. I've cloned this repository and I am trying to build the project but I always came across with the same error:

`[ERROR] Failed to execute goal on project anserini: Could not resolve dependencies for project io.anserini:anserini:jar:0.9.4-SNAPSHOT: Failed to collect dependencies at com.github.TREMA-UNH:trec-car-tools-java:jar:17: Failed to read artifact descriptor for com.github.TREMA-UNH:trec-car-tools-java:jar:17: Could not transfer artifact com.github.TREMA-UNH:trec-car-tools-java:pom:17 from/to jitpack.io (https://jitpack.io): NullPointerException -> [Help 1]`

I have tried to modify the pom.xml and update package version to 17 as it is said in the original repo: [https://github.com/TREMA-UNH/trec-car-tools](url), but nothing seems to work.
I would appreciate any kind of help.

**Comment by lintool** [comment]
What version of Java are you on? What OS? Weird, no one I know has encountered this issue before...

**Comment by MarcosFP97** [comment]
I am using Java 11.07 and Centos 7

**Comment by lintool** [comment]
I just removed my Maven cache and rebuilt from scratch:

```
...
Downloading from public: https://repo1.maven.org/maven2/com/github/TREMA-UNH/trec-car-tools-java/13/trec-car-tools-java-13.pom
Downloading from AnseriniMaven: https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/com/github/TREMA-UNH/trec-car-tools-java/13/trec-car-tools-java-13.pom
Downloading from jitpack.io: https://jitpack.io/com/github/TREMA-UNH/trec-car-tools-java/13/trec-car-tools-java-13.pom
Downloaded from jitpack.io: https://jitpack.io/com/github/TREMA-UNH/trec-car-tools-java/13/trec-car-tools-java-13.pom (3.1 kB at 2.4 kB/s)
...
```

It was successful, but you seem to be trying to grab a more recent version of the jar... why?

The issue is likely that the authors of treccar haven't properly published the artifacts on their end...

**Comment by MarcosFP97** [comment]
I have also tried to clean Maven cache and it still doesn't work. Related to the artifact version, I decided to upgrade to 17 since with 13 didn't work too... should I try with an earlier one?

**Comment by lintool** [comment]
I'm sorry, I don't know how to help... I'm unable to replicate the error you're getting, so I can't help you...

**Comment by MarcosFP97** [comment]
Don't worry. I will keep trying and if I find the problem I will post it in here in case somebody has a similar problem. Thanks for your help!
