### ISSUE TITLE
SPL forbids SPL

### ISSUE THREAD

**Issue by kevinmartinjos** [castorini/anserini#1256]
[This](https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SearchArgs.java#L176) line contains `spl` in the forbids list, and that seems wrong.

**Comment by lintool** [comment]
Yup, that's a bug. Mind sending a quick PR? Thanks!

**Comment by kevinmartinjos** [comment]
@lintool [Here](https://github.com/castorini/anserini/issues/1256) you go :)

**Comment by lintool** [comment]
Thanks! Closed by #1257
