### ISSUE TITLE
Removed unused code in TREC News Tracks background linking baseline

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1258]
For background linking, we have regressions for BM25, BM25+RM3, and BM25+RM3+DF: https://github.com/castorini/anserini/blob/master/docs/regressions-backgroundlinking18.md

I would like to remove code that's not involved in running one of those three conditions:

+ The other configurations and code paths are not tested.
+ According to TREC 2018 results, the other configurations aren't as effective anyway.

@Peilin-Yang is this okay with you? This is your code...
@PepijnBoers @Chriskamphuis I assume this is okay with you also?

**Comment by Peilin-Yang** [comment]
I am okay to remove the unused code, thanks

**Comment by Chriskamphuis** [comment]
:+1: for me
