### ISSUE TITLE
What do we do with common code?

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1272]
With https://github.com/castorini/pyserini/pull/179 we've exposed end-to-end indexing/search in Python.

Our guide can now be ported over to Python!
https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md

However, what do we do about all the scripts here?
https://github.com/castorini/anserini/tree/master/src/main/python/msmarco

It seems like exactly the same issue with #1216

One proposal might be that "eval" submodule should really be all common code... so we'd have `common/eval`, `common/scripts`...

Thoughts? @rodrigonogueira4 @ronakice

**Comment by ronakice** [comment]
> * One proposal might be that "eval" submodule should really be all common code... so we'd have common/eval, common/scripts...
Yes, I think that is a good idea. Although, I don't really like the name "common" for the submodule. "utils"/"tools" or something along those lines?

**Comment by lintool** [comment]
Closed by #1282
