### ISSUE TITLE
Unindexable meaning

### ISSUE THREAD

**Issue by MarcosFP97** [castorini/anserini#1274]
Hi, 
I am using CommonCrawlWarcCollection specifically developed for ingesting TREC Health Misinformation Track (2020). However, I am obtaining a high number of unindexable docs. Is this normal? Under which circumstances a doc is classified as unindexable?
Thanks a lot

**Comment by MXueguang** [comment]
https://github.com/castorini/anserini/issues/1259#issuecomment-640024026

Common Crawl WARC contains WARC request for each response. the requests are not indexable. So you will see roughly 1:1 rate of indexable v.s. unindexable. Also, each WARC files has a file header, unindexable as well

**Comment by MarcosFP97** [comment]
Ok, thanks!
