### ISSUE TITLE
Add documentation for FEVER baseline

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1289]
In the FEVER paper: https://www.aclweb.org/anthology/N18-1074/

Table 2:
<img width="305" alt="Screen Shot 2020-06-17 at 7 33 50 AM" src="https://user-images.githubusercontent.com/313837/85028237-d060fc00-b148-11ea-8f5d-c8ff44d1fdc5.png">

We should add documentation that compares Anserini baselines directly to results in this table.

cc/ @ronakice @kelvin-jiang

**Comment by ronakice** [comment]
Yup, @kelvin-jiang is on it!

**Comment by ronakice** [comment]
Close?
