### ISSUE TITLE
Alternative functions to dump all document ids?

### ISSUE THREAD

**Issue by nsndimt** [castorini/anserini#1294]
The IndexUtils.java has been deleted in a recent commit #1255. I find the dumpAllDocids option very useful and want it back. 
I do not find any function in Pyserini that can export all document's external ids. So, I think we should add this function to [IndexReaderUtil.java](https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexReaderUtils.java) and expose it in the Pyserini.

**Comment by lintool** [comment]
See https://github.com/castorini/pyserini/#how-do-i-fetch-a-document
