### ISSUE TITLE
RM3 expanded queries

### ISSUE THREAD

**Issue by Fatima-200159617** [castorini/anserini#1319]
Hi, 
Could you please let me know if there is a way to get the expanded queries using Anserini RM3 implementation.
I managed to retrieve passages of the MSmacro dataset by setting -rm3 as a parameter but what I need is the expanded queries themselves.

**Comment by lintool** [comment]
See: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/rerank/lib/Rm3Reranker.java#L62

There's a `outputQuery` flag to print out queries.

**Comment by Fatima-200159617** [comment]
Thanks.
Since I am using searchMsmacro I modifed the 'false' parameter to 'true' in the below part of code and I did not get any output
![image](https://user-images.githubusercontent.com/32257669/87560939-aa396800-c6c4-11ea-9541-880d1cb38162.png)
Then I modifed the file you mentioned above where I set the outputQuery to 'true' still did not work
![image](https://user-images.githubusercontent.com/32257669/87561141-ef5d9a00-c6c4-11ea-9e3e-062acd79d1a7.png)
**am I supposed to get the outputs in logs folder ?**

**Comment by Fatima-200159617** [comment]
Thanks. Solved by updating Rm3Reranker.java

**Comment by cramraj8** [comment]
Currently, the default option is set to false, how to change it true in command line ? (command line argument is true/false or 1/0)

**Comment by cramraj8** [comment]
Never mind, I just realized providing -rm3.outputQuery argument enables it.
