### ISSUE TITLE
Integrate APIs for Freebase and other knowledge graphs

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#134]
Starting this issue as a placeholder for discussion with @minafarid et al.

We need to be able to access Freebase and knowledge graphs from Anserini - what form that takes is up for discussion, but this is needed for entity linking, relational extraction, etc.

**Comment by minafarid** [comment]
I already have Freebase  RDF data uploaded to one of our servers (latest version, before Freebase retired). The data is imported into Virtuoso (RDF store) and exposed through a RESTful API. Querying Virtuoso is done using SPARQL. The same endpoint also contains DBPedia RDF (from 2014 or 2015 I think).

**Comment by lintool** [comment]
How big is the Freebase RDF data? Is there an embedded option, e.g., using Apache Jena?
Or could we even throw the triples into Lucene?
I think in this context we really just want point lookups of triples, right?
This could reduce external dependencies.

**Comment by lintool** [comment]
@minafarid Additional thought on this - at some point in time we need to index the entities in the KB itself so we can do entity linking (e.g., partial matches on names)... which we'll need Lucene for anyways. So if we can squeeze everything into Lucene, that will simplify our dependencies.

**Comment by lintool** [comment]
We should take a look at this:
http://www.isi.edu/isd/LOOM/kres/freebase-tools/

**Comment by lintool** [comment]
Assigning this task to @salman1993

**Comment by minafarid** [comment]
I indexed freebase using http://www.isi.edu/isd/LOOM/kres/freebase-tools/

**Summary**
The tool performs indexing on two steps: 
1. Compress the URIs and Properties in the RDF triples (e.g., compress `http://rdf.freebase.com/` to `f_`). Kind of prefix compression. This is done using a `bash` script
2. Index the compressed triples using Lucene. This is done using `java`.

**Results**
* The compression script is very buggy and doesn't work on ubuntu.
* I ignored the compression script and ran the indexing directly on the full data.
* Indexing took ~ 2.5 hours on a 64-core machine with 256 GB ram, but not all resources were utilized during the indexing process. The documentation says that the compressed version would take 70 minutes to compress.
* Index size ~ 37 GB. Compressed version should be 13 GB

**Comment by minafarid** [comment]
**Query expressiveness**

- It is easy to retrieve all or a subset of properties for a particular resource/entity.
- More complex queries is claimed to be available through coding
- Freebase-tools is not a replacement for sparql interfaces

**Placeholder for performance comparison against virtuoso**
