### ISSUE TITLE
How to use learning to rank in Anseini?

### ISSUE THREAD

**Issue by Aaashley** [castorini/anserini#1347]
I have created a background linking task index based on anserini. What is the pipeline to do rerank.How to use the ltr module  in Anserini.(How to run it?How to add feature?How to select feature?How to train and test?)I can't find the document about the usage of ltr.
Thanks

**Comment by lintool** [comment]
hi @Aaashley thanks for your interest. The LTR pipeline is current not working and need to be revamped. It's on our todo list...
