### ISSUE TITLE
How to "Raw" Index using Anserini?

### ISSUE THREAD

**Issue by Mistobaan** [castorini/anserini#1353]
To make sure I understand and master the full pipeline I want to create the tokens from the documents myself (i.e. skipping the built-in stemming and tokenization) and index the generated tokens using the Lucene index.
My questions:
- What is the best example to follow? 
- Is there any support in python?
- Any gotchas to be aware in using the Lucene index? (i.e. some inner optimization that prevents arbitrary sequence of characters to be valid terms).
- Can I directly specify the weight of each term or has to be the TF-IDF?

**Comment by lintool** [comment]
Hi @Mistobaan see https://github.com/castorini/pyserini/#how-do-i-search-my-own-documents

You'll need to disable stopword removal and stemming, and tokenize only on spaces. This is doable in Lucene but I'm not sure the right hooks are exposed in Python.

No, you cannot specify the weight of each term.

Hope this helps!

**Comment by Mistobaan** [comment]
Thank @lintool. Yes definitely helped in finding this document:
- https://github.com/castorini/pyserini/blob/master/docs/usage-analyzer.md
The core of the logic in breaking up the text is inside the Lucene Analyzer. 
I found these analyzers:
- [DefaultEnglishAnalyzer](https://github.com/castorini/anserini/blob/2e9b2673482361ae457f50adaaedb14bee82c8f9/src/main/java/io/anserini/analysis/DefaultEnglishAnalyzer.java)
- [LSHAnalyzer](https://github.com/castorini/anserini/blob/6f4b9bf7a44a655a628742b3709892cd923eec42/src/main/java/io/anserini/ann/lexlsh/LexicalLshAnalyzer.java) 
- [Freebase](https://github.com/castorini/anserini/blob/f31070616a55d8d7389f924c03df2a08b111ae4d/src/main/java/io/anserini/analysis/FreebaseAnalyzer.java)
- [FakeWordsEncoderAnalyzer](https://github.com/castorini/anserini/blob/6f4b9bf7a44a655a628742b3709892cd923eec42/src/main/java/io/anserini/ann/fw/FakeWordsEncoderAnalyzer.java)
- [TweetAnalyzer](https://github.com/castorini/anserini/blob/f31070616a55d8d7389f924c03df2a08b111ae4d/src/main/java/io/anserini/analysis/TweetAnalyzer.java)

With the new keyword/term (Lucene Analyzer) I was able to find out the Lucene feature to make the custom term frequency: https://issues.apache.org/jira/browse/LUCENE-7854 
- https://lucene.apache.org/core/7_4_0/core/org/apache/lucene/analysis/tokenattributes/TermFrequencyAttribute.html
and a good document that explains more of the internal objects:
https://lucene.apache.org/core/4_0_0/core/org/apache/lucene/search/package-summary.html#scoring

Now the follow-up question is: If I create the custom/index in anserini/lucene how does it translate to ElasticSearch (to have distributed computing)?
I see that there is some sort of support for [elastic search](https://github.com/castorini/anserini/blob/2d8359c917c0a54d2b239cd02e289b3b4790a6bb/docs/experiments-cord19-extras.md#elasticsearch--kibana) but does it just send the raw JSON document through ElasticSearch' API and let ES re-create the index? or does it send chunks of the serialized index? 
I see:
-  the [various options for elastic search](https://github.com/castorini/anserini/blob/88418ee1b4d2f232104081314eff5902415e1e14/src/main/java/io/anserini/index/IndexArgs.java#L175)
-  then seems it [create a simple rest client](https://github.com/castorini/anserini/blob/88418ee1b4d2f232104081314eff5902415e1e14/src/main/java/io/anserini/index/IndexCollection.java#L607)
-  [connects to the collection](https://github.com/castorini/anserini/blob/88418ee1b4d2f232104081314eff5902415e1e14/src/main/java/io/anserini/index/IndexCollection.java#L810)
- [creates a bulk index request](https://github.com/castorini/anserini/blob/88418ee1b4d2f232104081314eff5902415e1e14/src/main/java/io/anserini/index/IndexCollection.java#L517)
- [IndexRequest is an ES Type](https://www.javadoc.io/doc/org.elasticsearch/elasticsearch/6.0.1/org/elasticsearch/action/index/IndexRequest.html)
- [Create and populate the ES XContentBuilder](https://github.com/castorini/anserini/blob/88418ee1b4d2f232104081314eff5902415e1e14/src/main/java/io/anserini/index/IndexCollection.java#L493) 
So if I can read the code well, to answer my own question, the ES indexer sends only some of the fields and only string/int or arrays. Now I am still not sure if ES will re-tokenize those and how I will have to read the code on that side to find out how those objects are stored/indexed. It seems that the XContentBuilder has a lot of capabilities and switches to populate the fields.

**Comment by lintool** [comment]
@Mistobaan 
> I see that there is some sort of support for elastic search but does it just send the raw JSON document through ElasticSearch' API and let ES re-create the index?

This ^^^^ There's no way for ES to "import" a Lucene index directly. It needs to re-index from scratch.

So, you'll need to set the tokenizer appropriately from the ES end, by twiddling with the ES configs, like here: https://github.com/castorini/anserini/blob/2d8359c917c0a54d2b239cd02e289b3b4790a6bb/src/main/resources/elasticsearch/index-config.cord19.json

**Comment by Mistobaan** [comment]
Thanks!
