### ISSUE TITLE
TopicReader for TREC CAsT topic

### ISSUE THREAD

**Issue by Arlo10veSu** [castorini/anserini#1354]
I'm trying to make retrieval for TREC CAsT data. But i meet some pronlem when perform the retrieval. It all failed while i changed different topicreader. The CAsT provided various format of topic file as follow. So which topicreader should i use for the data?

Json:

{
    "number": 31,
    "description": "A person is trying to compare and contrast types of cancer in the throat, esophagus, and lungs.",
    "turn": [
      {
        "number": 1,
        "raw_utterance": "What is throat cancer?"
      },
      {
        "number": 2,
        "raw_utterance": "Is it treatable?"
      },
      {
        "number": 3,
        "raw_utterance": "Tell me about lung cancer."
      },
      {
        "number": 4,
        "raw_utterance": "What are its symptoms? "
      },
      {
        "number": 5,
        "raw_utterance": "Can it spread to the throat?"
      },
      {
        "number": 6,
        "raw_utterance": "What causes throat cancer?"
      },
      {
        "number": 7,
        "raw_utterance": "What is the first sign of it?"
      },
      {
        "number": 8,
        "raw_utterance": "Is it the same as esophageal cancer?"
      },
      {
        "number": 9,
        "raw_utterance": "What\u0027s the difference in their symptoms?"
      }
    ],
    "title": "head and neck cancer"
  },

txt:

Number: 31
Title: head and neck cancer
Description: A person is trying to compare and contrast types of cancer in the throat, esophagus, and lungs.   
1	What is throat cancer?
2	Is it treatable?
3	Tell me about lung cancer.
4	What are its symptoms? 
5	Can it spread to the throat?
6	What causes throat cancer?
7	What is the first sign of it?
8	Is it the same as esophageal cancer?
9	What's the difference in their symptoms?

the annotations for topic,  tsv format:

  |31_1 | What is throat cancer?
  | 31_2 | Is throat cancer treatable?
  | 31_3 | Tell me about lung cancer.
  | 31_4 | What are lung cancer's symptoms?
  | 31_5 | Can lung cancer spread to the throat?
  | 31_6 | What causes throat cancer?
  | 31_7 | What is the first sign of throat cancer?
  | 31_8 | Is throat cancer the same as esophageal cancer?
  | 31_9 | What's the difference in throat cancer and esophageal cancer's symptoms?

**Comment by justram** [comment]
Hi,

For the retrieval task of TREC-CAsT data, it seems like you have built a corpus index for retrieval.
These topic files are your queries. If you have built index and want to facilitate a retrieval through anserini, you can use the following command:
```script=
${ANSERINI_PATH}/target/appassembler/bin/SearchMsmarco -index ${CAST_INDEX_DIR} -queries data/task_files/${QUERY}.tsv -output runs/run.cast.tsv
```

If you have not built your index file, you can use the following command to built your index.
(Follow the [guide from the hosts of CAsT](http://www.treccast.ai/) to download the corpus and run the deduplication process with the [TREC-CAsT tool](https://github.com/grill-lab/trec-cast-tools).
 
After your deduplication process, you will have the corpus in XML format.
Use the TrecwebCollection topic reader should be ok. 
```script=
${ANSERINI_PATH}/target/appassembler/bin/IndexCollection -collection TrecwebCollection -generator JsoupGenerator  -input ${CORPUS_XML_PATH} -index ${CAST_INDEX_DIR} -storePositions -storeDocvectors -storeRawDoc
```

**Comment by Arlo10veSu** [comment]
@justram 
Hi, many thanks. for your replay. 
I tried it and it really worked.  But i find that SearchMsmarco seems not support change rank algorirhm and query expand method through checking the code of SearchMsmarco. It only can work with bm25 and rm3. But if i want to try different method like the regression experiment used SearchCollection, what should i do? Convert the CAsT  topic file  into the format which can be used for the topicreader in SearchCollection?

**Comment by lintool** [comment]
@Arlo10veSu yup, the quickest way would be to convert the queries into one of the existing formats.

**Comment by Arlo10veSu** [comment]
@lintool Ok, thanks.
