### ISSUE TITLE
Inconsistent argument names for `qid_queries` between doc and code

### ISSUE THREAD

**Issue by tangsaidi** [castorini/anserini#1359]
The doc was updated recently in #1323, where the parameter was changed to `qid_queries`

https://github.com/castorini/anserini/blob/aba846aa07d6f319fb3dc9cb591c20b4ae69f9ef/docs/experiments-msmarco-passage.md#L63

However, the argument expected by the MSMarco program is `queries`

https://github.com/castorini/anserini/blob/aba846aa07d6f319fb3dc9cb591c20b4ae69f9ef/src/main/java/io/anserini/search/SearchMsmarco.java#L43

I'm not sure if we should revert the documentation change to conform with the code or simply change the argument name in the code.

resolves #1359

**Comment by lintool** [comment]
Please fix the documentation and send PR?
