### ISSUE TITLE
Is there ongoing work for a serverless anserini work?

### ISSUE THREAD

**Issue by syang** [castorini/anserini#1363]
I read this paper https://arxiv.org/pdf/2002.01447.pdf and I felt this by itself could be a huge architecture revolution for the IR infrastructure. I have two questions here:

1. The paper mentioned that the code repo is https://github.com/castorini/anlessini, but it's empty. I hope I am looking for the right place, and maybe the code will be available soon. But if it's not the case, can @lintool point me to the right repo?

2. The paper mentioned this mechanism can handle the index with the size of 700MB without problem, but I am wondering if this architecture can scale beyond larger index where a single lambda memory can't fit.

**Comment by lintool** [comment]
We're working on it... ;)

cc @shaneding

**Comment by shaneding** [comment]
Hey @syang sry bout the late reply, like @lintool mentioned I am currently working on this. Currently, if the actual index without raw documents exceed 700mb, then idt there is a way to scale.
