### ISSUE TITLE
Where is the target/ folder

### ISSUE THREAD

**Issue by ReyonRen** [castorini/anserini#1364]
Hi, I wonder where I can find target/ folder to run 
sh target/appassembler/bin/IndexCollection -threads 9 -collection JsonCollection \
 -generator DefaultLuceneDocumentGenerator -input collections/msmarco-passage/collection_jsonl \
 -index indexes/msmarco-passage/lucene-index-msmarco -storePositions -storeDocvectors -storeRaw 
for Msmarco Passage Retrieval? 
Thank you.

**Comment by lintool** [comment]
`target/` is automatically built by Maven. Did you follow the instructions in the README? https://github.com/castorini/anserini#getting-started

**Comment by ReyonRen** [comment]
> `target/` is automatically built by Maven. Did you follow the instructions in the README? https://github.com/castorini/anserini#getting-started

Thank you!
