### ISSUE TITLE
About how to change the default value

### ISSUE THREAD

**Issue by ReyonRen** [castorini/anserini#1365]
Hi, Thanks for sharing the data and source code!

I want to ask how can I change the default values of k1 and b in msmarco passage retrieval (k1=0.82 and b=0.68)?https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md

Thank you!

**Comment by lintool** [comment]
This is clearly specified here: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SearchMsmarco.java#L59
