### ISSUE TITLE
Modify file but not change in running progress?

### ISSUE THREAD

**Issue by ReyonRen** [castorini/anserini#1366]
Hi, sorry to bother.
I change the `src/main/java/io/anserini/search/SearchMsmarco.java`, but the running progess not change when I run `sh target/appassembler/bin/SearchMsmarco -hits 1000 -threads 1 -index ../DeepCT-master/lucene-index-msmarco.deepct -queries collections/msmarco-passage/collectionandqueries/queries.dev.small.tsv -output dev.score.try` again. Please help me, thank you!

**Comment by lintool** [comment]
>  the running progess not change

What does this mean?

**Comment by ReyonRen** [comment]
Sorry, I didn’t express it clearly. I wanted to get the score during BM25 retrieval, so I tried to modify the `src/main/java/io/anserini/search/SearchMsmarco.java` file. But re-run the command after the modification, it seems that my modification did not take effect, so I would like to ask how to get the score retrieved by BM25?

**Comment by lintool** [comment]
Did you rebuild with Maven?

**Comment by ReyonRen** [comment]
> Did you rebuild with Maven?

No. If I rebuild maven, it will be fine? 
Thank you！
