### ISSUE TITLE
Wrong path in Anserini Robust04 demo notebook

### ISSUE THREAD

**Issue by yuxuan-ji** [castorini/anserini#1373]
In this [notebook](https://github.com/castorini/anserini-notebooks/blob/master/anserini_robust04_demo.ipynb):
![image](https://user-images.githubusercontent.com/28494647/92539805-90be2380-f210-11ea-9697-45a081eb130f.png)

`cd eval` should be changed to `cd tools/eval`

**Comment by lintool** [comment]
Fixed!
