### ISSUE TITLE
Weighted Query 

### ISSUE THREAD

**Issue by Narabzad** [castorini/anserini#1377]
Hello,
Is there any way that I can run bm25 retrieval method with weighted query terms? I have different weights for different query terms and I need to do a weighted query term retrieval such as this example in Indri:
https://sourceforge.net/p/lemur/wiki/Indri%20Query%20Language%20Reference/

**Comment by lintool** [comment]
See: https://github.com/castorini/pyserini/blob/master/docs/usage-querybuilder.md

You might want to make sure you've read all the anserini/pyserini documentation first, because IIRC, the last couple of questions you've asked are already in the docs...
