### ISSUE TITLE
What the the equivalent of fbdocs of RM3 expansion in Axiom 

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#1382]
Dear Sir
I am making a research using Anserini and I want to be sure of something with you 

What is the equavilant of fbdocs and fbterms of RM3 in Axiom ?

After I looked for an answer  , 

![1](https://user-images.githubusercontent.com/47518534/93205233-5fcd7980-f74f-11ea-9838-5375253847e6.jpg)

RM3 fbterms is equavilant to axiom.top and 
for RM3 fbdocs I have two possible answers 
 
axiom.N is the total number of documents to work on ( fbdocs)
axiom.R is the number of randomly selected documents from axiom.N documents 

Am I right ? I just want to make sure how to choose fbdocs and fbterms in Axiom ?

**Comment by lintool** [comment]
No, there is not "equivalent" as axiomatic feedback works differently: see https://cs.uwaterloo.ca/~jimmylin/publications/Yang_Lin_ECIR2019.pdf
