### ISSUE TITLE
Snippet generation

### ISSUE THREAD

**Issue by MarcosFP97** [castorini/anserini#1384]
Hi!
I was wondering if there is a way to create highlighted search result excerpts in Anserini such as in Whoosh:

https://whoosh.readthedocs.io/en/latest/highlight.html#requirements

**Comment by MarcosFP97** [comment]
If there is not, I came to the idea that a naive approach could be to split each document in sentences using NLTK and consider each split as a different document. This should involve a parameter tuning for retrieval method such as BM25, for example.

**Comment by lintool** [comment]
Sorry about the late reply - maybe you can take advantage of spaCy for this? Check out: https://github.com/castorini/pyserini/blob/master/docs/working-with-spacy.md

Please re-open issue if there's follow-up...
