### ISSUE TITLE
Tool for timing the latency of feature extractor module

### ISSUE THREAD

**Issue by stephaniewhoo** [castorini/anserini#1387]
Currently, FeatureExtractorUtils only has a Pyserini interface and it has long processing time. We need a tool to timing the module.
By doing that, we can debug and detect time usage on per feature per doc etc.

**Comment by stephaniewhoo** [comment]
@nsndimt Do you want the timing tool be a separate Java class like what you did for cmd interface or after talked to @yuki617 , maybe we can add timing in https://github.com/castorini/anserini/blob/ca3aec84326a7506e6c1e8a9f79f52994e35cbd6/src/main/java/io/anserini/ltr/FeatureExtractorUtils.java#L91 this function

**Comment by lintool** [comment]
Depends on how heavy-weight the timing code is... you should measure the performance impact of having timing instructions, because we don't want the act of measurement to slow down the code itself...

**Comment by lintool** [comment]
@stephaniewhoo can this issue be closed? #1389 is merged, right?

**Comment by stephaniewhoo** [comment]
yes, closed by merged #1389
