### ISSUE TITLE
Request to check one of your measurements 

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#1390]
Dear Sir 
I hope that you check MAP measurement of CORE17 BM25 + Axiom ( Deterministic + rerankcutoff 20) 
![Core17Ax](https://user-images.githubusercontent.com/47518534/95698618-40d0e300-0c3a-11eb-8992-6f0e323e42bb.jpg)
![Core17Ax2](https://user-images.githubusercontent.com/47518534/95698619-41697980-0c3a-11eb-8c4d-95c1ebc250de.jpg)

Just to check : Does Deterministic variable Stabilize the results of Axiom ?

**Comment by lintool** [comment]
Based on the latest regression I ran a few days ago, the scores I'm getting is exactly the same as in the replication page: https://github.com/castorini/anserini/blob/master/docs/regressions-core17.md
