### ISSUE TITLE
Rename -selectMaxSegment

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1412]
I just noticed that in the context of -selectMaxSegment, we refer to passages as segments. Should we rename to "passage" instead to be consistent with the literature? So, `-selectMaxPassage` or even `-selectMaxP`?

Let's decide before this feature gets engrained in its usage so we don't have to change much documentation.

**Comment by rodrigonogueira4** [comment]
I prefer `-selectMaxPassage`

**Comment by lintool** [comment]
Okay, I will implement this, and then propagate changes to https://github.com/castorini/docTTTTTquery/issues/33
