### ISSUE TITLE
Qrels test cases

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1461]
Hey @MXueguang - while you're revamping the `Qrels` classes, can you add in a few simple tests?

<img width="594" alt="Screen Shot 2021-01-18 at 9 37 35 PM" src="https://user-images.githubusercontent.com/313837/104980778-66a61a80-59d5-11eb-9af4-91a25138b9a1.png">

Like a few tests cases to verify some of the above stats (from the book)? E.g., number of queries, qrels, avg qrels per query, etc. Should be pretty straightforward - iterate through the data structures and count, etc.

**Comment by MXueguang** [comment]
sure

**Comment by MXueguang** [comment]
The size of the topics has been tested in `TopicReaderTest`
so we only need to test the size of `qrels` and some qrels values in `QrelsTest` right?

**Comment by lintool** [comment]
Correct!
