### ISSUE TITLE
Difficult to set 'contents' boost with search fields option

### ISSUE THREAD

**Issue by jtibshirani** [castorini/anserini#1464]
When searching MS MARCO, it's possible to query over multiple fields using the option `-fields <field>=<boost>`. The resulting query is a disjunction over the `contents` field, plus the provided fields with their boosts applied.

This makes it harder to assign a weight to the `contents` field. Taking the example from #988 where we specify `-fields contents=1.0f -fields predictions=2.0f`, this would result in a query like

```
contents:value contents:value (predictions:value)^2.0
```

which is executed as

```
(contents:value)^2.0 (predictions:value)^2.0
```

Maybe the`-fields` option could be interpreted as fully defining fields + boosts instead of tacking on additional fields (as it is now)?

**Comment by lintool** [comment]
This is fine with me. The `fields` option was experimental, and nothing else in the code base depends on it... so okay to redefine the semantics of what the option means.
