### ISSUE TITLE
Questions about indexing Robust04 

### ISSUE THREAD

**Issue by yiyaxiaozhi** [castorini/anserini#1489]
I use the anserini-0.4.0 tool and run this command in /anserini-0.4.0.:
nohup sh target/appassembler/bin/IndexCollection -collection TrecCollection -input /home/xiaozhi/TREC2004Robust-master/Robust04 -index indexes/lucene-index.robust04.pos+docvectors+raw -generator DefaultLuceneDocumentGenerator -threads 16 -storePositions -storeDocvectors -storeRawDocs -storeTransformedDocs >& logs/log.robust04

and the logs show this error:
![image](https://user-images.githubusercontent.com/44088154/111873797-16473b00-89cd-11eb-8e63-899001aec803.png)

and my java version is here:
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
------------
while I change the generator to   `JsoupGenerator`, a new issue occurs:
this is the log :
![image](https://user-images.githubusercontent.com/44088154/111874837-e484a300-89d1-11eb-8523-a922151a5952.png)

It seems did not index any file in this processing.
The content file named doc_id and just contains doc_content instead of JSON format.
Should I gather all  files whose prefix is "LA" to a file with JSON format array like : 
[{'docids1':docid1,'doc1':doc1},{'docids2':docid2,'doc2':doc2}]
Could you please tell me how to fix this error?
Thanks a lot!

**Comment by lintool** [comment]
Two issues -

1. You're using a very old version of Anserini. v0.4.0 is dated March 4, 2019 and the instructions have changed. Please use the latest version.
2. Per our documentation, you'll need Java11: https://github.com/castorini/anserini#getting-started
