### ISSUE TITLE
Use Anserini from within an eclipse project

### ISSUE THREAD

**Issue by MarwaEssam** [castorini/anserini#1498]
I have my own Maven project and I built an inverted index for my dataset using Lucene V8.0 ... I can't perform query expansion though in Lucene. I wanted to use Anserini to load my index and perform the search with query expansion, but I found no document that guides me on how to do this. May you please help? I don't want to use Anserini externally as I have further processing on the results returned from the search before producing the output. 
 
An example of how to load an index using anserini (in java) would be mostly appreciated. Also how to search and perform query expansion (ex:RM3)

**Comment by lintool** [comment]
Unfortunately, Anserini is not designed to work with "generic" Lucene indexes, since it expects the fields to be named a certain way, etc.

I suppose you can build a Lucene index "outside" of Anserini and just make sure the fields are properly named, etc., but we have no experience with this...
