### ISSUE TITLE
sh: target/appassembler/bin/IndexCollection: No such file or directory

### ISSUE THREAD

**Issue by jl63** [castorini/anserini#1512]
When I am running the command 
``python3 src/main/python/trec-covid/index_cord19.py --date 2020-07-16 --all``
It will cause the error below:

Building abstract index...
sh: target/appassembler/bin/IndexCollection: No such file or directory
Building full-text index...
sh: target/appassembler/bin/IndexCollection: No such file or directory
Building paragraph index...
sh: target/appassembler/bin/IndexCollection: No such file or directory
Verifying abstract index...
sh: target/appassembler/bin/SearchCollection: No such file or directory
  File "tools/scripts/filter_run.py", line 45
    print(f'Read {len(docids)} docids from {args.whitelist}')
                                                           ^
SyntaxError: invalid syntax
/bin/sh: tools/eval/trec_eval.9.0.4/trec_eval: No such file or directory
Traceback (most recent call last):
  File "src/main/python/trec-covid/index_cord19.py", line 230, in <module>
    main(parser.parse_args())
  File "src/main/python/trec-covid/index_cord19.py", line 218, in main
    verify_indexes(args.date)
  File "src/main/python/trec-covid/index_cord19.py", line 144, in verify_indexes
    abstract_metrics = evaluate_run(f'verify.{date}.abstract.filtered.txt')
  File "src/main/python/trec-covid/index_cord19.py", line 119, in evaluate_run
    f'tools/eval/trec_eval.9.0.4/trec_eval -c -m ndcg_cut.10 {qrels} runs/{run}', shell=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'tools/eval/trec_eval.9.0.4/trec_eval -c -m ndcg_cut.10 src/main/resources/topics-and-qrels/qrels.covid-round3-cumulative.txt runs/verify.2020-07-16.abstract.filtered.txt' returned non-zero exit status 127.

In my target file, there is no appassembler inside it. Can you provide some suggestions on this problem? Thank you!

**Comment by MXueguang** [comment]
@jl63 Did you build anserini by `mvn clean package appassembler:assemble`?
following this https://github.com/castorini/anserini#getting-started

**Comment by MXueguang** [comment]
regarding python SyntaxError, it is caused by
https://github.com/castorini/anserini/blob/d808d4a50ee69f44493e19a87dc36c7eb99402a9/src/main/python/trec-covid/index_cord19.py#L124
We assume the default `python` is linked to `python3`, but I think it is linked to python2 in your environment

**Comment by jl63** [comment]
Thank you so much! I can run it successfully now!
