### ISSUE TITLE
Maven build issue

### ISSUE THREAD

**Issue by Tooba-ts1700550** [castorini/anserini#1518]
While executing the command
`! mvn clean package appassembler:assemble
`
I get the following error:
`BUILD FAILURE
[ERROR] Failed to execute goal org.codehaus.mojo:appassembler-maven-plugin:2.0.0:assemble (default-cli) on project anserini: Execution default-cli of goal org.codehaus.mojo:appassembler-maven-plugin:2.0.0:assemble failed: Plugin org.codehaus.mojo:appassembler-maven-plugin:2.0.0 or one of its dependencies could not be resolved: The following artifacts could not be resolved: net.java.dev.stax-utils:stax-utils:jar:20060502, stax:stax:jar:1.1.1-dev: Could not transfer artifact net.java.dev.stax-utils:stax-utils:jar:20060502 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
`

I am using Colab, and Java 11.
result of 
```
!java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode)
```

**Comment by MXueguang** [comment]
Hi @Tooba-ts1700550 
We have a demo of Anserini on Colab.
https://github.com/castorini/anserini-notebooks/blob/master/anserini_robust04_demo.ipynb
I just run this and it works.
See if it can help?

**Comment by lintool** [comment]
Having heard no follow-up, closing...
