### ISSUE TITLE
Converting TREC run to MSMARCO: clarification on WARNING

### ISSUE THREAD

**Issue by thibault-formal** [castorini/anserini#1523]
hi,
I was converting some trec runs to the MSMARCO format, and I have this warning (many many times):
`WARNING:root:Score of 45.231796 for doc id 4766294 is the same of doc id 3279842 for query id 1102400. This will likely impact metrics  negatively.` 

I understand what is happening, but:
* could you give some hints on why/how it "will likely impact metrics **negatively**". I understand it could impact metrics (different valid swapping), but why it would impact it *negatively* ?
* maybe I have a wrong intuition, but I felt that for term-based models like BM25, this should happen often ? Document sharing the same *tf* for each query term have the same score (but maybe it's not that common idk) ?

thanks in advance for your clarifications :)

**Comment by lintool** [comment]
Here's the tl;dr - it could happen if your score ties straddle a cutoff. For example, consider P@10 - if hit 10 and hit 11 are tied, and hit 10 happens to be relevant and hit 11 is non-relevant, you've gotten lucky. If the ties are broken differently and you change the _k_ as you're rewriting the rank list, your metric goes down...

Also, remember that `trec_eval` actually does it's own internal tie breaking... so in the above case, it might actually be hit 11 that's evaluated.

The scoring impact is generally small... but it _does_ happen, especially across many queries (like MS MARCO). From the perspective of reproducibility, it's annoying.

This is why in Anserini we explicitly do this:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/rerank/lib/ScoreTiesAdjusterReranker.java

If you want to full gory details, we wrote an entire paper about this issue:
https://dl.acm.org/doi/10.1145/3331184.3331339
