### ISSUE TITLE
Tuned BM25 for docT5query

### ISSUE THREAD

**Issue by thibault-formal** [castorini/anserini#1524]
Hi,
Unless I missed it, it seems that the results for the *tuned* BM25 with docT5query use the (k1=0.82, b=0.68) parameters obtained when tuning on the original collection: did you try to tune those on the expanded collection ? 
Thanks :)

**Comment by lintool** [comment]
That is correct... we didn't have time to re-tune. So BM25+docT5query just uses the base BM25 tuned parameters.

Yes, my hunch is that this tuning will make a difference for nDCG, MRR, MAP, etc. but won't make that much difference in R@1000 - which is what's important for neural reranking.

**Comment by thibault-formal** [comment]
ok great, thanks for the clarification @lintool ! 
I see; is it a general observation (like these parameters are more important for precision oriented measures, while recall is more stable) ?

**Comment by lintool** [comment]
Yes, I think this is a general finding.
