### ISSUE TITLE
Clarification on evaluating recall for TREC DL 2019 / 2020

### ISSUE THREAD

**Issue by thibault-formal** [castorini/anserini#1525]
Hi,
By digging on your documentation, I inadvertently stumbled upon this remark in the regression page for TREC DL 2020 ([here](https://github.com/castorini/anserini/blob/master/docs/regressions-dl20-passage-docTTTTTquery.md)): "Also, for computing nDCG, remember that we keep qrels of all relevance grades, whereas for other metrics (e.g., MAP), relevance grade 1 is considered not relevant (i.e., use the -l 2 option in trec_eval)." 

First thanks for pointing this, I completely forgot it and I might have made some evaluation mistakes on TREC... However, on the regression page for TREC DL 2019 ([here](https://github.com/castorini/anserini/blob/master/docs/regressions-dl19-passage.md)), you do not use the -l 2 option ? It should be the same right ?

**Comment by lintool** [comment]
I think you're right - this is on my stack to dig into a bit more detail...

**Comment by thibault-formal** [comment]
Hi @lintool 
I think it is actually important to clarify this, as I suspect results in some papers to be inaccurate... 

I reproduced on my side the evaluations for docT5query, matching your results. However, when discarding relevance grade = 1 for TREC DL 19 (so with -l 2 in `trec_eval`), recall results are greatly improved for docT5query (**bold** in the table). So for instance, evaluation for recall is not completely accurate in e.g. [TCT-ColBERT](https://arxiv.org/abs/2010.11386), but it is correct in [Efficiently Teaching an Effective Dense Retriever with Balanced Topic Aware Sampling](https://arxiv.org/abs/2104.06967). 

| model | TREC 19 ndcg@10 | TREC 19 recall@1000 | dev MRR@10 | dev recall@1000 | 
| - | - | - | - | - |
| docT5query - BM25 base | 0.642 | 0.802 [**0.831**] | 0.272 | 0.947 |
| docT5query - BM25 tuned | 0.648 | 0.801 [**0.827**]| 0.277 | 0.947 |
| simple siam BERT (mine) | 0.637 | 0.625 [**0.711**] | 0.312 | 0.941 | 

I also suspect that the same error has been made for evaluating ColBERT-TCT, for which recall should be higher too. For instance, I put the evaluation of a simple siamese I trained on the last row, and recall with -l 2 (**bold**) matches the *Bi-encoder (TCT-ColBERT)* reported in the paper.

It's not that big a deal, but as recall is maybe the metric we are more interested in, I think it's important that people correctly evaluate on TREC DL so that error don't propagate -- I did the mistake too so maybe I am not the only one.

**Comment by lintool** [comment]
Yes, I'm working on this right now... I believe you are correct. The numbers in the reproduction guide don't match the official TREC overview - https://arxiv.org/pdf/2003.07820.pdf but adding `-l 2` does...

So I'll need to fix here.

cc @jacklin64 and @justram on TCT issues.

Thanks for bringing this up!
