### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by KkEeVvIiNnn** [castorini/anserini#1534]
$ mvn clean package appassembler:assemble
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< io.anserini:anserini >------------------------
[INFO] Building Anserini 0.12.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from AnseriniMaven: https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/io/anserini/anserini-fastutil/6.5.6/anserini-fastutil-6.5.6.pom
Downloading from AnseriniMaven: https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/org/jetbrains/annotations-java5/maven-metadata.xml
[WARNING] Could not transfer metadata org.jetbrains:annotations-java5/maven-metadata.xml from/to AnseriniMaven (https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/): transfer failed for https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/org/jetbrains/annotations-java5/maven-metadata.xml
[WARNING] org.jetbrains:annotations-java5/maven-metadata.xmlfailed to transfer from https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of AnseriniMaven has elapsed or updates are forced. Original error: Could not transfer metadata org.jetbrains:annotations-java5/maven-metadata.xml from/to AnseriniMaven (https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/): transfer failed for https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/org/jetbrains/annotations-java5/maven-metadata.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.134 s
[INFO] Finished at: 2021-04-30T08:15:53Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project anserini: **Could not resolve dependencies for project io.anserini:anserini:jar:0.12.1-SNAPSHOT: Failed to collect dependencies at io.anserini:anserini-fastutil:jar:6.5.6**: Failed to read artifact descriptor for io.anserini:anserini-fastutil:jar:6.5.6: Could not transfer artifact io.anserini:anserini-fastutil:pom:6.5.6 from/to AnseriniMaven (https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/): transfer failed for https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/io/anserini/anserini-fastutil/6.5.6/anserini-fastutil-6.5.6.pom: Connect to raw.githubusercontent.com:443 [raw.githubusercontent.com/0.0.0.0, raw.githubusercontent.com/0:0:0:0:0:0:0:0] failed: Connection refused (Connection refused) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

my environment as follow:
$ java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

$ mvn -version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/wei_xu/anaconda3/opt/maven
Java version: 11, vendor: Oracle Corporation, runtime: /home/wei_xu/baselines/jdk-11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-123-generic", arch: "amd64", family: "unix"

**Comment by KkEeVvIiNnn** [comment]
seems https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/org/jetbrains/annotations-java5/maven-metadata.xml is a 404 page

**Comment by lintool** [comment]
Hrmmm... can't seem to replicate failure:

```
(python36) iMac-Pro:anserini jimmylin$ bin/build.sh 
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< io.anserini:anserini >------------------------
[INFO] Building Anserini 0.12.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from public: https://repo1.maven.org/maven2/org/jetbrains/annotations-java5/maven-metadata.xml
Downloading from AnseriniMaven: https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/org/jetbrains/annotations-java5/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/jetbrains/annotations-java5/maven-metadata.xml
Downloading from jitpack.io: https://jitpack.io/org/jetbrains/annotations-java5/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/jetbrains/annotations-java5/maven-metadata.xml (594 B at 1.8 kB/s)
Downloaded from public: https://repo1.maven.org/maven2/org/jetbrains/annotations-java5/maven-metadata.xml (594 B at 1.8 kB/s)
[INFO] 
```

@MXueguang what do you get?

**Comment by lintool** [comment]
Hearing no further follow up, closing.

Please reopen if there are additional issues.
