### ISSUE TITLE
how to get score of query and passage in msmarco-passage datasets?

### ISSUE THREAD

**Issue by yuhaia** [castorini/anserini#1547]
Hi, I'm replicating [transformer-kernel-ranking](https://github.com/sebastian-hofstaetter/transformer-kernel-ranking) which is a SOTA model in information retrieval task. And when I read README.md of [transformer-kernel-ranking](https://github.com/sebastian-hofstaetter/transformer-kernel-ranking) I found that it  need BM25 results from Anserini. Specifically, in [generate_validation_input_from_candidate_set](https://github.com/sebastian-hofstaetter/transformer-kernel-ranking/blob/master/matchmaker/preprocessing/generate_validation_input_from_candidate_set.py), it needs `candidate_file` whose format is like `2 Q0 1782337 1 21.656799 Anserini`. 

So I think that there should have score of query and passage like 21.656799 in BM25 results from Anserini. But I couldn't find how to get the score according to [Anserini: BM25 Baselines for MS MARCO Passage Ranking
](https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md). 

I submit a issue in [transformer-kernel-ranking](https://github.com/sebastian-hofstaetter/transformer-kernel-ranking) but the author seems to be not available now. So I wanna ask whether this project could get the score of query and passage/document in [MSMARCO](https://microsoft.github.io/msmarco/#ranking) datasets.

Thanks a lot!

**Comment by MXueguang** [comment]
Hi @yuhaia 
Try to replace the `SearchMsmarco` below by `SearchCollection`?
```
sh target/appassembler/bin/SearchMsmarco -hits 1000 -threads 1 \
 -index indexes/msmarco-passage/lucene-index-msmarco \
 -queries collections/msmarco-passage/queries.dev.small.tsv \
 -output runs/run.msmarco-passage.dev.small.tsv
```

**Comment by lintool** [comment]
Or https://github.com/castorini/pyserini/blob/master/docs/experiments-msmarco-passage.md#performing-retrieval-on-the-dev-queries

```python -m pyserini.search --topics msmarco-passage-dev-subset \
 --index indexes/lucene-index-msmarco-passage \
 --output runs/run.msmarco-passage.bm25tuned.txt \
 --bm25 --output-format msmarco --hits 1000 --k1 0.82 --b 0.68
```

Change `--output-format` to `trec`.

**Comment by MXueguang** [comment]
@yuhaia and if you prefer working with Python, you can look at Pyserini (i.e. @lintool's comment).

**Comment by yuhaia** [comment]
> Hi @yuhaia
> Try to replace the `SearchMsmarco` below by `SearchCollection`?
> 
> ```
> sh target/appassembler/bin/SearchMsmarco -hits 1000 -threads 1 \
>  -index indexes/msmarco-passage/lucene-index-msmarco \
>  -queries collections/msmarco-passage/queries.dev.small.tsv \
>  -output runs/run.msmarco-passage.dev.small.tsv
> ```
> 
> [EDIT]: need to add an argument `-topicreader TsvInt`

It's very nice of you guys to reply so soon. Thanks a lot~
