### ISSUE TITLE
RM3 only works for English

### ISSUE THREAD

**Issue by cash** [castorini/anserini#1570]
This is related to the JHU workshop.

I have a corpus that is not in English, but the Rm3Reranker has this line in it:

```java
if (!term.matches("[a-z0-9]+")) continue;
```
Would it be possible to have an argument on the constructor that either turns this off or supports passing in a custom filter?  For our use cases, we're probably fine with not having any filter, but since this is here it must have boosted performance on some data set and so I could see other use cases for custom filtering.

**Comment by lintool** [comment]
Hrm. Thanks for pointing that out. Turning off the filter is easy, but the tricky bit is figuring out how to expose it...

My initial reaction is to add a new option in `SearchArgs`: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SearchArgs.java#L265

Something like `-rm3.termFilter` set to true by default?

Thoughts?

**Comment by cash** [comment]
I agree that adding a boolean flag is the easiest way to turn filtering on or off. Having it default to true is necessary to not break anything. The name of the flag is reasonable. I can create a PR for this.

How do you handle propagating changes to pyserini? Do you limit changes to pyserini to what is exposed in the most recent release of anserini or do you work with snapshots and synchronize releases?

**Comment by lintool** [comment]
> I agree that adding a boolean flag is the easiest way to turn filtering on or off. Having it default to true is necessary to not break anything. The name of the flag is reasonable. I can create a PR for this.

Thanks!

> How do you handle propagating changes to pyserini? Do you limit changes to pyserini to what is exposed in the most recent release of anserini or do you work with snapshots and synchronize releases?

We build anserini and physically copy over the fat-jar - see instructions on a dev copy here:
https://github.com/castorini/pyserini/#development-installation

To expose to pyserini you'll need to expose the option in `SimpleSearcher` - something like this:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SimpleSearcher.java#L318

**Comment by lintool** [comment]
Closed by #1580
