### ISSUE TITLE
Can we extract bigrams using Anserini

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#1605]
Dear All
is there any way for shingling with anserini or extracting bigrams with their frequency as Unigrams

**Comment by lintool** [comment]
Try looking at the [`CJKAnalyzer`](https://lucene.apache.org/core/8_3_1/analyzers-common/org/apache/lucene/analysis/cjk/CJKAnalyzer.html) which generates bigrams.

**Comment by ABDULAZIZALQATAN** [comment]
Thanks Sir . I was thinking of [Shingle Filter](https://lucene.apache.org/core/6_0_1/analyzers-common/org/apache/lucene/analysis/shingle/ShingleFilter.html)

I will try them both
