### ISSUE TITLE
Fetch title and text of each document of Robust04 separately

### ISSUE THREAD

**Issue by Pourbahman** [castorini/anserini#1628]
Hi,

I used the following link but I do not know how to extract title and text of documents in Robust04 dataset.

 https://colab.research.google.com/github/castorini/anserini-notebooks/blob/master/anserini_robust04_demo.ipynb#scrollTo=2WIs-dMYY98u

Would you please guide me?

Thanks in advance,
Zahra

**Comment by Pourbahman** [comment]
Hi,

Kindly, it is about 11 days that I did not get any response. Would you please answer my question since I am a user of what you developed?

Thanks in advance,
Kind Regards,
Zahra

**Comment by lintool** [comment]
Hi @Pourbahman - you can use this method to access the actual document text: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SimpleSearcher.java#L661

Alternatively, you might be interested in our Pyserini toolkit, which has an easy to use Python interface:
https://github.com/castorini/pyserini/#how-do-i-fetch-a-document
