### ISSUE TITLE
Why Impact Searcher is much slower than BM25 Searcher?

### ISSUE THREAD

**Issue by namespace-Pt** [castorini/anserini#1683]
I noticed a big speed margin of BM25 Searcher over Impact Searcher, I also found the Impact Searcher **does not support multi-threads** searching. Why is Impact Searcher so slow?

**Comment by lintool** [comment]
Your answer is here: https://arxiv.org/abs/2110.11540

And, we're working on multi-threaded search here: https://github.com/castorini/anserini/pull/1678

**Comment by namespace-Pt** [comment]
Great. Thank you.
