### ISSUE TITLE
Can't Getting Started

### ISSUE THREAD

**Issue by MarliseLussa** [castorini/anserini#1689]
I getting started anserini according to the instructions of readme and tried it several times. There was always an error in MVN clean package appassembler: assembly. The error information is as follows:
（1）Downloading from maven-restlet:  https://maven.restlet.com/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom
(2)Downloading from releases.cloudera.com:  https://repository.cloudera.com/artifactory/libs-release-local/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom
(3)Downloading from maven-restlet:  https://maven.restlet.com/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
(4)Downloading from releases.cloudera.com:  https://repository.cloudera.com/artifactory/libs-release-local/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
Click the fourth link from the browser, and the web page displays status ": 404," message ":" file not found“

The subsequent error message is [error]  Failed to execute goal on project anserini: Could not resolve dependencies for project io.anserini:anserini:jar:0.13.6-SNAPSHOT: Failed to collect dependencies at org.apache.solr:solr-test-framework:jar:8.3.0 -> org.restlet.jee:org.restlet:jar:2.3.0: Failed to read artifact descriptor for org.restlet.jee:org.restlet:jar:2.3.0: Could not transfer  artifact org.restlet.jee:org.restlet:pom:2.3.0 from/to maven-restlet ( https://maven.restlet.com ): Connection reset -> [Help 1]
There are few tutorials and experience posts that can be found on the Internet. I really tried many methods that can't solve the problem. I look forward to receiving replies and guidance. Thank you very much!

**Comment by lintool** [comment]
What Java version are you using?

Have you tried Pyserini? https://github.com/castorini/pyserini/ That might be easier to get started...

**Comment by MarliseLussa** [comment]
1. Java version: 10.0.2, vendor: Azul Systems, Inc.
2. I originally wanted to use pyserini, I wanted to use pyserini's Development Installation, here I need to clone and build Anserini. Because After I have successfully built Anserini, I need to copy the fatjar, which will be target/anserini-XYZ-SNAPSHOT -fatjar.jar into pyserini/resources/jars/.

**Comment by lintool** [comment]
I wonder if it's an issue with Azul?

We've standardized on Java 11, openJDK. Can you try that?

**Comment by MarliseLussa** [comment]
I just tried Java version: 11.0.1, vendor: Oracle Corporation, and the same error message was reported.

**Comment by MarliseLussa** [comment]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.077 s
[INFO] Finished at: 2021-12-08T01:41:51Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project anserini: Could not resolve dependencies for project io.anserini:anserini:jar:0.13.6-SNAPSHOT: Failed to collect dependencies at org.apache.solr:solr-test-framework:jar:8.3.0 -> org.restlet.jee:org.restlet:jar:2.3.0: Failed to read artifact descriptor for org.restlet.jee:org.restlet:jar:2.3.0: Could not transfer artifact org.restlet.jee:org.restlet:pom:2.3.0 from/to maven-restlet (https://maven.restlet.com): Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by MarliseLussa** [comment]
mvn clean package appassembler:assemble
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< io.anserini:anserini >------------------------
[INFO] Building Anserini 0.13.6-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from public: https://repo1.maven.org/maven2/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom
Downloading from AnseriniMaven: https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom
Downloading from jitpack.io: https://jitpack.io/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom
Downloading from maven-restlet: https://maven.restlet.com/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom
Downloading from releases.cloudera.com: https://repository.cloudera.com/artifactory/libs-release-local/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom
Downloading from public: https://repo1.maven.org/maven2/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
Downloading from AnseriniMaven: https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
Downloading from jitpack.io: https://jitpack.io/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
Downloading from maven-restlet: https://maven.restlet.com/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
Downloading from releases.cloudera.com: https://repository.cloudera.com/artifactory/libs-release-local/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
Downloading from public: https://repo1.maven.org/maven2/org/jetbrains/annotations-java5/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/jetbrains/annotations-java5/maven-metadata.xml
Downloading from jitpack.io: https://jitpack.io/org/jetbrains/annotations-java5/maven-metadata.xml
Downloading from AnseriniMaven: https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/org/jetbrains/annotations-java5/maven-metadata.xml
Downloaded from public: https://repo1.maven.org/maven2/org/jetbrains/annotations-java5/maven-metadata.xml (722 B at 1.3 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/jetbrains/annotations-java5/maven-metadata.xml (722 B at 1.3 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.077 s
[INFO] Finished at: 2021-12-08T01:41:51Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project anserini: Could not resolve dependencies for project io.anserini:anserini:jar:0.13.6-SNAPSHOT: Failed to collect dependencies at org.apache.solr:solr-test-framework:jar:8.3.0 -> org.restlet.jee:org.restlet:jar:2.3.0: Failed to read artifact descriptor for org.restlet.jee:org.restlet:jar:2.3.0: Could not transfer artifact org.restlet.jee:org.restlet:pom:2.3.0 from/to maven-restlet (https://maven.restlet.com): Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by lintool** [comment]
Have you tried a web search with the error?

Also, we just upgraded to Lucene 8.11.0, which changed a bunch of dependencies. Try pulling master and retrying.

**Comment by MXueguang** [comment]
Hi @MarliseLussa,
I usually install mvn and openjdk via conda.
i.e.
```
conda install -c conda-forge openjdk=11
conda install -c conda-forge maven
```
it will handle many environment issue (e.g. config PATH etc.) by itelf

**Comment by MarliseLussa** [comment]
Thanks very very much to both of you! @MXueguang @lintool

**Comment by WeiShi-9** [comment]
> Hi @MarliseLussa, I usually install mvn and openjdk via conda. i.e.
> 
> ```
> conda install -c conda-forge openjdk=11
> conda install -c conda-forge maven
> ```
> 
> it will handle many environment issue (e.g. config PATH etc.) by itelf

amazing!
