### ISSUE TITLE
Take a look at ND4J

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#169]
We should take a look at ND4J: http://nd4j.org/

**Comment by rosequ** [comment]
@lintool where can we potentially use them in our existing code?

**Comment by lintool** [comment]
Here's an elaboration of this idea: I've been sitting on it for a bit to convince myself that it's worth doing.

Here's the deal: Python/Java integration has been a bit painful. However, the only magic in DL toolkits is the backprop: the feed forward part is pretty simple - it's just a bunch of matrix multiplication with activation.

So, why don't we train the model in PyTorch, "extract" the model, which is just a bunch of weight matrices, and run natively in Java? Then it'll integrate nicely with everything else in Lucene.

All we really need is a matrix library in Java, hence ND4J.

**Comment by lintool** [comment]
@tuzhucheng can you please summarize our findings in this thread, compared to PyTorch, and the profiling results. It appears that this is a dead end, but let's properly document our findings.

**Comment by tuzhucheng** [comment]
Although the model can be implemented in Java using ND4J, the running time is quite poor compared with that of Python using PyTorch.

Here are the running times for the feed forward on the `raw-dev` and `raw-test` datasets.

Java implementation using ND4J: 1260.73 real       724.20 user       726.83 sys
Python implementation using PyTorch: 40.30 real        30.30 user         4.89 sys

The Java implementation is ~20-30x slower.. 

If we instrument the Java program, we get the following results:

![image](https://user-images.githubusercontent.com/2687996/27405348-3e3a3eba-569f-11e7-9db7-43c85707147e.png)

We see that the matrix operations (e.g. multiplication, sum) take up 90% of the total running time. It is unlikely we can beat the Python running time even if we attempt to optimize the Java implementation.

**Comment by tuzhucheng** [comment]
The measurement that matrix operations for convolution take 90% of the total running time is consistent with the observations presented by Yangqing Jia at Facebook: https://atscaleconference.com/videos/deep-learning-in-production-at-facebook/ (10:50 - 11:30 in the video): "90% of time spent on convolution". They open-sourced an "acceleration package for neural network computations" called NNPACK (https://github.com/Maratyszcza/NNPACK) to be used by high-level deep learning packages like Torch.

**Comment by agibsonccc** [comment]
Hey folks - you're using a 2 year old version of nd4j. DL4j (https://github.com/deeplearning4j/deeplearning4j) has the current best practices.  If you want try benchmarking nd4j with numpy in python via jumpy: https://github.com/deeplearning4j/jumpy
