### ISSUE TITLE
Resolve inter-project dependency issues

### ISSUE THREAD

**Issue by tuzhucheng** [castorini/Anserini#172]
Current there is this in Anserini:

```python
from sm_model.bridge import SMModelBridge
```

We need to think about how we do inter-project dependencies. This requires us to put Castor inside Anserini I think. I propose we make each its own separate module that can be installed with pip. This way, projects can reside in their own directories and there is no need for nesting.

**Comment by rosequ** [comment]
@tuzhucheng we already handle this by using pip install, right?

**Comment by tuzhucheng** [comment]
Yes this is done sorry.
