### ISSUE TITLE
Cleanup deeplearning4j code

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#176]
I believe that after exploring deeplearning4j, we decided not to actually use it... so let's clean up the code and simplify the dependencies.

**Comment by rosequ** [comment]
This issue is resolved. Let's close it.

**Comment by agibsonccc** [comment]
Hey folks - Would love some input if you don't mind. If you had problems, would you at least mind filing an issue with the problems you had so we can fix them for others in the future? Thanks!
