### ISSUE TITLE
Help with reproduction - uniCOIL regressions

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1762]
I'd like someone to help with reproductions. Start with the following:

https://github.com/castorini/anserini/blob/master/docs/regressions-msmarco-passage-unicoil.md
https://github.com/castorini/anserini/blob/master/docs/regressions-msmarco-doc-segmented-unicoil.md
https://github.com/castorini/anserini/blob/master/docs/regressions-dl19-passage-unicoil.md
https://github.com/castorini/anserini/blob/master/docs/regressions-dl19-doc-segmented-unicoil.md
https://github.com/castorini/anserini/blob/master/docs/regressions-dl20-passage-unicoil.md
https://github.com/castorini/anserini/blob/master/docs/regressions-dl20-doc-segmented-unicoil.md

**Comment by lintool** [comment]
@manveertamber Can you please work on this? Also use it as a chance to read up about uniCOIL.

Check both the regression framework: https://github.com/castorini/anserini/blob/master/docs/regressions.md (should work directly from `orca`) as well as copy/paste from the pages (e.g., verify the download)... and do a pass on text also (typos, etc.)

Don't start yet, though - there's a known bug I need to fix first.

**Comment by lintool** [comment]
@manveertamber okay you can go now, I fixed issues with #1763

**Comment by manveertamber** [comment]
Everything looks good, except I did have trouble with getting all 3 scores from https://github.com/castorini/anserini/blob/master/docs/regressions-msmarco-doc-segmented-unicoil.md#effectiveness to appear. With `tools/eval/trec_eval.9.0.4/trec_eval -c -m map -c -m recall.100 -c -m recall.1000 src/main/resources/topics-and-qrels/qrels.msmarco-doc.dev.txt runs/run.msmarco-doc-segmented-unicoil.unicoil.topics.msmarco-doc.dev.unicoil.txt`. I only see the first 2 scores: MAP and R@100. Alternatively ` tools/eval/trec_eval.9.0.4/trec_eval -c -m map -c -m recall.1000 -c -m recall.100 src/main/resources/topics-and-qrels/qrels.msmarco-doc.dev.txt runs/run.msmarco-doc-segmented-unicoil.unicoil.topics.msmarco-doc.dev.unicoil.txt` shows me only the  MAP and R@1000 scores.

**Comment by lintool** [comment]
@manveertamber okay, I'll look into it - let's leave the issue open. In the meantime, can you send a PR with regression entries to the template and rebuild?

**Comment by mayankanand007** [comment]
FWIW I was able to get all 3 entries when I did the replication. I can try it again.
