### ISSUE TITLE
Getting error Could not transfer artifact org.apache.maven.plugins:maven-compiler-plugin:pom:(3.8.4) from/to artifactory.releases while changing maven version

### ISSUE THREAD

**Issue by rajyadav04** [castorini/anserini#1767]
I am getting below error when I am changing maven-compiler-plugin from 3.7.0 to 3.8.4. 

- Could not transfer artifact org.apache.maven.plugins:maven-compiler-plugin:pom:(3.8.4) 

I have 3.8.4 maven installed in my system, but still couldn't understand why it is throwing. 
![Screenshot (72)](https://user-images.githubusercontent.com/98162254/154220333-a7cb0f6c-f026-4e2d-a371-d04b82049d80.png)

![Screenshot (74)](https://user-images.githubusercontent.com/98162254/154220235-bbc7b08d-ca99-470f-aff5-dfcfb9688d05.png)

**Comment by lintool** [comment]
If you search for that error, Google gives you a few suggested fixes... try those?

This error doesn't seem to be related to anserini...

**Comment by rajyadav04** [comment]
> If you search for that error, Google gives you a few suggested fixes... try those?
> 
> This error doesn't seem to be related to answering...

I had tried a few ways suggesting like dependencies tags and a few other ways but didn't work.
What worked for me was to give the latest maven-compiler-plugin version instead of the upgraded version which I was keeping. 
So resolved.
