### ISSUE TITLE
AQUAINT index is Missing 2006 Files

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#1783]
Anserini AQUAINT default index is missing 2006 files 
The Index Files :  
![image](https://user-images.githubusercontent.com/47518534/155973184-58a11747-c713-44c2-8905-f90d23de10d8.png)

<img width="703" alt="1" src="https://user-images.githubusercontent.com/47518534/155973234-31b28cac-0335-4ef0-9dd3-0df6484fd901.png">

The Original Files  From [TREC Analysis Conference](https://tac.nist.gov//data/data_desc.html)

![image](https://user-images.githubusercontent.com/47518534/155975995-ff68a276-275a-4245-b283-08e6f32919fb.png)

<img width="960
[Courpus Additional Files pver Index.txt](https://github.com/castorini/anserini/files/8152907/Courpus.Additional.Files.pver.Index.txt)
" alt="2" src="https://user-images.githubusercontent.com/47518534/155973293-d05c4f72-63c4-4e92-9a11-39db52e9c26d.png">

This is a list of the additional files (2006) that are exist in the corpus but not in the index

[Additional Files](https://github.com/ABDULAZIZALQATAN/Issues/blob/main/Courpus%20Additional%20Files%20over%20Index.txt)

**Comment by lintool** [comment]
These appear to be empty documents. For example, consider:

```
<DOC>
<DOCNO> NYT19980611.0258 </DOCNO>
<DOCTYPE> NEWS STORY </DOCTYPE>
<DATE_TIME> 1998-06-11 19:06 </DATE_TIME>
<HEADER>
A5303 &Cx1f; ttj-z
u v &Cx13;  &Cx11;  BC-ELIMINATE-CONSERVATIV     06-11 0011
</HEADER>
<BODY>
<SLUG> BC-ELIMINATE-CONSERVATIVE-DEMOCRATS-HNS </SLUG>
  
 Thursday, June 11, 1998 
<TEXT>
<P>
</P>
</TEXT>
</BODY>
<TRAILER>
NYT-06-11-98 1906EDT &QL; 
</TRAILER>
</DOC>
```

So, not a bug. The indexer is correctly discarding empty docs.

**Comment by ABDULAZIZALQATAN** [comment]
Thanks Sir ... 👍 ... case closed
