### ISSUE TITLE
 trec-car-tools-java dependency Error

### ISSUE THREAD

**Issue by DreamsofGg** [castorini/anserini#1785]
Like #1249 and #1025 

Hi, it seems the url of trec-car-tools-java is broken, so I can't download it, how do I fix it? ( maybe a jar file could solve it?)

@lintool @MXueguang 

Thanks!

**Comment by lintool** [comment]
Do the solutions provided in those linked issues not work anymore?

**Comment by Capsar** [comment]
Hello,

I am getting a similar error, version 13 of trec-car-tools-java cannot be found. Even with the following repositories in the pom.xml:

`<repository>
      <id>public</id>
      <url>https://repo1.maven.org/maven2</url>
    </repository>`
`    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>`
`    <repository>
      <id>AnseriniMaven</id>
      <url>https://raw.githubusercontent.com/lintool/AnseriniMaven/master/mvn-repo/</url>
    </repository>`

To bypass the failing download I build the version myself by downloading version 13 from the trec-car-tools-java github.
And building it with `mvn clean install`

So I deleted the repository from .m2 folder.
Then I build trec-car-tools-java jar version 13 with the command above.
Then I build anserini again, and because trec-car-tools-java jar version 13 is present it continues.

It however still ends with 34 failures in the total of 521 tests. So it resulted in a failed build.

Will keep you updated with progress.

**Comment by laura-dietz** [comment]
I am the maintainer of trec-car-tools-java. So here is my thought...

I think this is an issue with jitpack. I realized that it sometimes has  some caching issues. 

the version 13 is still hosted on the git repository: https://github.com/TREMA-UNH/trec-car-tools-java/releases/tag/13

However, the latest version is 20 --- would it make sense to update?

**Comment by laura-dietz** [comment]
I can confirm the issue for version 13

[ERROR] Failed to execute goal on project treccar-tools-example: Could not resolve dependencies for project edu.unh.cs.treccar:treccar-tools-example:jar:0.1: Could not find artifact com.github.TREMA-UNH:trec-car-tools-java:jar:13 in jitpack.io (https://jitpack.io) -> [Help 1]
[ERROR] 

and 15
[ERROR] Failed to execute goal on project treccar-tools-example: Could not resolve dependencies for project edu.unh.cs.treccar:treccar-tools-example:jar:0.1: Failure to find com.github.TREMA-UNH:trec-car-tools-java:jar:15 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]


When I switch to version 16, ... 19, it works

[INFO] BUILD SUCCESS


I am appalled if jitpack is unable to serve older versions --- why would we be using those, if they grow defunct?

**Comment by laura-dietz** [comment]
I filed a ticket with jitpack

https://github.com/jitpack/jitpack.io/issues/4999

**Comment by lintool** [comment]
thanks @laura-dietz for tracking this down! BTW, why not publish to Maven Central?

so @Capsar - the fix is to upgrade to a newer version in `pom.xml`?

**Comment by laura-dietz** [comment]
@lintool maven central was too much of a pain to setup (need your own server to host, then have maven central pull from it).

Jitpack had the ease of use going for it.  If you know of an easy way I am happy to use it.  So far it worked quite smoothly. The weird thing is that I can see the [build log for v13](https://jitpack.io/com/github/TREMA-UNH/trec-car-tools-java/13/build.log)  was valid. I can even see it when I browse online.

I think it is some bug on jitpack, I hope they take a look at the issue.

I confirmed that it is working with v16 and up. We are trying out best to be backwards compatible to earlier versions. If there are issues: here the [link to the issue tracker](https://github.com/TREMA-UNH/trec-car-tools-java/issues)

**Comment by lintool** [comment]
> @lintool maven central was too much of a pain to setup (need your own server to host, then have maven central pull from it).

That's not true... sonatype provides staging/release services for free. Yes, I remember it being a pain to set up the first time, but after that, it works fine... also allows your artifact to be findable at https://search.maven.org/

Anyway, something to consider.

**Comment by lintool** [comment]
@DreamsofGg @Capsar Upgrading the jar version appears to have fixed the issue. Please re-open issue if you're still having trouble.

**Comment by Capsar** [comment]
Yes, it seemed to be an issue with jitpack.io

@lintool updating the pom.xml file to download the newer version of trec-car-tools-java does work. However, I don't know whether this brings any complications .

**Comment by laura-dietz** [comment]
@Capsar It was designed to be backwards compatible. If its not there is a bug (if there is a bug let me know and I will release a fixed version)
