### ISSUE TITLE
Revisit GeoSearch API design

### ISSUE THREAD

**Issue by d1shs0ap** [castorini/anserini#1796]
Potential changes to existing GeoSearch API:
- change method names from camel case to snake case
- consider replacing `QueryRelation` in Query with methods (e.g. `new_within_query`)
- rename `SimpleGeoSearcher` to `LuceneGeoSearcher` to stay consistent with renamed `SimpleSearcher`

**Comment by lintool** [comment]
There was some confusion between @d1shs0ap and I on Pyserini vs. Anserini... so, nm, what we currently have is fine.
