### ISSUE TITLE
SPLADE-distill CoCodenser-medium repro missing MS MARCO

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1815]
We should have the model for MS MARCO also, right?

**Comment by lintool** [comment]
hey @justram can we add for DL19 and DL20 also?

**Comment by justram** [comment]
> hey @justram can we add for DL19 and DL20 also?

Talked to Carlos earlier, but he is busy at the moment. 
We will get back to this on Monday.

**Comment by lintool** [comment]
Closed by #1813
