### ISSUE TITLE
Generate training data from Freebase index

### ISSUE THREAD

**Issue by minafarid** [castorini/Anserini#182]
* We need to retrieve training examples from Freebase index.
* The training examples can be used in machine learning applications.
* Depending on the target property, the retrieval queries will change to reflect how data is represented in Freebase RDF triples.

**Comment by Peilin-Yang** [comment]
@lintool Is this still relevant?

**Comment by lintool** [comment]
Closing, Freebase code removed in #329 - no longer relevant
