### ISSUE TITLE
The Output is not written directly  (Comment)

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#1849]
Dear All  
Thanks all for this great Lucene Tool 
I have been using Anserini for Years 
Jumping to the point. 

Before, when I run a retrieval process, it directly writes to the output file. This was useful because it allowed me to check the output during the process and check its size ( because I am running huge processes )
Now The Retrieval process is not written directly to the output file. But it keeps the results somewhere (buffer maybe) until it finishes the whole process.

Don't you think that writing to the output file directly is better?

**Comment by lintool** [comment]
Incremental writing of output file is no longer possible due to the recent addition of multi-threading. Because of multi-threading, queries finish at different times, so we need so synchronization. The easiest mechanism is to store all results in memory before dumping out to file at the end.
