### ISSUE TITLE
Refactor Rocchio impl to save work when there's no negative feedback

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1903]
In the current implementation, we compute the negative feedback vector no matter what:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/rerank/lib/RocchioReranker.java#L103

And we rely on gamma=0 to _not_ use negative feedback.

This means we are wasting effort computing the non-rel vector when, by default, we're not using it.

We should change the impl to check the use neg feedback flag, and skip this entire process if we can.

**Comment by lintool** [comment]
Also, @yuki617 - bottom feedback docs should be relative to `-hits` parameter... so if `-hits 1000`, the default, then 990-1000 (if bottom fb docs = 10). If `-hits 100`, then ranks 90-100.

**Comment by lintool** [comment]
Ref #1906

**Comment by yuki617** [comment]
> Also, @yuki617 - bottom feedback docs should be relative to `-hits` parameter... so if `-hits 1000`, the default, then 990-1000 (if bottom fb docs = 10). If `-hits 100`, then ranks 90-100.

Currently, bottom feedback doc always use the last 10 document from the hits, so if -hits is 1000, neg feedback should use 990-1000; if -hits is 100, neg feedback should use 90-100

**Comment by lintool** [comment]
Closed by #1906
