### ISSUE TITLE
Run HC4 with Lucene 9

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1910]
Look at #1875

Based on my preliminary tests, Lucene 9 has better analyzers for Russian. We should try HC4 and see if it makes a difference.

@ToluClassics can you try pulling this branch and running? Please report effectiveness differences here in issue?

**Comment by ToluClassics** [comment]
The scores are the same using Lucene 9.0 and 8.0

**Comment by lintool** [comment]
@ToluClassics I don't think this is true, but with #1960 the point is moot anyway. Closing issue.
