### ISSUE TITLE
Add option to SearchCollection to use hgf tokenizer

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#1988]
Hey @ToluClassics - I'm looking at the latest hgf wp regressions for MS MARCO, and it seems to be using pre-tokenized queries, e.g., [msmarco-doc-hgf-wp.yaml](https://github.com/castorini/anserini/pull/1987/files#diff-5d6e68bff68480485533f9e9517c00e60d086d902455339a8acc931bd8e897c6)

We should probably add an option in `SearchCollection` to use hgf tokenization?

**Comment by ToluClassics** [comment]
it uses the hgf tokenization for the queries as well

Here's the path to the queries

https://github.com/castorini/anserini/blob/4a9a97c9666da69db54ccdf308f17ebc606dd1e0/src/main/resources/regression/msmarco-doc-hgf-wp.yaml#L51

SearchCollection::

https://github.com/castorini/anserini/blob/4a9a97c9666da69db54ccdf308f17ebc606dd1e0/src/main/java/io/anserini/search/SearchCollection.java#L407-L408

**Comment by lintool** [comment]
Ah, sorry I misread the PR.
