### ISSUE TITLE
Indexer bindings for Wikipedia

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#205]
Let's add into Anserini the ability to index Wikipedia so we can run the QA pipeline on it. We can use [this package to parse and clean-up Wikipedia text](https://github.com/lintool/wikiclean).

**Comment by rosequ** [comment]
@lintool the package mentioned in the hyperlink says "Not found". Can you share the link with us?

**Comment by lintool** [comment]
Fixed link.

**Comment by MeowFei** [comment]
WikiClean has already been used [here](https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/collection/WikipediaCollection.java#L20).

**Comment by rosequ** [comment]
Closing this issue since the indexer bindings for Wikipedia already exists.
