### ISSUE TITLE
Naming for index and search classes

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#2066]
We currently have three sets of indexing/search entry points:
1. "normal" inverted indexing and search: `io.anserini.index.IndexCollection`, `io.anserini.search.SearchCollection`
2. indexing and searching dense vectors using HNSW.
3. indexing and searching dense vectors using inverted indexes, with LSH or FW analyzers, currently in the `io.anserini.ann` package.

We need a consistent naming scheme... How about:

For 1, keep as before:
+ `io.anserini.index.IndexCollection`
+ `io.anserini.search.SearchCollection`

For 2:
+ `io.anserini.index.IndexHnswDenseVectors`
+ `io.anserini.search.SearchHnswDenseVectors`

For 3:
+ `io.anserini.index.IndexInvertedDenseVectors`
+ `io.anserini.search.SearchInvertedDenseVectors`

**Comment by tteofili** [comment]
the proposal looks good to me
