### ISSUE TITLE
Tweet Indexing and Searching may not work

### ISSUE THREAD

**Issue by Peilin-Yang** [castorini/Anserini#219]
Some previous PRs must have broken the tweets related indexing and/or searching. 
Currently, indexing seems to work but searching does not return any documents.
For reference, the current sha is c949669984ffdce5075c669af1b788b1ad7f9185

**Comment by Peilin-Yang** [comment]
I am currently working on https://github.com/castorini/Anserini/pull/215 and this might solve the problem (the PR is not specifically for fixing this issue though)

**Comment by lintool** [comment]
Fixed as part of #215, which has been merged into master.
