### ISSUE TITLE
Upgrade to Lucene 9.8.0

### ISSUE THREAD

**Issue by jpountz** [castorini/anserini#2213]
Lucene 9.8.0 was released a few days ago, here is the [changelog](https://lucene.apache.org/core/9_8_0/changes/Changes.html). You may be especially interested in:
 - Better evaluation efficiency for disjunctive queries, especially the more complex ones that have many and/or high-frequency terms, e.g. disjunctive queries generated by learned sparse retrieval models.
 - [Integration of vector search with block joins](https://lucene.apache.org/core/9_8_0/join/org/apache/lucene/search/join/DiversifyingChildrenFloatKnnVectorQuery.html), enabling indexing passages as child documents while vector searches still return parent documents as hits. (NOTE: you will need to add a dependency on the `lucene-join` module to take advantage of this feature)
 - [Support for recursive graph bisection](https://lucene.apache.org/core/9_8_0/misc/org/apache/lucene/misc/index/BPIndexReorderer.html) (NOTE: you will need to add a dependency on the `lucene-misc` module to use this feature)

**Comment by tteofili** [comment]
Thanks @jpountz ! I am looking into it right now, I was already working on the 9.7.0 upgrade, I will close that PR and open a new one for this.

**Comment by jpountz** [comment]
Cool!
