### ISSUE TITLE
Incorporate jtreceval directly into our repo

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#2247]
https://github.com/terrierteam/jtreceval

For example: https://github.com/castorini/anserini/blob/master/docs/regressions/regressions-msmarco-passage.md

We currently have:

```
tools/eval/trec_eval.9.0.4/trec_eval -c -m map tools/topics-and-qrels/qrels.msmarco-passage.dev-subset.txt runs/run.msmarco-passage.bm25-default.topics.msmarco-passage.dev-subset.txt
```

After integration, we should be able to execute:

```
target/appassembler/bin/trec_eval -c -m map tools/topics-and-qrels/qrels.msmarco-passage.dev-subset.txt runs/run.msmarco-passage.bm25-default.topics.msmarco-passage.dev-subset.txt
```

And with the fatjar, we can do:

```
java -cp anserini-0.22.2-SNAPSHOT-fatjar.jar trec_eval ...
```

**Comment by Melissa1412** [comment]
I will pick it up.

**Comment by lintool** [comment]
@jasper-xian will work on this.

**Comment by lintool** [comment]
Initial integration in #2324 merged - we need additional refinements, so I'm leaving open for now.

**Comment by lintool** [comment]
Next improvement is described in #2391 - closing this issue.
