### ISSUE TITLE
RM3 breaks when queries contain special characters

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#225]
RM3 breaks when feedback terms have special characters in it such as `*` and `/`, which is interpreted by Lucene's query parser as a special command.

Example is Robust04 collection.

**Comment by lintool** [comment]
According to https://lucene.apache.org/core/6_3_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html

Lucene supports escaping special characters that are part of the query syntax. The current list special characters are

> `+ - && || ! ( ) { } [ ] ^ " ~ * ? : \ /`

To escape these character use the \ before the character. For example to search for (1+1):2 use the query:

> `\(1\+1\)\:2`

**Comment by lintool** [comment]
I dug more deeply in this: the culprit seems to be
https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/search/SearchCollection.java#L249

When we specify RM3, a different code path is taken that uses the query parser, which then chokes on

> `<title> Literary/Journalistic Plagiarism `

https://github.com/castorini/Anserini/blob/master/src/main/resources/topics-and-qrels/topics.robust04.301-450.601-700.txt#L509

So, bug has nothing to do with feedback terms per se...

It's unclear to me why we need to do this.... any ideas @Peilin-Yang ?

**Comment by Peilin-Yang** [comment]
I think I can take a look.

**Comment by lintool** [comment]
Fixed as part of 7edffbac7cde9859b8537a3fb1c8cfd8332628a6
