### ISSUE TITLE
Upgrade to Lucene 9.9

### ISSUE THREAD

**Issue by jpountz** [castorini/anserini#2288]
Lucene 9.9 was just released, let's upgrade Anserini? https://lucene.apache.org/core/corenews.html#apache-lucenetm-990-available

**Comment by jpountz** [comment]
> But let's queue up after that?

Sure, no hurry.

> are there are new codecs introduce that we gotta upgrade?

Indeed, you'll need to replace `Lucene95Codec` with `Lucene99Codec` and `Lucene95HnswVectorsFormat` with `Lucene99HnswVectorsFormat` when you upgrade. There are new options as well, e.g. you could use `Lucene99HnswScalarQuantizedVectorsFormat` to enable int8 scalar quantization.

**Comment by lintool** [comment]
> int8

Nice. Is there int16 or float16 as well as intermediate step?

When we're ready for that, can you and @tteofili work on that together?

**Comment by jpountz** [comment]
> Nice. Is there int16 or float16 as well as intermediate step?

Not at this point., we're missing native support for float16 in the JVM.

**Comment by tteofili** [comment]
sure I can work with @jpountz on the upgrade (and perhaps on config options for enabling quantization in HNSW in Anserini)

**Comment by lintool** [comment]
> > Nice. Is there int16 or float16 as well as intermediate step?
> 
> Not at this point., we're missing native support for float16 in the JVM.

And do you have numbers of speed/effectiveness tradeoffs vs. full float32?

If not, I guess we should rerun https://arxiv.org/abs/2308.14963 ?

**Comment by jpountz** [comment]
Mileage varies, the main benefit is that you only need one byte per dimension to fit in RAM to get decent performance, vs. 4 bytes per RAM without scalar quantization. So this allows addressing more data with the same amount of RAM.

It turns out that we accidentally turned on quantization on Lucene's nightly benchmarks between Nov 13th and yesterday, there was a noticeable ~30% speedup, even though all vectors already fit in memory at 4 bytes per dimension. http://people.apache.org/~mikemccand/lucenebench/VectorSearch.html

@benwtrent might have more info than I do.

**Comment by jpountz** [comment]
For reference, there have been lots of performance improvements in 9.8 and 9.9 for sparse retrieval too, see e.g. http://people.apache.org/~mikemccand/lucenebench/OrHighHigh.html over recent months. One optimization in particular, https://github.com/apache/lucene/pull/12444 (annotation FK on the nigthly charts, and a [blog](https://www.elastic.co/blog/speedups-top-k-queries-high-frequency-terms) that describes the optimization) should help significantly with cases that are hard for dynamic pruning, such as learned sparse representations. So I would expect *much* better numbers for Lucene if you were to run benchmarks from https://arxiv.org/abs/2110.11540 again.

**Comment by jpountz** [comment]
> And do you have numbers of speed/effectiveness tradeoffs vs. full float32?

The PR that did the change has a few more numbers about speed and effectiveness: https://github.com/apache/lucene/pull/12582#issuecomment-1750806182

**Comment by lintool** [comment]
re: HNSW - yup, I suppose faster is a given... my question is more about how much you give up in terms of effectiveness...

**Comment by lintool** [comment]
> > And do you have numbers of speed/effectiveness tradeoffs vs. full float32?
> 
> The PR that did the change has a few more numbers about speed and effectiveness: [apache/lucene#12582 (comment)](https://github.com/apache/lucene/pull/12582#issuecomment-1750806182)

Thanks, this is good info.

But as I always say... you need a _real_ search task like MS MARCO, BEIR, etc.

**Comment by benwtrent** [comment]
The JVM just doesn't support f16. Reading from disk, doing fast vector operations, etc., its just bad. Even in JDK21. 

There have been steps to fix this (finally adding an intrinsic for de/encoding f16), but its not there yet.

We cannot add f16 until there is something in Panama Vector that handles it.

**Comment by lintool** [comment]
Upgrade completed #2302
