### ISSUE TITLE
Open discussion thread: interface between Castor and Anserini

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#239]
What's the interface between Castor and Anserini? This will dictate the shape of the [pyjnius](https://github.com/kivy/pyjnius) we will build.

As a starting proposal: Anserini does document retrieval and that's it. It ranks documents given a query and hands over the text of the document as a text string. Everything else is done on the Python end. This includes sentence splitting, PTB tokenization, looking up word vectors, etc.

Thoughts?

**Comment by Victor0118** [comment]
I agree with the proposal. I have tried Pyjnius and it is really friendly and easy to use. There might be some issues with the special character encoding but at least currently I can handle all issues I got.

**Comment by tuzhucheng** [comment]
Hi @mengf821, do you have any suggestions?

**Comment by lintool** [comment]
@Victor0118 Have you already gotten Pyjnius to work with Anserini? Can you describe exactly what you did, e.g., code snippets?

**Comment by Victor0118** [comment]
This code snippet searches the index by docID and returns the doc.
If you run this in the TUNA with python2, you can a document that some special characters become Mojibake.
If you run it with python3, you will get an exception and nothing is returned.
```
#import sys
#print(sys.getdefaultencoding())

import jnius_config
jnius_config.set_classpath("/home/w85yang/Anserini/target/anserini-0.0.1-SNAPSHOT.jar")

from jnius import autoclass
JString = autoclass('java.lang.String')

index_test = autoclass('io.anserini.index.IndexUtils')
indexes = index_test(JString('/home/w85yang/Anserini/lucene-index-all.car18'))

print(indexes.getTransformedDocument(JString('7250e1b901bb59853deb38a452f9009999e790ae')))

#print(indexes.getTransformedDocument(JString('77ef93823011e891e572ca9d34a6e251f53c052a')))
```

**Comment by Peilin-Yang** [comment]
I think this is the right way to go. Python libs dominate the DL field and we probably shouldn't use any Java libs for this matter.
FWIW, https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java has pretty much what you want - dump the raw document, dump the docVector, etc. 

For the interface, it can be done by adding a wrapper on top of https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java or if this is a very demanding feature request a server/client might be even better.

**Comment by lintool** [comment]
This suggests killing the word embedding stuff: https://github.com/castorini/Anserini/tree/master/src/main/java/io/anserini/embeddings

Any objections? @rosequ

**Comment by lintool** [comment]
Digging a bit more, I think this also means killing everything in `io.anserini.qa` - these classes try to break docs into sentences and then score using either idf or WMD. For consistency and comparison to Python models, this should also be performed on the Python end?

**Comment by Peilin-Yang** [comment]
https://github.com/castorini/Anserini/tree/master/src/main/js 
Is this also related? Seems to be the frontend of a DL model server?

**Comment by lintool** [comment]
@Peilin-Yang that's code by @tuzhucheng I've created #243 for him to cleanup.
That's one of his TODO items this summer. I'll let him drive that.

**Comment by rosequ** [comment]
@lintool sorry for the delay in response. I don't have objections on cleaning up the code. Replacing with Python code makes more sense (under utils/ in castor.ai, maybe). There's already an implementation of PyJnius available on castor.ai that @MeowFei and I worked on: https://github.com/castorini/Castor/tree/master/anserini_dependency

**Comment by lintool** [comment]
Okay, I think we've reached consensus on this. Closing.
