### ISSUE TITLE
Upgrade JDK?

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#2394]
We're still on JDK11.

Should we jump all the way to JDK 17 or JDK 21? These are the LTS choices:
https://www.oracle.com/ca-en/java/technologies/java-se-support-roadmap.html

**Comment by lintool** [comment]
My plan is to bump up to JDK 21. This will be my next big project.

**Comment by lintool** [comment]
See #2410

**Comment by tteofili** [comment]
+1, we would also get some benefits on the Lucene side (e.g., vector comparison speedups via Panama Vector API).
perhaps this might require some version bump?

**Comment by lintool** [comment]
Done!
