### ISSUE TITLE
End-to-End Integration Testing

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#245]
We should build some end-to-end integration testing so that everything that I've been doing manually in verifying the collections can be automated. The process should perform:

+ indexing collection from scratch
+ performing retrieval runs
+ computing evaluation metrics
+ comparing results against known values triggering errors if metrics change beyond some tolerance

A few ideas of how this could be implemented - 

1. In Java as a series of command line programs
2. In Java as a separate series of JUnit integration tests
3. In Python as a series of Python scripts

There are advantages and disadvantages of each. (2) Would allow us to hook into existing JUnit infrastructure and reporting tools, but downside is that multi-threaded JUnit test-cases can get tricky. (3) Would be lightweight and easy to write, but adds dependency on Python.

@Peilin-Yang Thoughts?

**Comment by Peilin-Yang** [comment]
Depending on the potential customers, either ourselves or other people, I think bash/docker for more general users and Java/Python for us. 
JUnit should be of small scale (https://github.com/castorini/Anserini/tree/master/src/test/java/io/anserini/end2end for example). 
Let's say a regression test on CW12 fails. The problem might be from indexing, from topic reader, from searching or reranking, from evaluation. Re-run the test will re-run the whole pipeline...which may not be that flexible. And honestly it is unusual to use JUnit for integration test. Actually this is not the `integration test` IMO - it is rather a `production pipeline`...

**Comment by lintool** [comment]
I think the customer is us for now - to basically automate what I'm doing manually right now. We know the environment (e.g., `tuna`), so I think Docker is a bit of an overkill...

**Comment by lintool** [comment]
See Python example in PR #248

**Comment by lintool** [comment]
Lots more regression test scripts added as part of commit 372cb5b06a6984126a9a97233a8ad735a3248438 in PR #251 

This seems to be working reasonably now. Closing.
