### ISSUE TITLE
Missing appassembler-maven-plugin:2.1.0:assemble

### ISSUE THREAD

**Issue by Nebu0528** [castorini/anserini#2456]
I pulled the latest code today and it is missing this plugin below for building anserini:

![image](https://github.com/castorini/anserini/assets/85001440/69cf3057-428e-4f8d-adc0-7147c0a8d6e9)

In the pom I don't see it, I was wondering if anyone could recreate this step and see if they encounter the same issue.

**Comment by lintool** [comment]
Are you sure you have the latest code? This plug-in was removed in #2444

**Comment by Nebu0528** [comment]
I pulled from master before I ran the command, I can do a fresh clone and let you know.

**Comment by Nebu0528** [comment]
Sorry for the delay; 

Did a fresh clone

![image](https://github.com/castorini/anserini/assets/85001440/aaef1f14-0d5e-42ab-838b-8ee46e430653)
Same issue persists, I'll be trying to add the plugin and see if it works, please let me know if you or someone else is getting the same issue.

**Comment by lintool** [comment]
<img width="908" alt="Screenshot 2024-04-14 at 4 29 37 PM" src="https://github.com/castorini/anserini/assets/313837/1099ec7d-157e-4fdf-b27e-139791ec3c1e">

See above. Your fork is many commits behind master...

**Comment by Nebu0528** [comment]
![image](https://github.com/castorini/anserini/assets/85001440/c75f6699-bb14-4a31-9f9a-93c79533afda)

Issue is persisting from cloning directly from anserini and cloning from my fork, would it be fine if I can revert to a commit where they were able to reproduce the results for BM25? 

My friend @Gelardinio also faces the same issue

**Comment by ToluClassics** [comment]
Im experiencing the same issue
