### ISSUE TITLE
Index of Microblog13 collection has duplicated documents

### ISSUE THREAD

**Issue by Peilin-Yang** [castorini/Anserini#258]
At least there are two documents that are consistent across multiple indexing tries: 301142378562068480, 313796170101174272.
Since the internal docids in Anserini are non-deterministic these duplicated doucments are hard to find. What I did is to log the internal docIds when doing the retrieval and look back-n-forth between logs and the output ranking list. 
Then we can use `target/appassembler/bin/IndexUtils -index lucene-index.Tweets2013.pos+docvectors.keepUrls.stemming -convertLuceneDocidToDocid xxxxx` and `target/appassembler/bin/IndexUtils -index lucene-index.Tweets2013.pos+docvectors.keepUrls.stemming -convertLuceneDocidToDocid yyyyy` to verify that there external docId are both 301142378562068480 or 313796170101174272.

For now I've no idea why this could happen but it seems to be an indexing issue.

**Comment by lintool** [comment]
This is because a tweet might be delivered multiple times in the streaming API, e.g., due to a network hiccup.

**Comment by Peilin-Yang** [comment]
I thought docid is the unique identifier of the indexed document and thus be unique.... seems to be not the case

**Comment by lintool** [comment]
No, Lucene treats it just as any other field - it has special semantics to us, but not for Lucene. Only the internal docid is unique.

**Comment by lintool** [comment]
Does this cause a specific issue? To really address this, we'd need to keep a global hash set of all ids encountered - however, since indexing is multi-threaded, this will need to be sync'ed and thus slow indexing by a lot...

**Comment by Peilin-Yang** [comment]
> Does this cause a specific issue? 

Yes, when I did the reranking the duplicated documents are in the ranking list. And this fails `trec_eval`.

I think I already know how to solve it - `IndexWriter.updateDocument(new Term("id", id), doc)`.  And testing on MB13 seems working. But this should be an optional parameter for `IndexCollection` as it slows down the indexing (the updateDocument basically delete the existing doc with the same id from the index and add the new one).
I will push the PR soon.

**Comment by lintool** [comment]
Yes, this should be a separate code path and we should measure the performance effects...

**Comment by Peilin-Yang** [comment]
fixed per #263
