### ISSUE TITLE
End-to-end regression testing, take two

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#279]
We have somewhat janky Python regression tests in place for most collections, per #245 

Open-thread to figure out what we do next...

@Peilin-Yang Suggests:

> How about this: We could have a more real, small yet publicly available corpus put into the repo. Ideally, this corpus and its topics behaves differently for different tie breaking strategies. We can use the end2end test framework to make the corpus part of it and thus be part of `mvn test`. Then we build python modules for manual but more comprehensive regression tests. The settings and the effectiveness numbers are stored in yaml files. The numbers in the yaml files will be the only source of truth for reference. `docs./experiment-*.md` could be doc templates and another script will populate the effectiveness number from the yaml files.

**Comment by lintool** [comment]
@Peilin-Yang Reactions:

1. I'm fine with CACM, but we should store it in another repo, `Anserini-data` or something like that. I like to keep the code repo small and compact, and the CACM collection has unclear copyright status.

2. Yes, keeping source of truth effectiveness in yaml is fine, but then we need some type of preprocessor to generate documentation... and this needs to be hooked into either the build process or the commit process, right? Any concrete ideas how you want to set this up?

**Comment by lintool** [comment]
Concrete PR is at #286

**Comment by Peilin-Yang** [comment]
merged in #355
