### ISSUE TITLE
Upgrade to Lucene 7

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#291]
Current latest version of Lucene is 7.4 - now that we have regressions in place, shall we upgrade?

@Peilin-Yang do you think we're ready?

**Comment by Peilin-Yang** [comment]
How about we first make our 1st release using Lucene 6.3 for reference?
I've tested Lucene 7.3. The results of BM25 have definitely changed.

**Comment by lintool** [comment]
@Peilin-Yang okay, sg

**Comment by lintool** [comment]
Completed in #514. Closing.
