### ISSUE TITLE
Fat jar No Longer Building for 0.1.1

### ISSUE THREAD

**Issue by tuzhucheng** [castorini/Anserini#300]
When I do `mvn clean package shade:shade`, I do not get a file named `anserini-0.1.1-SNAPSHOT-fatjar.jar` required for pyjnius in the `target` anymore, just have these files:

```
-rw-r--r--   1 michael  staff    640237  5 Jul 16:31 anserini-0.1.1-SNAPSHOT-javadoc.jar
-rw-r--r--   1 michael  staff  72324358  5 Jul 16:31 anserini-0.1.1-SNAPSHOT.jar
drwxr-xr-x  17 michael  staff       544  5 Jul 16:31 apidocs
drwxr-xr-x   4 michael  staff       128  5 Jul 16:31 appassembler
drwxr-xr-x   6 michael  staff       192  5 Jul 16:30 classes
drwxr-xr-x   3 michael  staff        96  5 Jul 16:30 generated-sources
drwxr-xr-x   3 michael  staff        96  5 Jul 16:30 generated-test-sources
drwxr-xr-x   4 michael  staff       128  5 Jul 16:31 javadoc-bundle-options
drwxr-xr-x   3 michael  staff        96  5 Jul 16:31 maven-archiver
drwxr-xr-x   3 michael  staff        96  5 Jul 16:30 maven-status
-rw-r--r--   1 michael  staff   7757138  5 Jul 16:31 original-anserini-0.1.1-SNAPSHOT.jar
drwxr-xr-x  68 michael  staff      2176  5 Jul 16:31 surefire-reports
drwxr-xr-x   8 michael  staff       256  5 Jul 16:30 test-classes
```

**Comment by lintool** [comment]
Maven says:

```
[INFO] Replacing /Users/jimmylin/workspace/Anserini/target/anserini-0.1.1-SNAPSHOT.jar with /Users/jimmylin/workspace/Anserini/target/anserini-0.1.1-SNAPSHOT-shaded.jar
```

Somewhere along the way, the Maven plugin behavior changed... so `anserini-0.1.1-SNAPSHOT.jar` is the fat jar, and the non fatjar is `original-anserini-0.1.1-SNAPSHOT.jar`.

I'll revert back to original behavior when I get a chance.

**Comment by Peilin-Yang** [comment]
Is that possible to add integration test for this?

**Comment by tuzhucheng** [comment]
Interesting, pyjnius reports class not found for SimpleSearcher if I use `anserini-0.1.1-SNAPSHOT.jar` but it is not an issue if I use the fat jar from before.

**Comment by lintool** [comment]
@tuzhucheng At least for me, the class seems to be there?

```
$ jar tf target/anserini-0.1.1-SNAPSHOT.jar | grep SimpleSearcher
io/anserini/search/SimpleSearcher$Result.class
io/anserini/search/SimpleSearcher.class
```
@Peilin-Yang Is it possible to do integration across Python and Java? And also, pyjnius needs to be installed.

**Comment by tuzhucheng** [comment]
Yep, when I use `jar tf` the class is there, but not when I use pyjnius with it.

**Comment by tuzhucheng** [comment]
Screenshot for reference

![image](https://user-images.githubusercontent.com/2687996/42352226-12ccdf54-8087-11e8-968f-383bf237ebfb.png)

**Comment by lintool** [comment]
Okay, I've narrowed it down to https://github.com/castorini/Anserini/commit/2c76f3c51ed57aaac24589e6b5ec19ad9c528e9c as the culprit.

It seems my messing with `appassembler-maven-plugin` mucked up the process of building the fat jar...

**Comment by lintool** [comment]
#302 should fix this issue.

**Comment by lintool** [comment]
Fixed.
