### ISSUE TITLE
Reorganization of collections: use inner classes to associate related objects

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#313]
Currently, we have `FooCollection` and `FooDocument`, like `ClueWeb09Collection` and `ClueWeb09Document`. Since they are a tightly-bound semantic unit, one could reorganize as inner classes. So:

+ `ClueWeb09` would be the name of the collection (implicitly)
+ `ClueWeb09.Document` would be the name of the document from that class.

Same with all the other collections. Then we can reorganize all these bundles in `io.anserini.collection.lib`; the interface definitions go in `io.anserini.collection`.

This would also make Javadocs a lot cleaner.

The only major downside I can see is that our source code files will be much longer... but given that one navigates with an IDE these days, it's not that big a deal...?

Thoughts @Peilin-Yang?

**Comment by Peilin-Yang** [comment]
I think it is reasonable to merge `Collection` and `Document`.
What do you think about another component `Iterator`? Basically, a `Collection` consists of `Iterator` and `Document`. The `Iterator` discovers documents (now we only deal with files but we can support streaming data too) and the `Document` parse the document into a structure or throw an error. 

Another thing is that we should unify or at least keep error handling consistent. Now when indexing a collection the error could be from `Document`; it could also be from `Collection`; it can yet be from `Generator`.... and I think we definitely need to fix this.

**Comment by lintool** [comment]
@borislin Can you organize the twitter and WashingtonPost collections in the same way? I.e., nest as inner classes.

If I understand correctly, `Status` and `WashingtonPost` in `io.anserini.document` are helpers for Jackson parsing? If so, can we given them a name that makes these clear?

Put Washington Post and Twitter on separate PRs please.

**Comment by borislin** [comment]
@lintool Jackson uses class definitions of `Status` and `WashingtonPost` to parse (deserialize & serialize) a tweet JSON and a WashingtonPost JSON data respectively. How about naming them `TweetObject` and `WashingtonPostObject`?

**Comment by lintool** [comment]
@borislin Three more collections to go and we're done: Wikipedia, Car, and Json. Separate PR for each?

@tuzhucheng should review Wikipedia
@Peilin-Yang should review Json
@Victor0118 should review Car

**Comment by lintool** [comment]
Yay, we're all done. Thanks @borislin !
