### ISSUE TITLE
Clean up semantics of index counters

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#317]
Currently, the semantics of index counters are a mess. We use `null` to signal end of reading from a `FileSegment`, but `null` can also mean error processing a record. We log counters as multiple points in the code path, and so the counter values are partially overlapping...

Let's clean up.

**Comment by lintool** [comment]
As noted by @borislin, this is related to #254.

**Comment by borislin** [comment]
@lintool @Peilin-Yang 

I propose the following `Counters` class (`unindexed` removed):

```
public final class Counters {
    /**
     * Counter for successfully indexed documents.
     */
    public AtomicLong indexed = new AtomicLong();

    /**
     * Counter for empty documents that are not indexed. Empty documents are not necessary errors;
     * it could be the case, for example, that a document is comprised solely of stopwords.
     */
    public AtomicLong empty = new AtomicLong();

    /**
     * Counter for unindexable documents. These are cases where {@link SourceDocument#indexable()}
     * returns false.
     */
    public AtomicLong unindexable = new AtomicLong();

    /**
     * Counter for skipped documents. These are cases documents are skipped as part of normal
     * processing logic, e.g., using a whitelist, not indexing retweets or deleted tweets.
     */
    public AtomicLong skipped = new AtomicLong();

    /**
     * Counter for unexpected errors.
     */
    public AtomicLong errors = new AtomicLong();
  }
```

num of unindexed docs = num of `empty` + num of `unindexable` + num of `errors` + num of `skipped`
So we don't need the `unindexed` counter.

Sg?

Btw, I've noticed that we have two places that have deleted tweets. One is the `-tweet.deletedIdsFile` option passed into `IndexCollection` and the other one is when the `delete` field is detected in the JSON string when parsing each tweet document. I believe we may have counter overlapping issue here, right?

**Comment by lintool** [comment]
@borislin overall, sg.

I'll let @Peilin-Yang clarify the semantics of Twitter deletes. 

> the other one is when the delete field is detected in the JSON string when parsing each tweet document.

Do you mean that the JSON of the tweet marks it as deleted? Can you show an example?

**Comment by borislin** [comment]
@lintool Yes, I mean the JSON of the tweet marks it as deleted.

Examples:

https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/collection/TweetCollection.java#L118

https://github.com/castorini/Anserini/blob/master/src/test/resources/sample_docs/tweets/tweets1#L3

**Comment by borislin** [comment]
@lintool 

In order to get this done, I think the next step will be refactoring `IndexCollection` to make use of `MapCollections`, right?

**Comment by lintool** [comment]
@borislin Perhaps in version 5 :)

IndexCollections is such a complex beast that I don't really want to touch it, and I don't think `MapCollections` is rich enough to address... so I think we should keep IndexCollections as a stand-alone class and try to fix the counting semantics the best we can...

**Comment by lintool** [comment]
Closing!
