### ISSUE TITLE
Write utility to dump out document vectors

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#318]
To replicate Gord's CORE17 runs, we need to dump out document vectors for the qrels (for simplicity, he weights by tf.idf). This should go into `IndexUtils`.

**Comment by Kytabyte** [comment]
Anserini changes soooooo fast...

My proposal is to use the dump raw docs idea, replicating `-dumpRawDoc`, `-dumpRawDocs`, `-dumpRawDocsWithDocid` args with `-dumpTfidf`, `-dumpTfidfs`, and `dumpTfidfsWithDocid` with the same functionality for each. Sounds good?

**Comment by lintool** [comment]
How about `-dumpDocVectors` and `-dumpDocVectors.weights` (`tf.idf` is the only option supported right now, but we could add `bm25` later)?

I don't think we need `WithDocid` because it wouldn't make sense to dump the doc vectors without docids, right?

**Comment by Kytabyte** [comment]
> How about -dumpDocVectors and -dumpDocVectors.weights (tf.idf is the only option supported right now, but we could add bm25 later)?

That's good.

> I don't think we need WithDocid because it wouldn't make sense to dump the doc vectors without docids, right?

Yes, but actually I'm not quite sure the use case to add a `WithDocid` option in dumping raw docs, since in `dumpRawDocuments` each doc will be written into a single tar file named as `docid`. Users can get the docid by name in anyways...

So basically I agree that we can make it only one option, just with tag or without it

**Comment by Peilin-Yang** [comment]
> Yes, but actually I'm not quite sure the use case to add a WithDocid option in dumping raw docs, since in dumpRawDocuments each doc will be written into a single tar file named as docid. Users can get the docid by name anyway...

@Kytabyte Anserini by default does store `<DOCNO>docid</DOCNO>` in the front of the raw documents (let's assume it is a TREC document). By adding `<DOCNO>docid</DOCNO>` we are able to directly index the dumped documents using Anserini or Indri. When the dumped archive is huge this is very handy.

**Comment by Kytabyte** [comment]
@Peilin-Yang Thank you for the explanation!

What about the `-dumpRawDoc` (dump one doc given docid) and `-dumpRawDocs` (dump all docs given a file of docid list) options? Do we need both options for dump doc vectors as well?

**Comment by lintool** [comment]
Sure, have both options - dump one doc vector and dump entire file of doc vectors

**Comment by Kytabyte** [comment]
Just realized that `-printDocvector` option is to print the document vector of an input docid; however for the same functionality for raw doc, the option is called `-dumpRawDoc`. Do we need to change one of them to keep the verb consistent?

**Comment by lintool** [comment]
Sure, feel free to refactor.

**Comment by lintool** [comment]
Completed. PR #326
