### ISSUE TITLE
Refactor NYT collection to directly index tgz files

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#321]
Currently, we can only index the NYT collection after decompressing it first. We should be able to use TarArchiveInputStream in Apache Commons Compress to index the tgz files directly.

For example, something like: https://stackoverflow.com/questions/25749550/read-tar-gz-in-java-with-commons-compression

**Comment by Kytabyte** [comment]
Do we make it only read from the tgz files, or we should keep both options?

**Comment by lintool** [comment]
Fixed with #340
