### ISSUE TITLE
"Mapper" over document collection

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#353]
As a way to demonstrate #254 (SourceDocument refactoring to get rid of readNextRecord), we could build a generic mapper framework -  an interface that lets us map over an entire collection in parallel. Design would be similar to how the indexer currently works - parallelism at the level of file segments, using a work pool.

The simplest implement would be a counter util to count the number of documents in a collection - this would help with issue #317 (Clean up semantics of index counters).

**Comment by lintool** [comment]
With #352 and #254 done, @borislin can turn attention to this now?

Once this has been implemented, we can sanity check against counts here for ClueWeb12:
https://lemurproject.org/clueweb12/specs.php

And similar ground-truth counts for other collections.

The reason I want this broken out separately is that we can isolate reading records from other issues that crop up during indexing (e.g., parse errors, empty docs, etc.).

**Comment by borislin** [comment]
@lintool I think we still need to parse each document, right? For instance, for each tweet document, we need to update `counter.errors` for tweet documents that contain the `delete` field.

**Comment by lintool** [comment]
Well, deletes aren't errors though. By error I mean something like invalid JSON? Yes, there are going to be invalid JSON... but for ClueWeb{09,12}, we should be able to match exactly the record count in the websites above.

**Comment by borislin** [comment]
#370 added this generic mapper framework
