### ISSUE TITLE
Contribute Python newswire paragraph segmentation scripts

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#358]
Hi @Kytabyte can you contribute your Python newswire segmentation scripts directly to Anserini? Send a PR, let's get it CR'ed.

Related to #312

**Comment by Kytabyte** [comment]
Sure. Which folder should this code go in?

**Comment by Kytabyte** [comment]
sg!

**Comment by lintool** [comment]
Addressed by PR #430
