### ISSUE TITLE
Axiomatic Analysis for Improving the Log-Logistic Feedback Model

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#365]
Should we implement this in Anserini?

Axiomatic Analysis for Improving the Log-Logistic Feedback Model
https://dl.acm.org/citation.cfm?id=2914768

**Comment by aalbahem** [comment]
@lintool I am implementing a couple of relevance models for my research, so I would like to implement this.

**Comment by aalbahem** [comment]
@lintool For my research, I have implemented the basic LL model. I also have implemented [MixtureMode](https://dl.acm.org/citation.cfm?id=502654), [Distill model](https://dl.acm.org/citation.cfm?id=2914695), and the Rocchio method. I plan to implement the axiomatic-based models of LL later. 

I am not sure whether we should create separate issues for these methods that I have implemented, then pull request these issues or put them all into a single issue. 

As we are adding more relevance feedback methods, I think it is better to have regression tests for all relevance models, which we update regularly.  

Let me know what you think?

**Comment by lintool** [comment]
Can you send a PR for LL first? How effective is it? The effectiveness values for LL reported in the paper are lower than what we have for baseline RM3.

**Comment by aalbahem** [comment]
I would PR that soon with results. But, the results is below what we have for bm25+RM3.

Apart from that, I did build my code on top of the #626 code, so should I wait until that get merged before the new PR.

**Comment by lintool** [comment]
@aalbahem I just commented on #626 - lmk what you think...

**Comment by lintool** [comment]
There doesn't seem to be interest in this. Closing.
