### ISSUE TITLE
Separate FileSegment interface and AbstractFileSegment abstract class?

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#366]
Okay, this might be a bit pedantic, but I think `FileSegment` should be an interface with `AbstractFileSegment` as the base class implementing that interface.

From a hygiene point of view, separating interfaces from impl is "a good thing".

From a practical perspective, our docs say something like:
> A static collection of documents, comprised of one or more {@link AbstractFileSegment}s.

Which is technically not true and sounds a bit odd. But saying *subclasses* or *concrete implementations* of `AbstractFileSegment` everywhere sounds too awkward. 

@borislin @Peilin-Yang thoughts?

I can work on it.

**Comment by borislin** [comment]
I'm a bit confused.

Right now, we have our `FileSegment` in each collection, which extends to `AbstractFileSegment` as the base class.

Do you mean we should create an interface and let our `FileSegment` in each collection to implement that interface?

**Comment by lintool** [comment]
No, just that we should have `interface FileSegment` and `abstract class AbstractFileSegment implements FileSegment`.

**Comment by borislin** [comment]
But right now, we already have `abstract class AbstractFileSegment<T extends SourceDocument> implements Iterator<T>, Closeable`. If we create another interface `FileSegment`, what does this interface contain?

**Comment by lintool** [comment]
So, it would be:

> interface FileSegment extends Iterator

and

> abstract class AbstractFileSegment implements FileSegment, Closeable

Something like that?

**Comment by borislin** [comment]
Sure, I'm okay with this.

**Comment by lintool** [comment]
Fixed in #366 - see CR for additional discussion on class names we settled on.
