### ISSUE TITLE
Confusion HtmlCollection: does it accept tgz?

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#368]
The javadoc says:
https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/collection/HtmlCollection.java#L37

> The file name (excluding the extension) will be the docid and the stripped contents will be the contents.

However, the impl accepts `tgz` files. So what's the behavior when indexing `tgz` files? What's used as the docid? Some clarification seems to be needed?

**Comment by Peilin-Yang** [comment]
The docid will still be the filename (the files in the tar archive).

**Comment by lintool** [comment]
This is lower priority, but we should add a test case... things that aren't tested or part of regressions that we run regularly have a tendency to break...

**Comment by lintool** [comment]
Closed by #873
