### ISSUE TITLE
Clean up semantics for updating counter for deleted tweets

### ISSUE THREAD

**Issue by borislin** [castorini/anserini#373]
Currently, there are two places where we have checked for deleted tweets. One is the [`-tweet.deletedIdsFile`](https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/index/IndexCollection.java#L122) option passed into `IndexCollection` and the other one is when the [`delete`](https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/collection/TweetCollection.java#L118) field is detected in the JSON string when parsing each tweet document in `TweetCollection` using Jackson.

As mentioned by @lintool , since we have to comply with Twitter API usage agreement, we have to use the deleted tweets file. So we will get rid of checking for deleted tweets in JSON parsing in `TweetCollection` and let `TweetGenerator` checks for deleted tweets and update the `counters.skipped` counter, preventing updating the `skipped` counter twice.

@Peilin-Yang Thoughts?

**Comment by lintool** [comment]
Additional clarification - we don't actually index the stream live - the JSON messages are always captured in a file first. So we do another pass to gather up all the JSON delete messages into a file that we pass to `tweet.deletedIdsFile` in the indexing code.

**Comment by lintool** [comment]
As part of working on #916 - rereading this issue - I think this can be closed.
