### ISSUE TITLE
Iterator depending on NoSuchElementException to signal end of iteration

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#381]
Branch contains a test case that exposes bad iterator behavior:
https://github.com/castorini/Anserini/commit/01e8c82c3a297b0939bffef32f52b7ef7588c5a9

The iterator depends on NoSuchElementException to signal end of iteration, which fails when we try to apply a functional programming style.

Fix and add test cases.

**Comment by borislin** [comment]
So the fix will be: `hasNext()` should return `false` instead of throwing `NoSuchElementException`, right?

How about `RuntimeException`? Should we also catch it in `hasNext()` and return `true` so allowing the iterator to load more documents?

**Comment by borislin** [comment]
@lintool Thoughts?

**Comment by lintool** [comment]
Correct, I think those are the desired behaviors.

**Comment by borislin** [comment]
Fixed in #399
