### ISSUE TITLE
Snippet (Fragment) Engine for Anserini

### ISSUE THREAD

**Issue by HTAustin** [castorini/Anserini#391]
Add a snippet engine to allow fragments of documents that match the user’s query to be included with the query response. The same feature is already implemented in SOLR: https://lucene.apache.org/solr/guide/6_6/highlighting.html.

**Comment by r-clancy** [comment]
We've been exploring integrating Anserini and Solr (see https://github.com/castorini/SolrAnserini), so we get highlighting for free with Solr when an index is built using the `-storeTransformedDocs` parameter (see https://github.com/castorini/Anserini/pull/480 for PR adding documentation).

Closing this issue as the Solr integration gets us highlighting.
