### ISSUE TITLE
Anserini tagline: too generic?

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#400]
Currently, the tagline for Anserini says:
```
Anserini: An information retrieval toolkit built on Lucene
```
E.g., this is at the top of the license headers for our documentation.

This seems too generic to me... some better options:

1. A toolkit for information retrieval research built on Lucene
2. A toolkit for reproducible information retrieval research built on Lucene
3. A Lucene-based toolkit for information retrieval research
4. A Lucene-based toolkit for supporting information retrieval research
5. A Lucene-based toolkit for reproducible information retrieval research

Currently, I like the second one the best. Any additional thoughts? Additional suggestions?

**Comment by Peilin-Yang** [comment]
You should make the list as an ordered one....
Vote for number 2

**Comment by borislin** [comment]
+1 for number 2

**Comment by lintool** [comment]
#439 address this. Closing.
