### ISSUE TITLE
Wrong description of parameter options (topic v.s. topics) for experiments on trec collections

### ISSUE THREAD

**Issue by lukuang** [castorini/Anserini#402]
Hi,

I tried to run experiments using the provided commands on [gov2](https://github.com/castorini/Anserini/blob/master/docs/experiments-gov2.md) and [robust04](https://github.com/castorini/Anserini/blob/master/docs/experiments-robust04.md). However, the parameter options of performing retrieval seem to be wrong. Instead of "-topics", the commands listed on the above links use "-topic" instead.

**Comment by Peilin-Yang** [comment]
merged as #405
