### ISSUE TITLE
Adding capability to index multiple fields

### ISSUE THREAD

**Issue by Peilin-Yang** [castorini/anserini#404]
Currently, it is impossible to index fields other than `contents` for most of the collections.
However, such functionality is desirable for LTR, Background linking and other use cases. 

With the help of Lucene's native fielded indexing, it is possible to add this functionality at the Generators.

**Comment by lintool** [comment]
Really old issue... but we've made progress: https://github.com/castorini/pyserini/blob/master/docs/experiments-elastic.md

Closing for now.
