### ISSUE TITLE
Missing topics and qrels for topic 501-550

### ISSUE THREAD

**Issue by lukuang** [castorini/Anserini#416]
I found that in the experiment page of wt10g `experiments-wt10g.md`, topics 501-550 are mentioned. However, the corresponding topics and qrels files are not found in the `src/main/resources/topics-and-qrels`. Moreover, there is no information about these queries (e.g. performances) in the resource file `src/main/resources/regression/wt10g.yaml`.

**Comment by Peilin-Yang** [comment]
Anserini combines the two topic files into one topics.451-550.txt 
This is also true for qrels 
The numbers in `src/main/resources/regression/wt10g.yaml` are also reflected this.

**Comment by lukuang** [comment]
Sorry, should be more careful.....

But a related question: why the topic files in gov2 are not combined?
