### ISSUE TITLE
Write up instructions for Anserini/Solr integration

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#431]
Specific follow-on to #364 

@r-clancy Can you please send a PR with instructions on how to set up and integrate an Anserini index into Solr? Based on our previous discussions, it should be fairly simple, along these lines:

1. `docker start...`
2. copy in Anserini index
3. copy in metadata config file
4. restart Solr
5. navigate to URL

It might be short enough to include directly in a section in `README.md`, or we might start a new file in `docs/` and link to it.

In the future, we might even consider building a regression test around this.

**Comment by r-clancy** [comment]
Sure - I'll write something up and add it to the `docs/` directory.

**Comment by lintool** [comment]
Closing this issue since Solr + Anserini integration has moved to https://github.com/castorini/SolrAnserini
