### ISSUE TITLE
Exploration into Anserini + NN integration via ONNX

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#435]
Soon we'll have a demo of running a NN on the JVM via ONNX:
https://github.com/castorini/ONNX-demo/

Let's do some exploration of Anserini+NN integration to see how the pieces might begin to fit together? A simple demo might be to do a search, and classify sentences from the retrieved documents into positive and negative.

**Comment by EmergentOrder** [comment]
You may want to consider using the [JavaCPP Preset for ONNX](https://github.com/bytedeco/javacpp-presets/tree/master/onnx)

**Comment by lintool** [comment]
Today's FB Horizon announcement features ONNX prominently: https://code.fb.com/ml-applications/horizon/

**Comment by r-clancy** [comment]
@lintool For the integration, would we want to use the JavaCCP Preset mentioned about or use Scala code (following Heli's example) and call that from Java?

**Comment by lintool** [comment]
No idea... try both and compare and contrast?

**Comment by EmergentOrder** [comment]
Some more detail to aid in your decision-making:
 
The [JavaCPP Preset for ONNX](https://github.com/bytedeco/javacpp-presets/tree/master/onnx) contains everything that you get from an implementation generated from ONNX Protobuf definitions, including the ability to load a model. You also get the ability to ["polish"](https://github.com/onnx/onnx/blob/v1.3.0/onnx/utils.py#L14) and convert the version of a model (in this now merged [PR](https://github.com/bytedeco/javacpp-presets/pull/622) ) as well as access to the operator schemas, the ONNX IR, ONNX-ML (Classical Machine Learning extension), ONNXIFI and more.

The JavaCPP Preset offers an API that is as close as possible to the ONNX C++ API in Java. This means it does not include a backend capable of actually running inference on the model.

In contrast, my project [ONNX-Scala](https://github.com/EmergentOrder/onnx-scala) (which uses the JavaCPP Preset under the hood) aims to provide a typeful, idiomatic and purely functional Scala API to ONNX. ONNX-Scala makes full use of (sometimes bleeding-edge) language features where appropriate, while targeting 2 current and 2 in-development versions of Scala for the JVM, as well as Scala Native and Scala.js.

ONNX-Scala provides a clean separation between API, program definition, and backend implementation.

Currently there is no backend available for ONNX-Scala either, but the plan is to have several backend implementations available. The first cut of the first one should be ready in the near future. 
[Lantern](https://github.com/feiwang3311/Lantern) is the top candidate right now, although I have partially-baked MXNet backend that could be revived as well.

I am also working on a JavaCPP Preset for [ngraph](https://github.com/NervanaSystems/ngraph) , which should provide us with an ONNX backend in Java (also a candidate for a backend in ONNX-Scala).

Phew; hope it helps.

**Comment by lintool** [comment]
@EmergentOrder cool, thanks for the detailed rundown!

**Comment by r-clancy** [comment]
@EmergentOrder Thanks for the info!

**Comment by lintool** [comment]
Hey @EmergentOrder I recently checked out your LinkedIn profile - it says you're a freelance developer... if you're interested in doing some work for us, let's chat. If interested, ping me directly on email?

**Comment by lintool** [comment]
No plans in the near future to work on this, closing for now.
