### ISSUE TITLE
Refactor axiom semantic term matching to avoid use of query parser

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#442]
Just like #429 but for axiom semantic term matching - we should be generating queries programatically, not generating a text string and then applying the query parser:

https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/rerank/lib/AxiomReranker.java#L143

**Comment by r-clancy** [comment]
This change has been implemented in #451.

However, the regression tests do not pass (see [error.txt](https://github.com/castorini/Anserini/files/2507800/error.txt)).

The old query (generated by the Lucene parser) and the new query (generated manually using TermQuery and BoostQuery) are identical:

![cw09b](https://user-images.githubusercontent.com/1282383/47387340-1ac47800-d6dd-11e8-87cf-8e7bfba0be76.png)

**Comment by r-clancy** [comment]
@lintool I re-based from master and re-ran the tests, they all look good now. Not sure what gremlins were plaguing me before, but this is ready to be merged.

**Comment by lintool** [comment]
#451 merged. Closing.
