### ISSUE TITLE
Version of Java and Maven for building Anserini

### ISSUE THREAD

**Issue by paopao74cn** [castorini/Anserini#445]
After testing, Java(up to 8) and Maven (up to 3.5.4) will work for building Anserini. Such versions should be mentioned and added into README.md in the section of Build using Maven.

**Comment by paopao74cn** [comment]
Both Java 10 and 11 (just released on 2018-09-25) ran into the same testing error (copied below): 
Tests in error:
 io.anserini.integration.IndexerTest: file handle leaks: [FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-003/_1_Lucene50_0.tim), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-003/_1.tvd), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-001/_1_FST50_0.doc), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-003/_1_FST50_0.doc), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-001/_1.fdt), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-003/_1.nvd), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-001/_1.tvd), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-001/_1.nvd), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-003/_1_Lucene50_0.doc), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-003/_1.fdt), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-001/_1_Lucene50_0.doc), FileChannel(/private/var/folders/qg/zpdv2ll92z5d0yx5c_2fsnhw0000gp/T/io.anserini.integration.IndexerTest_3D2D001ADD1CDB8B-001/tempDir-001/_1_Lucene50_0.tim)]

**Comment by Chriskamphuis** [comment]
At the moment Anserini will not build if you are using openjdk1.8 (on debian) due to a [bug](https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class) in openjdk. 

You can add the following snippet to the pom file for a small workaround:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
  	<artifactId>maven-surefire-plugin</artifactId>
	<version>2.22.1</version>
	<configuration>
		<useSystemClassLoader>false</useSystemClassLoader>
	</configuration>	
</plugin>
```

**Comment by lintool** [comment]
This issue is linked to directly from the README, so no need to keep open. Closing.
