### ISSUE TITLE
Change RM3 default parameters

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#447]
We should change the RM3 default parameters to match Indri. As of v5.13, the defaults in Indri are:

>  int fbDocs = _param.get( "fbDocs" , 10 );
 > int fbTerms = _param.get( "fbTerms" , 10 );
 > double fbOrigWt = _param.get( "fbOrigWeight", 0.5 );
 > double mu = _param.get( "fbMu", 0 );

This is in `src/RMExpander.cpp`.

**Comment by aalbahem** [comment]
Can I work on this?

**Comment by lintool** [comment]
Hi @aalbahem welcome and thanks for offering to contribute. @Peilin-Yang and I need to discuss how to sequence this ticket wrt roadmap - i.e., do we do this before or after the planned migration over to Lucene 7. Issue is that updating params will change all our regression numbers.

Person working on this ticket will also need access to all the collections to update the regression numbers. Do you have access to the collections?

**Comment by aalbahem** [comment]
I am a PhD student at RMIT, so I believe we have many collections indexed in RMIT. But, I believe they are indexed in Indri.  I chose this issue because I wanted to start with a small contribution. 

I can also start helping in the migration to Lucene 7, I used Lucene and Solr a lot, so I definitely can help. That is the reason I wanted to help in the first place.

**Comment by lintool** [comment]
@aalbahem tbh, this issue is more involved than it looks because everything is tied into our regression testing framework so that our results are replicable...

I've made notes on #467 #422 - you might be interested in helping out there? Or drop me an email and let's discuss.

Another thing you might be able to help with is to replicate all our regression runs in the repo - on all the collections - just to make sure we haven't missed anything.

The Lucene7 upgrade is mostly done, on a separate branch... once again, the issue is with sequencing on when to merge in, which I gotta discuss with @Peilin-Yang 

Thanks~

**Comment by lintool** [comment]
Done and merged in #539
