### ISSUE TITLE
Open thread for discussion: integration of word embeddings in Anserini

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#467]
We've been discussing for a while now how to integrate word embeddings into Anserini. A while ago, @rosequ experimented with [deeplearning4j](https://deeplearning4j.org/), at the end of the day, it was much easier to work with word embeddings on the PyTorch end for anything related to DL.

As part of https://github.com/castorini/Anserini/pull/465 @tteofili raised this issue again. So this is an open thread for discussion.

There are several facets to this problem - The first is simply using Lucene indexes as a key-value store to hold world embeddings. Then there's the issue of manipulating the word embeddings, which will require integration with some linear algebra package.

@tteofili do you have thoughts on this?

**Comment by tteofili** [comment]
@lintool I agree on the simplest use case of using Lucene as a kv store to hold embeddings.

I think we should write up how we expect word/document embeddings to be used in the context of Anserini. I see the following use cases:
- word / query expansion (index / search time)
- document embeddings based ranking
- document embeddings based reranking

Regarding 
> it was much easier to work with word embeddings on the PyTorch end for anything related to DL
can you elaborate more on that ?
It sounds to me that either we have a few Anserini specific abstractions for embeddings (and DL in general) and let extensions implement them or have to choose a DL library.

Implementation note: we could index embeddings as Lucene `FloatPoints` if we can reduce their dimensionality up to 8 (e.g. see this [paper](https://lld-workshop.github.io/papers/LLD_2017_paper_34.pdf)) and do a nearest neighbour search for the rank / rerank use case. However we would need a linear algebra library for the PCA / dimensionality reduction bits.

**Comment by tteofili** [comment]
e.g. an Anserini Reranker based on [average word embeddings nearest neighbour](https://gist.github.com/tteofili/ce26241bd086e61a8c26a7544c175298) (using DL4J).

**Comment by lintool** [comment]
How effective is it? :)

**Comment by tteofili** [comment]
it quite depends on the model used, anyway in general better P@10, stable P@30, worse MAP with pretrained word embedding models (e.g. Word2vec on Google News, GloVe on Wikipedia, etc.) on NYT corpus. 
It might be better with locally trained word embeddings (as opposed to pretrained models on different corpora).

**Comment by lintool** [comment]
@aalbahem this might be a place where you can help? Let's use Lucene to store word embeddings as a dumb key-value store?

**Comment by lintool** [comment]
Note to self - look into deeplearning4j for utils to pre-load word embeddings: https://github.com/deeplearning4j/deeplearning4j/issues/719

**Comment by tteofili** [comment]
@lintool it works with word2vec and GloVe pretrained models.

**Comment by lintool** [comment]
@tteofili I'm looking into this now - integration into Anserini, using Lucene as a dumb key-value store for the vectors. We need this feature no matter what...

Would greatly appreciate code contributions... :)

**Comment by lintool** [comment]
Hi @tteofili give this https://github.com/castorini/Anserini-embeddings

What about building our first embedding based Anserini reranking?
Give this: https://github.com/castorini/Anserini/issues/485#issuecomment-443007726

Do we absolutely need dl4j?

**Comment by tteofili** [comment]
> What about building our first embedding based Anserini reranking?

+1

> Given this: [#485 (comment)](https://github.com/castorini/Anserini/issues/485#issuecomment-443007726)
> 
> Do we absolutely need dl4j?

we can do a reranker which works on a sidecar lookup index for word embeddings based on https://github.com/castorini/Anserini-embeddings. In order to do that we "just" need the nearest neighbour function in place :-)

**Comment by lintool** [comment]
>  In order to do that we "just" need the nearest neighbour function in place :-)

How slow is it if we just brute force it? I.e., iterate through all words? Everything is memory, right? Throw an LRU on top for the most common words?

**Comment by lintool** [comment]
For ANN, seems like we might really need something like https://github.com/spotify/annoy-java

**Comment by tteofili** [comment]
> How slow is it if we just brute force it? I.e., iterate through all words? Everything is memory, right? Throw an LRU on top for the most common words?

I think this would be probably quite slow, even with a cache for common words.

> For ANN, seems like we might really need something like https://github.com/spotify/annoy-java

yes, something like that. there are some interesting considerations for leveraging embeddings in search (lucene/solr) in this presentation: https://www.slideshare.net/SimonHughes13/vectors-in-search-towards-more-semantic-matching.

**Comment by tteofili** [comment]
or, as soon as Anserini is on Lucene 7, we can work with dimensionality reduced word embeddings indexed as `FloatPoints` and [FloatPointNearestNeighbour](https://github.com/apache/lucene-solr/blob/master/lucene/sandbox/src/java/org/apache/lucene/document/FloatPointNearestNeighbor.java#L347). 
So on the Anserini side we wouldn't add any additional dependency. 
We would can use `PCA.pca(...)` from DL4J during embedding indexing in Anserini-embeddings.

**Comment by lintool** [comment]
@tteofili I don't have any experience with `FloatPointNearestNeighbour`... is this something you can prototype? Yes, upgrading to Lucene 7 is a priority.

**Comment by tteofili** [comment]
> @tteofili I don't have any experience with `FloatPointNearestNeighbour`... is this something you can prototype? Yes, upgrading to Lucene 7 is a priority.

yes, I'll prototype that.

**Comment by tteofili** [comment]
@lintool see https://github.com/castorini/Anserini-embeddings/pull/3

**Comment by lintool** [comment]
@tteofili ^^^^^ that's awesome, thanks!

**Comment by lintool** [comment]
We now have [approx. nearest neighbor search](https://github.com/castorini/anserini/blob/master/docs/approximate-nearestneighbor.md) in Anserini, as discussed in https://arxiv.org/abs/1910.10208 

Seem okay to close this issue for now.
