### ISSUE TITLE
Performing retrieval scores documents twice

### ISSUE THREAD

**Issue by Chriskamphuis** [castorini/Anserini#476]
I was trying to run experiments on Disks 4 & 5 (Robust04). After indexing and retrieving as described [here](https://github.com/castorini/Anserini/blob/master/docs/experiments-robust04.md), the output contains two scores for every document.

The output looks like this:

```
301 Q0 FBIS4-39330 1 12.893000 Anserini
301 Q0 FBIS4-39330 2 12.892999 Anserini
301 Q0 FBIS4-40260 3 12.814900 Anserini
301 Q0 FBIS4-40260 4 12.814899 Anserini
301 Q0 FBIS3-24145 5 12.796900 Anserini
301 Q0 FBIS3-24145 6 12.796899 Anserini
301 Q0 FBIS4-46734 7 12.760400 Anserini
301 Q0 FBIS4-46734 8 12.760399 Anserini
301 Q0 FBIS4-7811 9 12.602600 Anserini
301 Q0 FBIS4-7811 10 12.602599 Anserini
```

This does not allow for the evaluation to run as every topic document pair should only have one relevance score when running trec_eval.

**Comment by lintool** [comment]
Hi @Chriskamphuis any idea why every document is indexed twice on your end?

**Comment by Chriskamphuis** [comment]
Hi @lintool, no first I suspected something went wrong with indexing. So I removed the index and reindexed everything, but then the same problem occured again.

**Comment by lintool** [comment]
@Chriskamphuis That's odd... what about your document collection? Are the duplicate documents there?

I've come across duplicate tweets before but that's a collection issue, since the streaming API might deliver a single twee multiple times. I've never come across the issue where every document appears twice...

**Comment by Chriskamphuis** [comment]
@lintool Yes it appears that two sub directories of disk 4 were corrupted. I have no clue what happened, but it was indeed an error in the collection.

**Comment by arjenpdevries** [comment]
Re-finding problem: where are those bl**dy cd-roms?!
_Found them_ - apologies for the chaos here!
