### ISSUE TITLE
document all untuned, oracle/overfitting results in READMEs

### ISSUE THREAD

**Issue by diazf** [castorini/Anserini#482]
Effectiveness metrics in non-JDIQ READMEs do not clearly indicate how the model parameters were selected or default parameters if untuned.

**Comment by Peilin-Yang** [comment]
@diazf I think the commands are all included there (and the default parameters were used)?

**Comment by Peilin-Yang** [comment]
In the JDIQ paper, we explicitly said we've used the oracle setting:

> For all systems, we report results from parameter tuning to optimize average precision (AP) at
rank 1000 on the newswire collections, WT10g, and Gov2, and NDCG@20 for the ClueWeb collections.
There was no separation of training and test data, so these results should be interpreted
as oracle settings.

**Comment by lintool** [comment]
Twitter thread as context: https://twitter.com/diazf_acm/status/1065391723713581056

I've self-assigned and will update the docs accordingly.

**Comment by arjenpdevries** [comment]
Best way to handle is to simply provide additional measurements with default parameters and with 10-fold cross-validation.

The project is very nice ppl!

**Comment by lintool** [comment]
Addressed in #487 and #488
