### ISSUE TITLE
Use Lucene as a key-value store for word embeddings

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#485]
Seems like deeplearning4j can be used for loading pre-trained word embeddings: deeplearning4j/deeplearning4j#719

Basic desired feature is to store word embeddings in Anserini, using Lucene as a simple key-value store. Lookup by word.

We need to think through the tokenization issue... mismatches between the pre-trained word embeddings and Lucene's analysis pipeline.

**Comment by lintool** [comment]
Hi have a simple working demo for this. However, the inclusion of dl4j brings in a whole bunch of dependencies... this blows up the Anserini fatjar from 71MB to 664MB. I think it's better for now to check in the indexing code in a separate repo.

@Peilin-Yang let me know if you have any thoughts...

**Comment by Peilin-Yang** [comment]
1GB of fatjar is just nothing, right?

**Comment by lintool** [comment]
Well, every build recreates the fatjar, so it really slows down the build...

**Comment by Peilin-Yang** [comment]
How slow was that?
The first download should be the most time consuming and once the artifacts are cached locally all subsequent builds should be fast, no?

**Comment by lintool** [comment]
Building the fatjar requires bundling all the component jars together - I believe Maven basically rewrites all the bits each time. So it does add a noticeable delay... the branch is on another machine at home. I'll time it and report back on thread.

**Comment by Peilin-Yang** [comment]
Or you can push the branch and I will test it.

**Comment by lintool** [comment]
```
$ time mvn clean package appassembler:assemble
```
Before, two trials:

```
real	0m18.799s
user	1m5.853s
sys	0m8.929s

real	0m18.811s
user	1m5.920s
sys	0m9.211s
```

After, two trials:

```
real	1m34.223s
user	2m27.208s
sys	0m12.106s

real	1m32.926s
user	2m24.764s
sys	0m11.871s
```

This is on my iMac Pro at home, which is a reasonable desktop. I think the verdict is clear - the cost doesn't make sense at this point, since all we're doing is using dl4j to read word embeddings to index in Lucene. I'll put the indexing code in a separate repo, but still ask for CR there.

If we end up using more dl4j features in the future, we'll revisit.

**Comment by lintool** [comment]
@tteofili @Peilin-Yang https://github.com/castorini/Anserini-embeddings/ seem to work fine, closing for now.
