### ISSUE TITLE
try jtreceval

### ISSUE THREAD

**Issue by cmacdonald** [castorini/anserini#489]
Downloading, compiling trec_eval C binary etc looks like a pain. We have jars with binaries compiled in directly - see https://github.com/terrierteam/jtreceval - also available on MavenCentral.

**Comment by lintool** [comment]
This is a great resource and we've been using it for a while now, e.g., https://github.com/castorini/anserini-notebooks/blob/master/pyserini_msmarco_passage_demo.ipynb

Thanks @cmacdonald !
