### ISSUE TITLE
How to get each docno‘s corpus(text)?

### ISSUE THREAD

**Issue by bayou3** [castorini/Anserini#503]
Hello, I have run the command “nohup sh target/appassembler/bin/IndexCollection -collection ClueWeb09Collection \
-generator JsoupGenerator -threads 44 -input /path/to/cw09b -index \
lucene-index.cw09b.pos+docvectors -storePositions -storeDocvectors -storeRawDocs \
>& log.cw09b.pos+docvectors+rawdocs &”.
After it, I got a lot of files, for instance, the files started with "_3" are [_3.fdt, _3.fdx, _3.fnm, _3_Lucene50_0.doc, _3_Lucene50_0.pos, _3_Lucene50_0.tim, _3_Lucene50_0.tip, _3_Lucene54_0.dvd, _3_Lucene54_0.dvm,  _3.nvd,  _3.nvm, _3.si, _3.tvd, _3.tvx ]. 

Among them, _3.fdt is of biggest size, 5.2G, if I check its content, it displays some messy code(text). 
My goal is to obtain the plain text of each doc, so how should I do ?
Thank you!

**Comment by lintool** [comment]
Use this class to fetch docs from the index: https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java

Run as:

```
$ target/appassembler/bin/IndexUtils [...options see above...]
```

**Comment by bayou3** [comment]
> Use this class to fetch docs from the index: https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java
> 
> Run as:
> 
> ```
> $ target/appassembler/bin/IndexUtils [...options see above...]
> ```

I use commands
“Anserini/target/appassembler/bin/IndexUtils -dumpRawDocs ClueWeb09B_path -index lucene-index.cw09b/”  (lucene-index.cw09b is the path after index building)
or
"Anserini/target/appassembler/bin/IndexUtils -dumpRawDocs lucene-index.cw09b/ -index lucene-index.cw09b/"
All ot these two reports errors. 
I read the codes of your link:
"public void dumpRawDocuments(String reqDocidsPath, boolean prependDocid) throws IOException, NotStoredException {
    LOG.info("Start dump raw documents" + (prependDocid ? " with Docid prepended" : "."));

    InputStream in = getReadFileStream(reqDocidsPath); 
“
Then what should reqDocidsPath be or how can I modify the common for fetching corpus?

**Comment by lintool** [comment]
What errors are you getting?

**Comment by lintool** [comment]
Did you check out the command line options?

```
$ target/appassembler/bin/IndexUtils
Option "-index" is required
 -convertDocidToLuceneDocid docid       : converts a collection lookupDocid to a Lucene
                                          internal lookupDocid
 -convertLuceneDocidToDocid docid       : converts to a Lucene internal lookupDocid to a
                                          collection lookupDocid  (default: 0)
 -docVectorWeight [NONE | TF_IDF]       : the weight for dumped document vector(s), NONE
                                          or TF_IDF
 -dumpAllDocids [NONE | GZ | BZ2 | ZIP] : dumps all docids in sorted order. For non-tweet
                                          collection the order is in ascending of String
                                          docid; For tweets collection the order is in
                                          descending of Long tweet idplease provide the
                                          compression scheme for the output
 -dumpDocVector docid                   : prints the document vector of a document
 -dumpDocVectors [Path]                 : dumps the document vector for all documents
                                          from input file
 -dumpRawDoc docid                      : dumps raw document (if stored in the index)
 -dumpRawDocs [Path]                    : dumps raw documents from the input file
 -dumpRawDocsWithDocid [Path]           : By default there is no <DOCNO>docid<DOCNO>
                                          stored in the raw docs. By prepending
                                          <DOCNO>docid<DOCNO> in front of the raw docs we
                                          can directly index them
 -dumpSentences docid                   : splits the fetched document into sentences (if
                                          stored in the index)
 -dumpTransformedDoc docid              : dumps transformed document (if stored in the
                                          index)
 -index [Path]                          : index path
 -printTermInfo term                    : prints term info (stemmed, total counts, doc
                                          counts, etc.)
 -stats                                 : print index statistics (default: false)
```

**Comment by Peilin-Yang** [comment]
@bayou3 
Hi, Welcome!
I am not sure if you want to point query some specific documents or want to do it for a bunch of docIds.

For dumping just 1 doc what you need to do is:
```
Anserini/target/appassembler/bin/IndexUtils -index path_to_index -dumpRawDoc doc_id
```
However, please note that the `doc_id` above is the external doc_id -- i.e. it is what natively in the document which you might not easily know.
`IndexUtils` has another option which you can convert the Lucene's internal docid to an external docid 
```
Anserini/target/appassembler/bin/IndexUtils -index path_to_index -convertLuceneDocidToDocid doc_id
```

So for point query a random document you can do it with one command: 
```
target/appassembler/bin/IndexUtils -index /scratch2/indexes/lucene6/lucene-index.robust04.pos+docvectors+rawdocs/ -dumpRawDoc `target/appassembler/bin/IndexUtils -index /scratch2/indexes/lucene6/lucene-index.robust04.pos+docvectors+rawdocs/ -convertLuceneDocidToDocid 1`
```
Then you will at least see a raw document.

Hope this helps.

**Comment by bayou3** [comment]
Thank @lintool  and @Peilin-Yang very much!
The issue I came into is due to lack of docids. So I run "target/appassembler/bin/IndexUtils -index path_to_index  -dumpAllDocids none" firstly to get docids file, and then use "-dumpRawDocs" with the docids file to get the finall raw docs.  :)

**Comment by cramraj8** [comment]
Hello, I don't find the IndexUtils program in the current master-branch clone. Is this function to get document's text available ?

**Comment by lintool** [comment]
See https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexReaderUtils.java

Specifically, https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexReaderUtils.java#L436

There's also `documentRaw` and `documentContents`.
