### ISSUE TITLE
Write partitioned tweets indexer

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#51]
Write an indexer that indexes tweets into multiple partitions - simple round robin strategy would be a reasonable start.

**Comment by Peilin-Yang** [comment]
Is this still a requirement?

**Comment by lintool** [comment]
It would still be a nice feature to have - not only tweets, but also other documents as well. My former student Yulu Wang worked on this: https://dl.acm.org/citation.cfm?id=3018727

Would be nice to have Anserini implementation...

**Comment by lintool** [comment]
Not much interest in working on tweet search (anymore)...
