### ISSUE TITLE
Put example command to dump LTR feaures into the README.md

### ISSUE THREAD

**Issue by claclark** [castorini/Anserini#53]
specifically

sh target/appassembler/bin/DumpTweetsLtrData -index tweets2011-index/ -topics src/main/resources/topics-and-qrels/topics.microblog2011.txt -output ltr.data.txt -qrels src/main/resources/topics-and-qrels/qrels.microblog2011.txt -ql

**Comment by lintool** [comment]
The entire LTR pipeline needs to be revamped, so closing issue for now.
