### ISSUE TITLE
Code for Anserini indexing into Solr

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#534]
Hi @r-clancy IIRC you have code that will allow us to use the Anserini frontend to index directly into a Solr instance via SolrJ? Can you please send a PR so I can start playing with it?

So, in theory, I should be able to start up based on Docker here https://github.com/castorini/SolrAnserini and then index directly into the instance?

**Comment by r-clancy** [comment]
Closing, see https://github.com/castorini/Anserini/pull/536.
