### ISSUE TITLE
How to obtain a DFCF file from the built index?

### ISSUE THREAD

**Issue by bayou3** [castorini/Anserini#540]
Hi, the index has been built successfully by your command guide. 
Then I want to count the DFCF ( document frequency, category frequency) from the index. Previously, when I used terrier tool to construct the index, it will generate a data.properties file, then using a written program extractDFCF.ictFormat.jar can easily get DFCF from the terrier-constructed index. So can I get DFCF from the  Anserini-constructed index ?

**Comment by Peilin-Yang** [comment]
@bayou3 

Anserini has an application `IndexUtils` and the command 
```
target/appassembler/bin/IndexUtils -index path_to_index -printTermInfo term | grep "document frequency"
```
can give you the document frequency. The code is here https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java#L179

I am not sure what is `category frequency`?

**Comment by bayou3** [comment]
@Peilin-Yang Thank you so much for pointing me out,  it is so helpful. CF is collection frequency. Although it seems to take some time to run this command, I use another script to interrupt it and obtain the needed DF. Thank you!
