### ISSUE TITLE
Export Anserini (Lucene) index to Solr

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#558]
We currently use Docker: https://github.com/castorini/SolrAnserini

Seems to me that using Docker isn't particularly necessary, since Solr itself is pretty easy to stand up. Would be nice to have something like this:

```
export_index_to_solr --solr-root /path/ -core core17 ...
```

**Comment by r-clancy** [comment]
Do we still need this after adding https://github.com/castorini/anserini/pull/600?

**Comment by lintool** [comment]
No longer needed. Closing.
