### ISSUE TITLE
Very high max memory allocation

### ISSUE THREAD

**Issue by tokee** [castorini/Anserini#572]
The `target/appassembler/bin/` scripts has `Xmx` set to `256G`: https://github.com/castorini/Anserini/blob/master/pom.xml#L94

This is a very high memory allocation: I tried running Anserini with the default `256GB` on a machine with ~90GB available memory and it kept increasing the heap until it had allocated it all + the swap file. This is expectable behaviour from the JVM: With `256GB` the Anserini tools can only reliably run on a machine with at least that amount of available memory.

An ad hoc test with 39GB of `ClueWeb12` material shows that `IndexCollection` with 40 threads runs fine with `8GB`, both in lucene & solr mode. Maybe the`Xmx` should be adjustable?

Addendum: This seems to be a replica of #516, except that the proposed solution there is to modify the `pom.xml`, which seems strange to me.

**Comment by r-clancy** [comment]
In https://github.com/castorini/Anserini/pull/573 the `Xmx` value has been reduced to `31G` from `256G`. From testing with the full `cw09b` dataset, it seems to remain stable around `24G`. This might be a little high still, but it's much more reasonable than `256G`.

**Comment by lintool** [comment]
Memory usage has been dialed back to 31g in commit 67ecbbe651335f94414a3e55bba5814be0292d4e.

Reran all regressions from scratch (including indexing):

```
[o] python src/main/python/run_regression.py --collection cacm --index
[o] nohup python src/main/python/run_regression.py --index --collection disk12 >& log.disk12 &
[o] nohup python src/main/python/run_regression.py --index --collection robust04 >& log.robust04 &
[o] nohup python src/main/python/run_regression.py --index --collection robust05 >& log.robust05 &
[o] nohup python src/main/python/run_regression.py --index --collection core17 >& log.core17 &
[o] nohup python src/main/python/run_regression.py --index --collection core18 >& log.core18 &
[o] nohup python src/main/python/run_regression.py --index --collection mb11 >& log.mb11 &
[x] nohup python src/main/python/run_regression.py --index --collection mb13 >& log.mb13 &
[o] nohup python src/main/python/run_regression.py --index --collection wt10g >& log.wt10g &
[o] nohup python src/main/python/run_regression.py --index --collection gov2 >& log.gov2 &
[o] nohup python src/main/python/run_regression.py --index --collection car17 >& log.car17 &
[o] nohup python src/main/python/run_regression.py --index --collection cw09b >& log.cw09b &
[o] nohup python src/main/python/run_regression.py --index --collection cw12b13 >& log.cw12b13 &
[o] nohup python src/main/python/run_regression.py --index --collection cw12 >& log.cw12 &

[o] nohup python src/main/python/jdiq2018/run_regression.py --collection disk12 >& jdiq2018.disk12.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection robust04 >& jdiq2018.robust04.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection robust05 >& jdiq2018.robust05.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection wt10g >& jdiq2018.wt10g.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection gov2 >& jdiq2018.gov2.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection cw09b --metrics map ndcg20 err20 >& jdiq2018.cw09b.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection cw12b13 --metrics map ndcg20 err20 >& jdiq2018.cw12b13.log &
```
Everything passes except for `mb13`, which throws OOM. It passes with 48g. Okay to keep 31g setting I think, just watch out when running regressions in the future.

Closing.
