### ISSUE TITLE
Releasing v0.4.0

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#579]
We've seemed to have reached a checkpoint. Major changes include:
+ upgrade to Lucene 7.6
+ ECIR runbooks
+ Anserini/Solr integration

Seems like a good idea to do an official release? Thoughts?

@Peilin-Yang @lukuang @r-clancy @Victor0118 ?

**Comment by lukuang** [comment]
sg

**Comment by r-clancy** [comment]
:+1:

**Comment by lintool** [comment]
Version 0.4.0 officially released!
Release notes at https://github.com/castorini/Anserini/blob/master/docs/release-notes/release-notes-v0.4.0.md

Thanks to @Peilin-Yang @r-clancy @Victor0118 @tokee @Kytabyte @andrewyates @Chriskamphuis @tiddler @tteofili for your contributions!
