### ISSUE TITLE
Partial replication failure on ClueWeb12-B13 for ax models

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#592]
According to #590 @matthew-z wasn't able to replicate results with ax models on ClueWeb12-B13. We should look into this...

**Comment by matthew-z** [comment]
Somehow the AX results matched after indexing again with oracle JVM (1.8.0_201)....

**Comment by lintool** [comment]
Interesting.

Hypothesis is that pseudo-random number generation works differently in OpenJDK vs. Oracle JVM. This would explain the differences in ax results, which rely on sampling docs.

@matthew-z Just to be clear, with Oracle JVM you are able to replicate our figures *exactly*, while with OpenJDK you come close? (If so, how close is "close" in the latter case?)

**Comment by matthew-z** [comment]
Did you mean no-AX algorithms?   They matched exactly I remember. sorry, the openJDK results have been covered by the oracle ones. I will try openjdk again.

**Comment by lintool** [comment]
Okay, thanks! I'll send a PR to capture this discussion and ask you to review.

**Comment by lintool** [comment]
@matthew-z please look at https://github.com/castorini/Anserini/pull/594

**Comment by lintool** [comment]
Resolved with #594, closing.

**Comment by Peilin-Yang** [comment]
> Hypothesis is that pseudo-random number generation works differently in OpenJDK vs. Oracle JVM.

I am not sure, but this is unlikely IMO.
I am going to test it again by myself

**Comment by lintool** [comment]
Whatever the issue, Oracle vs. openJDK isn't the issue. All regressions run fine on `damiano`:

```
[jimmylin@damiano ~]$ java --version
openjdk 11.0.4 2019-07-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11-LTS, mixed mode, sharing)
```
