### ISSUE TITLE
RRF between RM3 and Ax

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#615]
As a simple experiment, let's trying running RRF between RM3 and Ax: this package seems to already have RRF implemented: https://github.com/joaopalotti/trec_tools

@emmileaf this might not make much sense right now, but I'll walk you through this...

**Comment by lintool** [comment]
@emmileaf you showed me some results on this? Can you post to this thread?

**Comment by emmileaf** [comment]
__Robust04:__

|     | BM25+AX | BM25+RM3 | BM25+AX+RM3 (RRF) | P-value (Base: BM25+AX) | P-value (Base: BM25+RM3) |
|-----|:-------:|:--------:|:-----------------:|:-----------------------:|:------------------------:|
| MAP |  0.2895 |  0.2903  |       0.2963      |         0.019821        |         0.024997         |
| P30 |  0.3333 |  0.3365  |       0.3410      |         0.037711        |         0.161866         |
|     |         |          |                   |                         |                          |

__Core17:__

|     | BM25+AX | BM25+RM3 | BM25+AX+RM3 (RRF) | P-value (Base: BM25+AX) | P-value (Base: BM25+RM3) |
|-----|:-------:|:--------:|:-----------------:|:-----------------------:|:------------------------:|
| MAP |  0.2700 |  0.2682  |       0.2813      |         0.030513       |         0.019737         |
| P30 |  0.4927 |  0.4940  |       0.4973     |         0.588484        |         0.740242        |
|     |         |          |                   |                         |                          |


For Core18, I just realized that my results were inconsistent with the experiments doc, and will need to double check and debug a bit more...

**Comment by lintool** [comment]
@emmileaf Thanks! Can you try the other fusion methods offered by the package?

**Comment by emmileaf** [comment]
For sure- I'll add to this thread.

**Comment by emmileaf** [comment]
Other fusion methods from [trectools](https://github.com/joaopalotti/trectools/blob/master/trectools/fusion.py):

#### Rank Biased Precision

Robust04:

|     | BM25+AX | BM25+RM3 | BM25+AX+RM3 (RBP) | P-value (Base: BM25+AX) | P-value (Base: BM25+RM3) |
|-----|:-------:|:--------:|:-----------------:|:-----------------------:|:------------------------:|
| MAP |  0.2895 |  0.2903  |       0.2682      |        0.000000        |         0.000000         |
| P30 |  0.3333 |  0.3365  |       0.3396      |         0.061813        |         0.345704         |
|     |         |          |                   |                         |                          |

Core17:

|     | BM25+AX | BM25+RM3 | BM25+AX+RM3 (RBP) | P-value (Base: BM25+AX) | P-value (Base: BM25+RM3) |
|-----|:-------:|:--------:|:-----------------:|:-----------------------:|:------------------------:|
| MAP |  0.2700 |  0.2682  |       0.2330      |         0.000093       |        0.000835         |
| P30 |  0.4927 |  0.4940  |       0.5067     |         0.161777        |         0.105224        |
|     |         |          |                   |                         |                          |

#### Vector Space Fusion

Robust04:

|     | BM25+AX | BM25+RM3 | BM25+AX+RM3 (VSF) | P-value (Base: BM25+AX) | P-value (Base: BM25+RM3) |
|-----|:-------:|:--------:|:-----------------:|:-----------------------:|:------------------------:|
| MAP |  0.2895 |  0.2903  |       0.2901      |         0.073643        |         0.966559         |
| P30 |  0.3333 |  0.3365  |       0.3336      |         0.670020        |          0.604390         |
|     |         |          |                   |                         |                          |

Core17:

|     | BM25+AX | BM25+RM3 | BM25+AX+RM3 (VSF) | P-value (Base: BM25+AX) | P-value (Base: BM25+RM3) |
|-----|:-------:|:--------:|:-----------------:|:-----------------------:|:------------------------:|
| MAP |  0.2700 |  0.2682  |       0.2708      |         0.007257       |        0.790198         |
| P30 |  0.4927 |  0.4940  |       0.4953     |         0.044315        |          0.927823        |
|     |         |          |                   |                         |                          |

#### Combination (score sum)

Robust04:

|     | BM25+AX | BM25+RM3 | BM25+AX+RM3 (SUM) | P-value (Base: BM25+AX) | P-value (Base: BM25+RM3) |
|-----|:-------:|:--------:|:-----------------:|:-----------------------:|:------------------------:|
| MAP |  0.2895 |  0.2903  |       0.2925      |         0.000281        |         0.632728         |
| P30 |  0.3333 |  0.3365  |       0.3352      |         0.208824        |           0.794289         |
|     |         |          |                   |                         |                          |

Core17:

|     | BM25+AX | BM25+RM3 | BM25+AX+RM3 (SUM) | P-value (Base: BM25+AX) | P-value (Base: BM25+RM3) |
|-----|:-------:|:--------:|:-----------------:|:-----------------------:|:------------------------:|
| MAP |  0.2700 |  0.2682  |       0.2742      |         0.004270       |        0.500317         |
| P30 |  0.4927 |  0.4940  |       0.4987     |         0.083058        |           0.738421        |
|     |         |          |                   |                         |                          |

**Comment by lintool** [comment]
so tl;dr - is that RRF still works the best?

**Comment by emmileaf** [comment]
Yup looks like it, at least for default params/etc. from the package.

**Comment by lintool** [comment]
Merging of #658 unblocked Core18
Per #668, Core17 probably needs to be rerun

**Comment by emmileaf** [comment]
> Merging of #658 unblocked Core18
> Per #668, Core17 probably needs to be rerun

- Results re-run and edited in comments above. 
- TLDR from updated results: RRF still the most effective, but does not perform as well on core17/core18 compared to robust04.

**Comment by lintool** [comment]
Good to have these results, but moving forward this should probably be done on the Pyserini end...
