### ISSUE TITLE
Anserini  - The main class cannot be detected

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#631]
Dear Sir
I am trying to run Anserini Commands on TREC CommonCore 2017
https://github.com/castorini/anserini/blob/master/docs/experiments-core17.md
The problem is that the main class cannot be detected

![image](https://user-images.githubusercontent.com/47518534/57275283-f4bd5e80-7095-11e9-9cfb-0075127a7e0a.png)
It might be from here "Class path" or somthing relted to it
![image](https://user-images.githubusercontent.com/47518534/57275229-cfc8eb80-7095-11e9-83e3-d0d3e82eda57.png)

**Comment by lintool** [comment]
Can you try running from the command line instead of from IntelliJ?

**Comment by ABDULAZIZALQATAN** [comment]
Thanks sir for response
Tried with Windows Command Line - Ubuntu Terminal - Cygwing Command Line - Intellj Maven >>> many things tried over days
I would be grateful if you help
Regards

**Comment by lintool** [comment]
Can you copy and paste your command-line invocation and the error you get? @emmileaf might be able to help - she's a Windows user also.

**Comment by ABDULAZIZALQATAN** [comment]
Command 
```
nohup sh target/appassembler/bin/IndexCollection -collection \
NewYorkTimesCollection -generator JsoupGenerator -threads 16 -input \
"C;\Users\kkb19103\Desktop\My Files\Original Files\TREC-CommonCore 2017\nyt_corpus" -index lucene-index.core17.pos+docvectors+rawdocs \
-storePositions -storeDocvectors -storeRawDocs >& \
log.core17.pos+docvectors+rawdocs &
```
Error 
![error](https://user-images.githubusercontent.com/47518534/57304178-c2802100-70d6-11e9-8b4c-940f2d4a7770.png)

Suggestion 
![4](https://user-images.githubusercontent.com/47518534/57304205-d0ce3d00-70d6-11e9-9d9e-77e5b130422b.jpg)

No problem with windows 
![3](https://user-images.githubusercontent.com/47518534/57304269-eb081b00-70d6-11e9-8a43-4062df30aec9.jpg)

**Comment by emmileaf** [comment]
Hi @ABDULAZIZALQATAN,
Unfortunately I wasn't able to replicate the problem on Windows 10... what version of maven are you using? Could you check perhaps if the classpath contains `"$REPO"/io/anserini/anserini/0.4.1-SNAPSHOT/anserini-0.4.1-SNAPSHOT.jar` ?

**Comment by ABDULAZIZALQATAN** [comment]
Maven Version
![8](https://user-images.githubusercontent.com/47518534/57307245-235e2800-70dc-11e9-9ff2-b4bb6d21c979.jpg)

Class path 
![7](https://user-images.githubusercontent.com/47518534/57307295-396be880-70dc-11e9-96ce-7750d2f3af11.jpg)

**Comment by emmileaf** [comment]
Are you building the package from command line or IntelliJ? I wonder if this might be an IntelliJ Maven issue...

Not sure if you've already done this, but perhaps you could try installing Maven 3.3+ separately from IntelliJ, add it to `PATH`, and run  `mvn clean package appassembler:assemble` from command line?

**Comment by Peilin-Yang** [comment]
We should build a Docker file/registry to avoid such issues

**Comment by ABDULAZIZALQATAN** [comment]
Thanks Emily for your support >>>  You were right >>> I installed the latest MVN and Java JDK
when I run `mvn clean package appassembler:assemble`
I get the following error >>> 
I will try to do my best to resolve with you and tell the others the reson behind that

![9](https://user-images.githubusercontent.com/47518534/57426415-fcf0d780-7216-11e9-8229-327d19add3b0.jpg)

Some of the report files attached to the error

[io.anserini.collection.TrecDocumentTest.txt](https://github.com/castorini/anserini/files/3160297/io.anserini.collection.TrecDocumentTest.txt)

[io.anserini.collection.TrecwebDocumentTest.txt](https://github.com/castorini/anserini/files/3160298/io.anserini.collection.TrecwebDocumentTest.txt)

In the End App Assembler is not generated 

![11](https://user-images.githubusercontent.com/47518534/57426540-7688c580-7217-11e9-815f-99e4b2569553.jpg)

**Comment by emmileaf** [comment]
This looks similar to what I had encountered in issue [#619](https://github.com/castorini/anserini/issues/619). 

There seems to be a Windows specific file deletion problem for some of the tests... perhaps you can try the tweak from [#619](https://github.com/castorini/anserini/issues/619) for tests that are failing for you and see if that resolves the error? 

Building with `-DskipTests` can also skip the tests in the meanwhile.

**Comment by ABDULAZIZALQATAN** [comment]
Thanks again for support >>> It looks like that this is very easy for you :) 
after skipping tests and we override test problem the following error occurs 
![10](https://user-images.githubusercontent.com/47518534/57428492-8eb11280-7220-11e9-9ce9-41280d412294.jpg)

**Comment by ABDULAZIZALQATAN** [comment]
![12](https://user-images.githubusercontent.com/47518534/57523675-8559a000-731d-11e9-8795-84b7d7a60a39.jpg)

Thank GOD it works >>> when I change my Java JDK Version and Skip Tests 
Thanks for your amazing support

**Comment by lintool** [comment]
If you're able to replicate our results, please feel free to contribute a short log entry, just like: https://github.com/castorini/anserini/blob/master/docs/experiments-core17.md

<img width="536" alt="Screen Shot 2019-05-10 at 7 54 34 AM" src="https://user-images.githubusercontent.com/313837/57525489-e0c56700-72f8-11e9-9ba2-0dc075000b2c.png">

Send a pull request and we'll merge.

Otherwise, best of luck. Closing issue.
