### ISSUE TITLE
Tiny Indexes performance

### ISSUE THREAD

**Issue by ArthurCamara** [castorini/anserini#637]
We are running experiments on a small collection, that will generate multiple, tiny indexes, that will be used for one single query. 

Simply put, we just want to use Anserini's implementation of BM25+RM3, instead of having to index these collections on disk.

Two options came into mind: 
1- Some API call that would directly call BM25+RM3 on the Anserini backend
2- Use Lucene's MemoryIndex

Which one is more appropriate?

**Comment by lintool** [comment]
Do you really want lots of tiny indexes? In Lucene, it is possible to say, "search query q, but only rank the following subset of doc {d1, d2, ...}"

If you really want lots of tiny indexes, Lucene's MemoryIndex is probably the way to go.

**Comment by ArthurCamara** [comment]
The first one would work. How do Anserini deals with passing arguments to the Lucene backend?

**Comment by yangwanning** [comment]
> Do you really want lots of tiny indexes? In Lucene, it is possible to say, "search query q, but only rank the following subset of doc {d1, d2, ...}"
> 
> If you really want lots of tiny indexes, Lucene's MemoryIndex is probably the way to go.

Also wondering how to do with first way which specify a certain set of docs when search a certain query q. Can you please show the way to do that? Thanks!!

**Comment by lintool** [comment]
@yangwanning sorry for the late reply - must have missed this.

> Also wondering how to do with first way which specify a certain set of docs when search a certain query q. Can you please show the way to do that? Thanks!!

Check out -

https://github.com/castorini/anserini/blob/master/src/test/java/io/anserini/integration/IndexerTest.java#L213

The trick is to add a query that only matches on a particular document. You can make it a boolean OR to match on multiple documents.

**Comment by lintool** [comment]
Closing... please reopen if there are any more issues.
