### ISSUE TITLE
Core 18 WAPO - Many Document Vectors are not Sorted (Null Term Frequency ) is this Normal?

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#646]
Dear Sir 
I ran retrieval method on Core18 as mentoined in this website 
there are many document vectors that were not sorted >>> is this normal ? specially when I saw your code this situation happens when Term Frequency is null or something wrong with it for a specific document

![1](https://user-images.githubusercontent.com/47518534/57672580-a6b5d700-7610-11e9-984c-ad33830d13d9.jpg)

![Code Not Sorted](https://user-images.githubusercontent.com/47518534/57672609-b7664d00-7610-11e9-9a12-55d3fdb5ac4a.jpg)

**Comment by emmileaf** [comment]
For the Washington Post Collection, body content is currently defined by text having content type of `sanitized_html` or `tweet`. Around 4% of Core18 documents have empty body content (e.g. images) so no term vector is created, but other parsed fields such as title are stored and the document is not skipped over. 

My guess is that when the axiomatic reranker selects a set of R*N document ids, the (N-1)*R randomly picked documents may contain these documents that are effectively empty. It looks like the warnings are for the same four documents in each query run, so this probably doesn't have a major impact on the query expansion.

**Comment by lintool** [comment]
@emmileaf Thanks for looking into this, I've created #654 as follow up, but this issue seems like its resolved.
