### ISSUE TITLE
Error During Training Classifier 

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#647]
I am currently replicating the experiment of h2oloo Group
on this stage : "Training and Generating Classifier Results"
I got a error while I was running the following command : 
```
python script/train.py --train-folder main_folder/train/ \
 --test-folder main_folder/test/ \
 --rank-file src/main_folder/test/Core18_rerank_[rm3|ax].txt \
 --classifier clf --output-folder main_folder/output/clf
```
After following the exact steps for that I got the following  :
![Training](https://user-images.githubusercontent.com/47518534/57755352-a4bf4700-76e8-11e9-922e-ece00f6b0257.jpg)

Any idea how to overcome this one

**Comment by lintool** [comment]
What does Google say when you search for the error? Sorry, I don't have any experience running Python on Windows... however, this appears to be a lightgbm issue, so you can try disabling it?

**Comment by ABDULAZIZALQATAN** [comment]
Sure Sir 
I googled it and I am still googling >> one of the ideas is to shorten the path by putting the project under C directly 
I will try to resolve it and tell everybody here what I did 
Thanks for your ccoperation and patience 
Regards

**Comment by ABDULAZIZALQATAN** [comment]
Dear All 
The problem is resolved easily by installing the latest 
**Microsoft Visual C++ Redistributable for Visual Studio 2019** 
From The Following Link : 
[https://visualstudio.microsoft.com/downloads/](https://visualstudio.microsoft.com/downloads/)
because the latest lightgbm is included in it >>> I used pip to install it and that arose the issue >>> just Install redistributable c++ or any other installation method according to their gitHub Page 
[https://github.com/microsoft/LightGBM/blob/master/docs/Installation-Guide.rst](https://github.com/microsoft/LightGBM/blob/master/docs/Installation-Guide.rst)

**Comment by lintool** [comment]
Glad you sorted the issue out. Closing.
