### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by rodrigonogueira4** [castorini/anserini#648]
After I type:
mvn clean package appassembler:assemble

I get the following error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.965 s
[INFO] Finished at: 2019-05-19T09:06:52-04:00
[INFO] Final Memory: 31M/1583M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project anserini: Could not resolve dependencies for project io.anserini:anserini:jar:0.4.1-SNAPSHOT: Failed to collect dependencies at com.fasterxml.jackson.core:jackson-databind:jar:2.9.8: Failed to read artifact descriptor for com.fasterxml.jackson.core:jackson-databind:jar:2.9.8: Could not transfer artifact com.fasterxml.jackson.core:jackson-databind:pom:2.9.8 from/to public (https://repo1.maven.org/maven2): Input/output error -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

I'm using maven 3.52 and the following Java:
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Comment by lintool** [comment]
Try cleaning the Maven cache?
https://stackoverflow.com/questions/7408545/how-do-you-clear-apache-mavens-cache

**Comment by rodrigonogueira4** [comment]
I now get a different error:

$ rm -r /home/rfn216/.m2/
$ mvn clean package appassembler:assemble

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.129 s
[INFO] Finished at: 2019-05-19T09:16:42-04:00
[INFO] Final Memory: 26M/1583M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.codehaus.mojo:appassembler-maven-plugin:2.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:appassembler-maven-plugin:jar:2.0.0: Could not transfer artifact org.codehaus.mojo:appassembler-maven-plugin:pom:2.0.0 from/to central (https://repo.maven.apache.org/maven2): Input/output error -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by lintool** [comment]
Hrm. I just did:

```
$ rm -r ~/.m2/repository/
```
Cannot appear to replicate your behavior:

```
$ mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_172, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.4", arch: "x86_64", family: "mac"
```
Some maven oddness...

**Comment by rodrigonogueira4** [comment]
After waiting a week, it magically fixed itself.

**Comment by lintool** [comment]
:)

**Comment by dzhao123** [comment]
@lintool it seems I have smilar problem.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.198 s
[INFO] Finished at: 2020-02-21T15:40:38-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project anserini: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by dzhao123** [comment]
https://stackoverflow.com/questions/23260057/the-forked-vm-terminated-without-saying-properly-goodbye-vm-crash-or-system-exi?page=1&tab=votes#tab-top
Solved.
