### ISSUE TITLE
read term vctor

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#651]
Dear Sir 
Is there anyway to read the generated binary Document Vectors and Term Vectors ?
Is it involved in your Feature Extractor ?

![FeatureExtractor](https://user-images.githubusercontent.com/47518534/57996016-0dc60680-7abd-11e9-8690-edbb53239717.jpg)

![2](https://user-images.githubusercontent.com/47518534/57996027-1fa7a980-7abd-11e9-82a0-1b1301dc0be0.jpg)

**Comment by ABDULAZIZALQATAN** [comment]
Dear Sir 
Is there anyway to read the generated binary Document Vectors and Term Vectors ?
Is it involved in your Feature Extractor ?

![FeatureExtractor](https://user-images.githubusercontent.com/47518534/57996016-0dc60680-7abd-11e9-8690-edbb53239717.jpg)

![2](https://user-images.githubusercontent.com/47518534/57996027-1fa7a980-7abd-11e9-82a0-1b1301dc0be0.jpg)

**Comment by lintool** [comment]
Check out this test case:
https://github.com/castorini/anserini/blob/master/src/test/java/io/anserini/integration/IndexerTest.java#L166

It should have everything you need...

**Comment by lintool** [comment]
I'm assuming this has been resolved? Closing, but re-open otherwise.
