### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ChrisRBXiong** [castorini/anserini#653]
I am using the aliyun maven repository, and can not build the project. Is my usage correct? Thansk a lot !

after I type:
`mvn clean package appassembler:assemble -e`

I get following error:

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-compiler-plugin/3.7.0/maven-compiler-plugin-3.7.0.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-compiler-plugin/3.7.0/maven-compiler-plugin-3.7.0.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-compiler-plugin:3.7.0: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.7.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-compiler-plugin:jar:3.7.0
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/codehaus/mojo/appassembler-maven-plugin/2.0.0/appassembler-maven-plugin-2.0.0.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/codehaus/mojo/appassembler-maven-plugin/2.0.0/appassembler-maven-plugin-2.0.0.pom
[WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:appassembler-maven-plugin:2.0.0: Plugin org.codehaus.mojo:appassembler-maven-plugin:2.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:appassembler-maven-plugin:jar:2.0.0
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-javadoc-plugin/3.0.1/maven-javadoc-plugin-3.0.1.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-javadoc-plugin/3.0.1/maven-javadoc-plugin-3.0.1.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-javadoc-plugin:3.0.1: Plugin org.apache.maven.plugins:maven-javadoc-plugin:3.0.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-javadoc-plugin:jar:3.0.1
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-shade-plugin/3.1.0/maven-shade-plugin-3.1.0.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-shade-plugin/3.1.0/maven-shade-plugin-3.1.0.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-shade-plugin:3.1.0: Plugin org.apache.maven.plugins:maven-shade-plugin:3.1.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-shade-plugin:jar:3.1.0
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-source-plugin/3.0.1/maven-source-plugin-3.0.1.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-source-plugin/3.0.1/maven-source-plugin-3.0.1.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-source-plugin:3.0.1: Plugin org.apache.maven.plugins:maven-source-plugin:3.0.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-source-plugin:jar:3.0.1
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-deploy-plugin/2.8.2/maven-deploy-plugin-2.8.2.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-deploy-plugin/2.8.2/maven-deploy-plugin-2.8.2.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-deploy-plugin:2.8.2: Plugin org.apache.maven.plugins:maven-deploy-plugin:2.8.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-deploy-plugin:jar:2.8.2
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-release-plugin/2.5.3/maven-release-plugin-2.5.3.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-release-plugin/2.5.3/maven-release-plugin-2.5.3.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-release-plugin:2.5.3: Plugin org.apache.maven.plugins:maven-release-plugin:2.5.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-release-plugin:jar:2.5.3
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-gpg-plugin/1.6/maven-gpg-plugin-1.6.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-gpg-plugin/1.6/maven-gpg-plugin-1.6.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-gpg-plugin:1.6: Plugin org.apache.maven.plugins:maven-gpg-plugin:1.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-gpg-plugin:jar:1.6
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-clean-plugin:2.5: Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-resources-plugin:2.6: Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-jar-plugin:2.4: Plugin org.apache.maven.plugins:maven-jar-plugin:2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-jar-plugin:jar:2.4
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-surefire-plugin:2.12.4: Plugin org.apache.maven.plugins:maven-surefire-plugin:2.12.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-surefire-plugin:jar:2.12.4
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-install-plugin:2.4: Plugin org.apache.maven.plugins:maven-install-plugin:2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-install-plugin:jar:2.4
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-site-plugin:3.3: Plugin org.apache.maven.plugins:maven-site-plugin:3.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-site-plugin:jar:3.3
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-antrun-plugin:1.3: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-antrun-plugin:jar:1.3
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-assembly-plugin:jar:2.2-beta-5
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-dependency-plugin:2.8: Plugin org.apache.maven.plugins:maven-dependency-plugin:2.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-dependency-plugin:jar:2.8
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-release-plugin:2.5.3: Plugin org.apache.maven.plugins:maven-release-plugin:2.5.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-release-plugin:jar:2.5.3
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/codehaus/mojo/maven-metadata.xml
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-metadata.xml
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-metadata.xml
[WARNING] Checksum validation failed, expected <html><head><script but is b828efd5b45bc776760bceb16cce8d1e from alimaven for http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/codehaus/mojo/maven-metadata.xml
[WARNING] Could not transfer metadata org.apache.maven.plugins/maven-metadata.xml from/to alimaven (http://maven.aliyun.com/nexus/content/repositories/apache-snapshots): TransferFailedException
[WARNING] Could not transfer metadata org.codehaus.mojo/maven-metadata.xml from/to alimaven (http://maven.aliyun.com/nexus/content/repositories/apache-snapshots): TransferFailedException
[WARNING] Failure to transfer org.apache.maven.plugins/maven-metadata.xml from http://maven.aliyun.com/nexus/content/repositories/apache-snapshots was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced. Original error: Could not transfer metadata org.apache.maven.plugins/maven-metadata.xml from/to alimaven (http://maven.aliyun.com/nexus/content/repositories/apache-snapshots): TransferFailedException
[WARNING] Failure to transfer org.codehaus.mojo/maven-metadata.xml from http://maven.aliyun.com/nexus/content/repositories/apache-snapshots was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced. Original error: Could not transfer metadata org.codehaus.mojo/maven-metadata.xml from/to alimaven (http://maven.aliyun.com/nexus/content/repositories/apache-snapshots): TransferFailedException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.138 s
[INFO] Finished at: 2019-05-21T08:54:04+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'appassembler' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/trec1/.m2/repository), alimaven (http://maven.aliyun.com/nexus/content/repositories/apache-snapshots)] -> [Help 1]
org.apache.maven.plugin.prefix.NoPluginFoundForPrefixException: No plugin found for prefix 'appassembler' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/trec1/.m2/repository), alimaven (http://maven.aliyun.com/nexus/content/repositories/apache-snapshots)]
    at org.apache.maven.plugin.prefix.internal.DefaultPluginPrefixResolver.resolve (DefaultPluginPrefixResolver.java:95)
    at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.findPluginForPrefix (MojoDescriptorCreator.java:266)
    at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.getMojoDescriptor (MojoDescriptorCreator.java:220)
    at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments (DefaultLifecycleTaskSegmentCalculator.java:104)
    at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments (DefaultLifecycleTaskSegmentCalculator.java:83)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:89)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by Peilin-Yang** [comment]
```
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/maven/plugins/maven-compiler-plugin/3.7.0/maven-compiler-plugin-3.7.0.pom
```

It seems you are not using the default maven repository. 
(Also, the latest stable Maven version is 3.6.1).
Could you please try to switch to the default repo? The guide is at https://maven.apache.org/guides/mini/guide-multiple-repositories.html

**Comment by lintool** [comment]
I'm assuming this has been resolved? Please reopen otherwise.
