### ISSUE TITLE
Improved processing of WashPost fields?

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#654]
A follow up on: https://github.com/castorini/anserini/issues/646#issuecomment-495253072

> Around 4% of Core18 documents have empty body content (e.g. images) so no term vector is created, but other parsed fields such as title are stored and the document is not skipped over.

It might make sense to try to append the title to the body content so that at least something is indexed?

@emmileaf can you look in the qrels file and see if any of docids are relevant?

**Comment by emmileaf** [comment]
I've had some issues replicating [experiments-core18.md](https://github.com/castorini/anserini/blob/master/docs/experiments-core18.md) and think it might be related to this...seems like body content had more fields appended to it pre-#593?

@r-clancy Do you have any other dependencies on a paragraph-only content field? It looks like term vectors are only created from the contents field (FIELD_BODY), and removing the `title`/`caption`/`kicker` fields alters the index + retrieval results from before.

Perhaps we can append title/caption/etc. back into the content field, but just try to clean up the original parsing issues - thoughts?

Previous:

```
BM25
map                     all     2491
P_30                    all     3580

Index statistics
----------------
documents:             595037
documents (non-empty): 595037
unique terms:          840929
total terms:           317882653
stored fields:
  article_url (indexOption: DOCS, hasVectors: false)
  author (indexOption: DOCS, hasVectors: false)
  contents (indexOption: DOCS_AND_FREQS_AND_POSITIONS, hasVectors: true)
  fullCaption (indexOption: DOCS, hasVectors: false)
  id (indexOption: DOCS, hasVectors: false)
  kicker (indexOption: DOCS, hasVectors: false)
  title (indexOption: DOCS, hasVectors: false)
```
Current:


```
BM25
map                     all     0.2444 
P_30                    all     0.3520 

Index statistics
----------------
documents:             595037
documents (non-empty): 585493
unique terms:          817578
total terms:           304740621
stored fields:
  article_url (indexOption: DOCS, hasVectors: false)
  author (indexOption: DOCS, hasVectors: false)
  contents (indexOption: DOCS_AND_FREQS_AND_POSITIONS, hasVectors: true)
  id (indexOption: DOCS, hasVectors: false)
  title (indexOption: DOCS, hasVectors: false)
```

**Comment by lintool** [comment]
Hrm. So a regression broke, huh? And made results worse?

Yes, I agree... clean up but add those fields back in?

**Comment by r-clancy** [comment]
I'll push a fix tonight adding the fields back and clean-up the original parsing issues.

**Comment by r-clancy** [comment]
@lintool I think this one can be closed now since the `title` (and `kicker`) are added to the body content?
