### ISSUE TITLE
Implement additional relevance feedback models

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#657]
For example, from - York University at TREC 2009: Relevance Feedback Track
https://trec.nist.gov/pubs/trec18/papers/yorku.RF.pdf

Which is one of the comparison conditions in:
https://www.aclweb.org/anthology/papers/D/D18/D18-1478/

**Comment by aalbahem** [comment]
@lintool I was about to open an issue for adding standard relevance feedback models. I actually have implemented Rocchio, RM 3, Distill model and Logistic Log feedback models on top my refactored code.

**Comment by lintool** [comment]
I believe we're still missing results on https://github.com/castorini/anserini/pull/626
... where you were planning on reporting?

Can we get that merged in ASAP?

We're planning on some major upgrades, to Lucene 8 soon, per #586 ...

**Comment by lintool** [comment]
Given the lack of follow up, closing.
