### ISSUE TITLE
PerFieldAnalyzer feature request

### ISSUE THREAD

**Issue by Impavidity** [castorini/anserini#659]
Can we add a feature about multi fields indexing:
- Define which fields will be indexed in an json object
- Define which analyzer will be applied to a specific field. Maybe some of them will not be tokenized.

A configuration file will be used here?

**Comment by lintool** [comment]
👍 to this idea

This would really only be applicable for JSON collection right? For all the standard ones (Robust04, NYT, ClueWeb, etc.) it'll just be hard-coded?

**Comment by lintool** [comment]
I'm thinking about this issue again in the context of #1831

For now, I think we'll punt on this problem and close the issue.

The challenge is that I can't figure out a clean way of specifying per-field configs on the command line... we'd end up developing some awkward DSL, which would be janky.

This can already be done programmatically by implementing a new `Generator` class... so in principle this is already doable today. For now, though, I don't think there's a specifically compelling use case that requires this...
