### ISSUE TITLE
Anserini 0.5.0 release?

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#660]
Thoughts about cutting a 0.5.0 release? @r-clancy @emmileaf @Victor0118 @Peilin-Yang 

We'd use this for OSIRRC. Folds in all the code for SIGIR.

Blocks on #658 though

**Comment by r-clancy** [comment]
Sounds good to me now that #658 is fixed.

:ship:

**Comment by lintool** [comment]
Okay, there's a CAR patch I need to make per #641 - I'll then need to rerun all regressions from scratch cw12 full takes two days, so we're probably talking about mid-week next week for release. FYI in terms of planning for OSIRRC.

**Comment by lintool** [comment]
The other major addition is Anserini -> Solr ingestion right? I'm going to verify that it works... can we get @emmileaf to test also to get independent verification?

**Comment by r-clancy** [comment]
The Solr integration was mainly 0.4.0, I think 0.5.0 just contains some tweaks. Either way, it's good to sanity check it.

**Comment by lintool** [comment]
We should try to fix #515 also? @emmileaf

**Comment by emmileaf** [comment]
Yup, I can send in a PR for #515 for Monday.

**Comment by emmileaf** [comment]
> The other major addition is Anserini -> Solr ingestion right? I'm going to verify that it works... can we get @emmileaf to test also to get independent verification?

For the sanity check- I was able to successfully set up solrini by following the [doc](https://github.com/castorini/anserini/blob/master/docs/solrini.md).

**Comment by lintool** [comment]
Merged in #665 

Release candidate for v0.5.0 https://github.com/castorini/anserini/commit/3545350f3a12bd55a616e41057aa51d3b5cfaed2

Will proceed to run all regressions from scratch and report back.

**Comment by lintool** [comment]
At commit `3545350` (6/3/2019) - the following regressions all successfully completed:

```
[o] nohup python src/main/python/run_regression.py --index --collection disk12 >& log.disk12 &
[o] nohup python src/main/python/run_regression.py --index --collection robust04 >& log.robust04 &
[o] nohup python src/main/python/run_regression.py --index --collection robust05 >& log.robust05 &
[o] nohup python src/main/python/run_regression.py --index --collection core17 >& log.core17 &
[o] nohup python src/main/python/run_regression.py --index --collection core18 >& log.core18 &

[o] nohup python src/main/python/run_regression.py --index --collection wt10g >& log.wt10g &
[o] nohup python src/main/python/run_regression.py --index --collection gov2 >& log.gov2 &

[o] nohup python src/main/python/run_regression.py --index --collection car17v1.5 >& log.car17v1.5 &
[o] nohup python src/main/python/run_regression.py --index --collection car17v2.0 >& log.car17v2.0 &

[o] nohup python src/main/python/run_regression.py --index --collection mb11 >& log.mb11 &
[o] nohup python src/main/python/run_regression.py --index --collection mb13 >& log.mb13 &

[o] nohup python src/main/python/run_regression.py --index --collection cw09b >& log.cw09b &
[o] nohup python src/main/python/run_regression.py --index --collection cw12b13 >& log.cw12b13 &
[o] nohup python src/main/python/run_regression.py --index --collection cw12 >& log.cw12 &

[o] nohup python src/main/python/jdiq2018/run_regression.py --collection disk12 >& jdiq2018.disk12.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection robust04 >& jdiq2018.robust04.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection robust05 >& jdiq2018.robust05.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection wt10g >& jdiq2018.wt10g.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection gov2 >& jdiq2018.gov2.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection cw09b --metrics map ndcg20 err20 >& jdiq2018.cw09b.log &
[o] nohup python src/main/python/jdiq2018/run_regression.py --collection cw12b13 --metrics map ndcg20 err20 >& jdiq2018.cw12b13.log &
```

All commits thereafter is documentation only.

Proceeding to cut v0.5.0 release.

**Comment by lintool** [comment]
Release successful: https://search.maven.org/artifact/io.anserini/anserini/0.5.0/jar

Closing issue.
