### ISSUE TITLE
Run Anserini baselines on AI2 citation prediction task (OpenResearch corpus)

### ISSUE THREAD

**Issue by rodrigonogueira4** [castorini/anserini#669]
The corpus contains 45M academic papers and the task is to predict which papers should be cited in a paper given its title and/or abstract as input.

https://api.semanticscholar.org/corpus/

We should compare our results against the BM25 implementation from this paper (table 2):
https://arxiv.org/pdf/1802.08301.pdf

**Comment by rodrigonogueira4** [comment]
Update: I was able to reproduce the F1@20 from https://arxiv.org/pdf/1802.08301.pdf but not their MRR.

F1@20: 0.059 (Anserini BM25) vs 0.058 (Whoosh BM25, Bhagavatula et. al, 2018)
MRR: 0.148 (Anserini BM25) vs 0.218 (Whoosh BM25, Bhagavatula et. al, 2018)

I will send a PR as soon as I find the reason for the MRR discrepancy.

**Comment by lintool** [comment]
If it isn't too hard, try Whoosh also just to isolate the differences?

**Comment by rodrigonogueira4** [comment]
Good idea, I will try it.

**Comment by rodrigonogueira4** [comment]
One potential cause for the difference in MRR is that we only use the title as query whereas Bhagavatula et. al (2018) mention in appendix D that they use title AND abstract as query. 

They use whoosh's `key_terms_from_text` method to extract terms from the query in order to make it shorter. Does anyone know an equivalent function in Anserini?

**Comment by lintool** [comment]
Nope, although we can use Whoosh to generate the queries, and then throw into Anserini? If that turns out to be the difference, we can reimplement in Java?

**Comment by rodrigonogueira4** [comment]
Sound good!

**Comment by rodrigonogueira4** [comment]
I found the difference: we should not return the same that doc that originated the query. Giving title only as a query to Anserini (as opposed to title+abstract from Bhagavatula et. al), the numbers are:

F1@20: 0.063 (Anserini BM25) vs 0.058 (Whoosh BM25, Bhagavatula et. al, 2018)
MRR: 0.246 (Anserini BM25) vs 0.218 (Whoosh BM25, Bhagavatula et. al, 2018)

**Comment by rodrigonogueira4** [comment]
I created PR to reproduce these results:
https://github.com/castorini/anserini/pull/682

**Comment by rodrigonogueira4** [comment]
Closing this as the BM25 baseline was successfully implemented. Thanks @bazingagin !
