### ISSUE TITLE
Indexing wikidata using Lucene

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#673]
We've already implemented classes for indexing Freebase in Lucene:
https://github.com/castorini/anserini/blob/master/docs/freebase.md

Let's apply to same basic idea to Wikidata?

We probably want to adopt the "node" as a document approach (as opposed to indexing each triple separately). Otherwise we'd bump into the max doc limit in Lucene.

Once this is implemented, it'd be interesting to compare against Jena, Cassandra, etc.

**Comment by lintool** [comment]
hi @r-clancy reviewing our open issues - I believe we've done these experiments already... but they're on another issue somewhere? Can you please provide link?

**Comment by lenyabloko** [comment]
Also compare it to https://github.com/google/sling/blob/master/doc/guide/wikiflow.md#wikidata-import

**Comment by r-clancy** [comment]
@lintool We ran the Jena vs. Lucene experiments on Freebase and Jena was much faster than Lucene for queries, but slower for indexing. Interestingly, the Jena + Lucene combination for full-text search for object literals was also much faster than pure Lucene. The interesting results are in the comments lower down (starting [here](https://github.com/r-clancy/dstlr/issues/3#issuecomment-501551469)), the first runs were done on a noisy `tuna`.

https://github.com/r-clancy/dstlr/issues/3

**Comment by lintool** [comment]
Okay, so this was just benchmarking the old Freebase code, right? So PR needed on Anserini?

I'll going to keep this issue open... might come back and look into Wikidata specifically. I'm still (perhaps irrationally) enamored by the idea of KG directly integrated into Lucene...

**Comment by r-clancy** [comment]
> Okay, so this was just benchmarking the old Freebase code, right? So PR needed on Anserini?

Yeah, this is just using the old code - no PR needed on Anserini.

**Comment by lintool** [comment]
Defunct, I'd say.
