### ISSUE TITLE
Run BM25 baselines on BioASQ

### ISSUE THREAD

**Issue by bazingagin** [castorini/anserini#675]
BioASQ is about biomedical indexing and QA. Data is available here:
http://participants-area.bioasq.org/

We should compare our results against the BM25 implementation from this paper:
https://www.aclweb.org/anthology/D18-1211

**Comment by bazingagin** [comment]
```
map                   	all	0.3503
recip_rank            	all	0.6059
P_20                  	all	0.2190
recall_20             	all	0.4393
recall_100            	all	0.5987
```
Not as high as reported in McDonald et. al, 2018:
```
p@20: 25.5
map: 46.1
```
I've already removed stop words and years>2017 but haven't used krovetz stemmer of Galago either during indexing or during searching. Although I don't think stemmer would cause that big gap. I'm still figuring out if anything else causes the gap.

**Comment by bazingagin** [comment]
Small update:
```
map                   	all	0.4156
recip_rank            	all	0.6429
P_20                  	all	0.2324
recall_20             	all	0.5290
recall_100            	all	0.7162
```
So the previous gap is caused by using a wrong pmid list for filtering out non-included pmids in qrels.
Now will try stemmer and strictly using years <= 2017 for indexing and searching.

**Comment by lintool** [comment]
There doesn't seem to be any (more) interest in this...
