### ISSUE TITLE
Build baselines for TREC 2019 DL Track

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#676]
Official corpus has been released! https://github.com/microsoft/TREC-2019-Deep-Learning

**Comment by lintool** [comment]
@rodrigonogueira4 since the corpus is also Tsv, should we build a specific collection reader into Anserini so that we don't have to convert first to Json?

**Comment by rodrigonogueira4** [comment]
@lintool, It makes sense, but the expanded docs from doc2query would still need to be indexed the json converter, right? We could add an argument for the collection reader pointing to the expansion terms, but that might be confusing to the users.

**Comment by lintool** [comment]
Resolved with #723.

Re: doc2query for DL, let's tackle in a different issue... but augmenting the documents externally would not require any additional code in Anserini itself.
