### ISSUE TITLE
Use title and abstract as query in Open Research corpus

### ISSUE THREAD

**Issue by rodrigonogueira4** [castorini/anserini#684]
Similarly to [Bhagavatula et. al (2018)](https://arxiv.org/pdf/1802.08301.pdf), use the concatenation of title and abstract as a query and use Whoosh's `key_terms_from_text` method to shorten the query.

Also, it would be interesting to experiment with raw title+abstract as a query.

**Comment by bazingagin** [comment]
The output of using title + abstract
map                   	all	0.0626
recip_rank            	all	0.3512
P_20                  	all	0.0811
recall_20             	all	0.1132
recall_1000           	all	0.3628

F1_20					0.0945

**Comment by rodrigonogueira4** [comment]
WOW!!!

This is filtering terms with `key_terms_from_text` or the simple concatenation of raw title and abstract?

**Comment by bazingagin** [comment]
This is the simple concatenation :)

**Comment by bazingagin** [comment]
```
The output of using key terms in both title and abstract
map                   	all	0.0412
recip_rank            	all	0.2521
P_20                  	all	0.0546
recall_20             	all	0.0790
recall_1000           	all	0.2818

F1_20					0.0646
```

**Comment by lintool** [comment]
Interesting. So Bhagavatula et. al (2018) used a technique that experiments demonstrate _not_ to help?
