### ISSUE TITLE
FeatureExtractorCli fails on collection clueweb

### ISSUE THREAD

**Issue by mam10eks** [castorini/anserini#688]
If I pass `-collection clueweb` to `io.anserini.ltr.FeatureExtractorCli` it fails since the condition in line 99 checks for a collection named 'webxml '.

Later, the `WebxmlTopicReader ` package path has changed.

**Comment by lintool** [comment]
@mam10eks the LTR pipeline is known to be completely broken... we've been meaning to fix, but haven't had the opportunity... perhaps you'd be willing to help? PRs welcome...

**Comment by mam10eks** [comment]
@lintool I would happy to help.

Do you mean the class `FeatureExtractorCli` with LTR pipeline or is there more what is broken?

**Comment by lintool** [comment]
Not sure... haven't touched the pipeline in a while. We started working on it a long time ago, and then Solr came out with a LTR framework. It's been on our TODO list for a while to integrate with it.

It'd be awesome to have LTR in Anserini that (1) doesn't have Solr overhead but (2) integrates nicely with Solr when needed.

This would be a big project to take on, but if you're interested, we'd definitely be happy to work with you...

In terms of research, a "classic" LTR baseline for TREC 2019 TREC DL would be great: https://github.com/microsoft/TREC-2019-Deep-Learning

**Comment by mam10eks** [comment]
I am definitely interested.

In order to work in small steps, I would prefer to check the `FeatureExtractorCli` first.

As far as I see, this would enable the usage of the existing FeatureExtractors (which are tested with unittests and hence probably work fine). Based on that it should be easy to train a RankLib model and inject that model into the `io.anserini.rerank.lib.RankLibReranker` for usage in `SearchCollection`.

What do you mean with "classic" LTR baseline?
Any of the LTR-Algorithms implemented in RankLib or the Solr-LTR-Framework?

**Comment by lintool** [comment]
Yup, that's the idea of our LTR pipeline. If you can get it working again, that'd be great.

By "classic" LTR I mean non-neural - i.e., feature engineering - what the current pipeline is doing.
