### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by Ricocotam** [castorini/anserini#704]
Hi,
I'm new here and I'd like to understand how this tool works.
I used ElasticSearch as my retrieval engine for the last months before finding this. It's a great project and I think using the same environment for our experiments leads to more trustworthy results.

I'm looking to some information about how to index documents.
I'm also looking how to reproduce papers like [Task-Oriented Query Reformulation with Reinforcement Learning, Nogueira 2017](https://arxiv.org/abs/1704.04572) since I'm doing the same kind of work. Those kind of works requires an engine to spam queries (up to 200queries/s, or even more if possible).

Thanks for the help,
Cheers

**Comment by lintool** [comment]
If you look at our README, it contains regressions and guides on how to get started with a bunch of document collections.

In particular, what corpus are you working with?

cc @rodrigonogueira4

**Comment by Ricocotam** [comment]
I'm currently working on MS-MARCO so no problem (though I have some issues reproducing regressions but I didn't put much effort in it) but I plan using custom documents from private datasets (though it's not gonna happen super soon). I just like understanding what's going on :)

Actually what I'd like to do is sending queries to the engine with small batches (like 32 queries). Using ES it was done through HTTP REST API but I don't understand how this could be done with anserini. It might not be possible nor the idea of the project.

**Comment by Ricocotam** [comment]
I read a bit more and it was pretty clear finally, just had to take more time reading, thanks for the help :)
