### ISSUE TITLE
Upgrade JDK8 to JDK??

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#710]
#705 is a symptom of JDK8 being EOL'ed. We should upgrade... but to what?

What are the project-wide ramifications? For example, what is the recommended JDK version for Solr/Lucene/Es... and Hadoop/Spark?

**Comment by r-clancy** [comment]
JDK 11 is where we'd want to move to - it's the default version in Ubuntu 18+ currently.

Plan of action: spin up an Azure VM with Java 11 installed, cut a branch for JDK 11, and see what breaks.

**Comment by r-clancy** [comment]
The [java-11](https://github.com/castorini/anserini/tree/java-11) branch seems to compile fine on my machine (and Travis) - I'm able to reproduce a couple of the `robust04` results on my laptop.

@lintool maybe we can get Java 11 installed on `tuna` (keeping Java 8 as the default version) and run the regressions there?

**Comment by lintool** [comment]
Let's leave tuna alone and run regressions on the new machine?

Additional questions - how does JDK 11 play with Solr and Spark and ES? And pyjnius?

**Comment by r-clancy** [comment]
Sounds good...

I did a quick search, everything should work fine with JDK 11 (will need to be tested to confirm):
- Solr should be fine - https://lucene.apache.org/solr/8_0_0/SYSTEM_REQUIREMENTS.html
- ES should be fine - https://www.elastic.co/support/matrix#matrix_jvm
- Spark should be fine - https://spark.apache.org/docs/latest/

As for pyjnius, @Victor0118 said he didn't come across any threads online with issues.

**Comment by lintool** [comment]
Upgraded to JDK11 with #743.
