### ISSUE TITLE
Further hiding pyjnius details

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#713]
Currently we do this:

```
import sys
sys.path += ['src/main/python']
from pyjnius_setup import configure_classpath
configure_classpath()

from jnius import autoclass
JString = autoclass('java.lang.String')
JSearcher = autoclass('io.anserini.search.SimpleSearcher')

searcher = JSearcher(JString('lucene-index.robust04.pos+docvectors+rawdocs'))
hits = searcher.search(JString('hubble space telescope'))

# the docid of the 1st hit
hits[0].docid
```

Can we try to hide pyjnius completely? I.e., just have a `pyserini` module that wraps everything? So we wouldn't need to mess with `autoclass`, etc.

Something like:

```
import sys
sys.path += ['src/main/python']

import pyserini
pyserini.configure()

# something like this?
searcher = pyserini.create_searcher('lucene-index.robust04.pos+docvectors+rawdocs')
hits = searcher.search('hubble space telescope')

...
```

Let's see if we can get rid of all the String/JString translations and make it "magic"?

Thoughts?

**Comment by lintool** [comment]
@Victor0118 Can you chime in here? This will impact BERTserini?

@rodrigonogueira4 @bazingagin Can you chime in also? I believe you need multi-threaded searcher for large volume datasets like OpenResearch. I'm also assuming you want to do the thread pooling on the Python end to integrate with downstream consumers (DL). Do you want to mock up what you want the interface to look like?

This will require some thinking: typically, in Java, you only want one `IndexReader`, but create multiple `IndexSearcher`s from it (one per thread)...

**Comment by emmileaf** [comment]
That makes sense... having a file as `src/main/python/pyserini.py` that will wrap all the autoclass usages, kind of like what we do here?
https://github.com/castorini/anserini/blob/e2d1f7b7ae8ef3c6c8e7a361b7e42fa069ba46ae/src/main/python/io/anserini/collection/pyjnius_utils.py#L1-L52

If we build a searcher interface that's more complicated than just exposing 
`JSearcher = autoclass('io.anserini.search.SimpleSearcher')`, it could probably go under `src/main/python/io/anserini/search` similar to the collections wrapper setup?

**Comment by lintool** [comment]
Closing issue for now.
