### ISSUE TITLE
Abstraction for Search Functionality

### ISSUE THREAD

**Issue by r-clancy** [castorini/anserini#718]
Currently, the search code depends on Lucene internals. However, we can also index documents in Solr and Elasticsearch. This is useful for larger collections such as `cw12` in order to improve performance of queries, get access to search interfaces, etc.

Solr and Elasticsearch both expose the document scores (see below for Solr) required in order to do our search experiments - the `bm25` parameters set for `solrini` get -very- close to the document scores returned by the same Lucene queries (this was tested across different Lucene and Solr versions, they should match). Further, both of these systems support native Lucene queries.

We should look at implementing some abstractions for the search functionality in Anserini that exposes the ID, text, and score of a document. This way, we can perform search experiments regardless of which back-end (Lucene, Solr, ES) is being used. I'm not too familiar with the search code in Anserini, so I'm not sure how big of a can of worms this is.

![image](https://user-images.githubusercontent.com/1282383/59468534-4dec8080-8e00-11e9-9449-e1dcf9fbb20f.png)

**Comment by lintool** [comment]
hi @r-clancy - I spoke to @emmileaf about getting started on this.

The end goal is that ad hoc retrieval against ES and Solr backends give the same results as direct local Lucene indexes, right?

I suggest creating new classes `SearchSolr` and `SearchElastic` instead of overloading `SearchCollection`, which is actually in need of refactoring...

**Comment by r-clancy** [comment]
Yeah, the goal would be to get the same results regardless of the back-end, @lintool. Solrini's BM25 params match Anserini's and I'm making changes now to ensure Elastirini's BM25 have the same parameters.

Creating these new classes be in favor of abstracting out the required components (doc object, sorted list of docs by score, etc.), right? If so, would it make sense to define an interface for search and have a `SearchLucene`, `SearchSolr`, `SearchElastic`, etc. implement this?

**Comment by lintool** [comment]
>  If so, would it make sense to define an interface for search and have a `SearchLucene`, `SearchSolr`, `SearchElastic`, etc. implement this?

Ideally, yes... but let's do this incrementally, maybe in a second pass refactoring?

Issue is that `SearchCollection` has a lot of features that we probably don't want to include in an interface, and injecting an interface will be very invasive.. and considering that all our regressions depend on this, might break a lot of things...

**Comment by r-clancy** [comment]
Closing as this was implemented in https://github.com/castorini/anserini/pull/746 and https://github.com/castorini/anserini/pull/785.
