### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project anserini: Fatal error compiling: invalid target release: 11

### ISSUE THREAD

**Issue by rajarsheem** [castorini/anserini#748]
how to resolve this issue?

**Comment by emmileaf** [comment]
Anserini was recently upgraded to Java 11 (commit [`17b702d`](https://github.com/castorini/anserini/commit/17b702d9c3c0971e04eb8386ab83bf2fb2630714)). We recommend using Java 11 if you would like to compile the latest commits, but to compile with Java 8, you can also edit/revert the following lines in `pom.xml`: https://github.com/castorini/anserini/blob/33d630cec4d07e926a022731046a0553aa928fb5/pom.xml#L81-L84

**Comment by rajarsheem** [comment]
Yeah, I solved it already. Forgot to close the issue. Thanks @emmileaf .

**Comment by yongbowin** [comment]
The same error occurs when my executing, modify `11` to your version perform well. Thx.

**Comment by rajarsheem** [comment]
@yongbowin I instead updated my Java to 11 ;)

**Comment by lintool** [comment]
What error are you getting? Have you trying searching online for potential solutions?

**Comment by techylife** [comment]
It is actually giving these much warnings and errors. 
![image](https://user-images.githubusercontent.com/59837849/110493785-f4220300-8118-11eb-9e46-a690a1553da3.png)

**Comment by lintool** [comment]
Unfortunately, none of our team has any experience with Java 15, and your error trace doesn't seem to offer much info...

**Comment by techylife** [comment]
ok

**Comment by bajeelapv** [comment]
Same issue for me also. I am using java 11

**Comment by HashirLabs** [comment]
For me it was working till jdk 15, i just updated it to jdk 16, and started getting the compilation error in intellij

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project XXX: Fatal error compiling

**Comment by lintool** [comment]
Unfortunately, Anserini is currently only supported on Java 11.

**Comment by kasuohei** [comment]
The same error occurring for me. I am using Java 17. But this solution is not working for me. Would be much thankful if got some help 🙏

**Comment by nikunj23190** [comment]
I update my target release from 11 to 8 and it worked,

**Comment by Bhrema** [comment]
Hey guys, recently my project had the same error. Just go to file -> settings..., then look for maven, and set the right version. Mine, for some reason changed to 3.8.something, and i reset to 3.6.3

**Comment by petertogara** [comment]
For those running on java 11+, if you generate your project using [http://start.spring.io/], then you need to check the java version used when generating the POM. 
```
    <properties>
        <java.version>11</java.version>
    </properties>
```
    Alternatively you need to add the the maven version and source specification
 ```
    <source>11</source> 
     <target>11</target> 
```
Guaranteed, it should work

**Comment by Undapalli** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile)

**Comment by minaz99** [comment]
@Undapalli did you find a fix for it ?

**Comment by justinmchase** [comment]
I've added this to the build plugins:

```
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>3.11.0</version>
              <configuration>
                <source>11</source>
                <target>11</target>
              </configuration>
            </plugin>
```
and 

```
 <properties>
        <java.version>11</java.version>
    </properties>
```

and the error still perpetually happens. Not sure what else is needed.

**Comment by lintool** [comment]
Can you pull latest from master? We've recently upgraded to JDK 21.

**Comment by David-Inkheart** [comment]
JDK 21 has similar error when deploed to Heroku.... 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project Manager: Fatal error compiling: invalid target release: 21 -> [Help 1]

Please, any help will be appreciated.

**Comment by lintool** [comment]
hi @David-Inkheart can you please elaborate? Why are you trying to deploy on Heroku?

Perhaps this is relevant? https://codejava.net/heroku/fixed-maven-error-invalid-target-release#:~:text=Fix%20%E2%80%9Cinvalid%20target%20release%E2%80%9D%20error%20by%20changing%20JDK%20version%20on%20Heroku&text=And%20run%20git%20push%20heroku,and%20get%20your%20app%20deployed.

**Comment by moosakhan2** [comment]
<img width="1470" alt="Screenshot 2024-06-02 at 1 32 29 AM" src="https://github.com/castorini/anserini/assets/170849681/5d46cb92-c153-459c-9136-f99758742d76">
<img width="1470" alt="Screenshot 2024-06-02 at 1 33 11 AM" src="https://github.com/castorini/anserini/assets/170849681/4d5ff790-a962-4c6c-aa82-1e08e31dcac0">


Getting an "invalid release target error".

For context I doing all this in Vs code and using bash shell in terminal, 

the command mvn clean package isnt working and returns me the above error.

**Comment by lintool** [comment]
As indicated in the README, we're on JDK 21 now.

<img width="834" alt="Screen Shot 2024-06-02 at 7 30 48 AM" src="https://github.com/castorini/anserini/assets/313837/26c48a84-7229-4993-b606-313715c21bd3">

Please follow our installation instructions.

**Comment by ilamaranm** [comment]
I am getting this same error on my pipeline execution...I m using java 11. I have attached my pom.xml structure and java version
Pls help me to sort out this
<properties>
     <java.version>11</java.version>
  </properties>	
 	<build>
        <plugins>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.2.0</version> 
                <configuration>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version> 
                <configuration>
                    <source>11</source>
                    <target>11</target>
                    <testSource>11</testSource>
          			<testTarget>11</testTarget>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            
            <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>3.0.0-M5</version>
            <configuration>
                <suiteXmlFiles>
                    <suiteXmlFile>src/test/resources/testng.xml</suiteXmlFile> 
                </suiteXmlFiles>
            </configuration>
        	</plugin>
        </plugins>
    </build>

C:\Users>java -version
java version "11.0.23" 2024-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.23+7-LTS-222)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.23+7-LTS-222, mixed mode)

C:\Users>javac -version
javac 11.0.23

C:\Users>mvn -v
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\apache-maven-3.9.9
Java version: 11.0.23, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11
Default locale: en_IN, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

**Comment by lintool** [comment]
As it clearly states in the second paragraph in our main repo README:

<img width="826" alt="Screen Shot 2024-08-28 at 8 02 29 AM" src="https://github.com/user-attachments/assets/650d42b0-f993-4493-86fa-bc507aa512dd">

Please upgrade to JDK 21.
