### ISSUE TITLE
Release v0.6.0

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#751]
Should we do a v0.6.0 release? Major changes are Lucene8 upgrade and move to JDK11.

Thoughts? @emmileaf @r-clancy @zeynepakkalyoncu @Victor0118 @rodrigonogueira4

**Comment by rodrigonogueira4** [comment]
Looks good to me, no deadlines in the next month, right?

**Comment by zeynepakkalyoncu** [comment]
Sounds good. Are we aiming for before or after the TREC DL deadline? Also, I think it would be a good idea to upgrade to JDK11 on our own servers to adapt our other repos?

**Comment by lintool** [comment]
> Sounds good. Are we aiming for before or after the TREC DL deadline? Also, I think it would be a good idea to upgrade to JDK11 on our own servers to adapt our other repos?

I was hoping to cut the release soonish... maybe this week?

I forgot to mention, I've rerun _all_ regressions from scratch (including `cw12`) on JDK11 on `damiano` and everything checks out.

Yes we should upgrade all our servers to JDK11, but I think that's an orthogonal issue? This is tuna and the GPU machines?

**Comment by zeynepakkalyoncu** [comment]
Sure!

Yeah, I only wanted to mention that issue as a reminder. I see it's already taken care of.

**Comment by lintool** [comment]
FYI - after merging in https://github.com/castorini/anserini/pull/789 - I'm planning on release v0.6.0

**Comment by lintool** [comment]
Just released [v0.6.0](https://search.maven.org/artifact/io.anserini/anserini/0.6.0/jar) [[Release Notes](https://github.com/castorini/anserini/blob/master/docs/release-notes/release-notes-v0.6.0.md)]!  🎉 

Thanks to contributions from:

+ Emily Wang ([@emmileaf](https://github.com/emmileaf))
+ Ryan Clancy ([@r-clancy](https://github.com/r-clancy))
+ Adrien Grand ([@jpountz](https://github.com/jpountz))
+ Chris Kamphuis ([@Chriskamphuis](https://github.com/Chriskamphuis))
+ Zhiying Jiang ([@bazingagin](https://github.com/bazingagin))
+ Rodrigo Nogueira ([@rodrigonogueira4](https://github.com/rodrigonogueira4))
+ Ronak Pradeep ([@ronakice](https://github.com/ronakice))
+ Adrien Pouyet ([@Ricocotam](https://github.com/Ricocotam))
+ Horatiu Lazu ([@MathBunny](https://github.com/MathBunny))
+ Matt Yang ([@justram](https://github.com/justram))
+ Victor Yang ([@Victor0118](https://github.com/Victor0118))
+ Charles Wu ([@charW](https://github.com/charW))
+ Zhaohao Zeng ([@matthew-z](https://github.com/matthew-z))
