### ISSUE TITLE
Open Research: Create human evaluation interface

### ISSUE THREAD

**Issue by bazingagin** [castorini/anserini#755]
1. create an interface that enables people to enter key words as queries
2. return a list of citations output by Anserini + BM25 (+BERT reranker)
3. interleave the result with Google Scholar, MS Academic, and Semantic Scholar's and enable people to "like" or "dislike" the returned results

**Comment by rodrigonogueira4** [comment]
Closing this and adding it to Fourdrinier. @bazingagin, you should be added to that repo in a minute.

**Comment by lenyabloko** [comment]
Hi, Can you share this implementation for my research purposes? I will use and report results in my article. Thank you.

**Comment by rodrigonogueira4** [comment]
Sorry, we end up not running this experiment, so we don't have any code.
