### ISSUE TITLE
Javadoc: Unable to find javadoc command when JAVA_HOME is set

### ISSUE THREAD

**Issue by tuzhucheng** [castorini/anserini#784]
I'm getting the following error while building anserini using `mvn clean package appassembler:assemble`:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.543 s
[INFO] Finished at: 2019-08-15T20:01:00Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar (attach-javadocs) on project anserini: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
```

JAVA_HOME is set and I've added the `bin` directory under it to `PATH` as well.

```
$ echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-amd64
```

Using maven 3.6.0, Java 11.0.3, Ubuntu 18.04.1.

**Comment by tuzhucheng** [comment]
A workaround is adding `-Dmaven.javadoc.skip=true verify` to the `mvn` command.

**Comment by tuzhucheng** [comment]
Turns out `javadoc` is not installed. I'll check my environment.

**Comment by tuzhucheng** [comment]
My bad, turns out I was setting up a new environment and installed JRE instead of JDK.

**Comment by namespace-Pt** [comment]
How do you fix it? I came across the same issue.

**Comment by lintool** [comment]
Setting `JAVA_HOME` is OS and environment specific. You should be able to find an answer via web search.
