### ISSUE TITLE
Use Lucene Similarity BM25 scoring instead of reimplementing custom scoring function

### ISSUE THREAD

**Issue by MathBunny** [castorini/anserini#798]
In `BM25FeatureExtractor.java`, the feature extractor computes BM25 score according to Lucene 5.3 documentation, however to retain consistency with master it'd be better to reuse Lucene similarity functionality instead in case of changes down the road.

**Comment by lintool** [comment]
Let's get this in a PR before a broader PR on the pipeline.

The correctness of the implementation can be easily verified by making you we get the same scores as those coming out of Lucene directly, i.e., as in https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md

**Comment by lintool** [comment]
Not relevant anymore given new work on LTR pipeline.
