### ISSUE TITLE
Indexing Core17 with 1 thread produces multiple leaves. 

### ISSUE THREAD

**Issue by Chriskamphuis** [castorini/anserini#808]
When I index `core17` with 1 thread `IndexReader.leaves()` produces two leaves. 
For `core18` and `robust04`, it correctly produces one leaf.

[Here](https://github.com/castorini/anserini/blob/master/docs/common-indexing-options.md) the indexing options describe that when using 1 thread the unique terms are only available when indexing with one thread. This is at the moment not possible for `core17`.

**Comment by lintool** [comment]
Try `-optimize` https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexArgs.java#L56

It'll force merge the index down to a single segment... that should do it.

**Comment by Chriskamphuis** [comment]
Thank you this solves it!
