### ISSUE TITLE
Ingestion of MS MARCO into Solr and ES

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#811]
Figure out how to ingest MS MARCO passage/doc collections into Solr and Elasticsearch. Update documentation as needed.

**Comment by apoorvp16** [comment]
Indexing of both MS MARCO doc and passage collections works well. But getting an issue with BM 25 retrieval

**Comment by lintool** [comment]
MS MARCO passage works now, part of #907

**Comment by lintool** [comment]
Originally planned to be part of v0.7.0 release - features mostly there, but not 100% complete. Punting for now.

**Comment by lintool** [comment]
With #1030 we now have a consistent set of regressions for `robust04`, `core18`, and `msmarco-passage`.
