### ISSUE TITLE
Update Solrini documentation for Washington Post

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#813]
@x389liu if you've successfully ingested Washington Post in Solr, can you add some documentation to that effect at the bottom of: https://github.com/castorini/anserini/blob/master/docs/solrini.md

Something like, we've verified that these instructions can be straightforwardly adapted to work with Washington Post based on instructions at https://github.com/castorini/anserini/blob/master/docs/regressions-core18.md

**Comment by x389liu** [comment]
PR https://github.com/castorini/anserini/pull/817 created.

**Comment by lintool** [comment]
Closing, as #817 has been merged.
