### ISSUE TITLE
Add integration test for Solrini

### ISSUE THREAD

**Issue by r-clancy** [castorini/anserini#815]
We need to create an end-to-end integration testing script written in Python that: sets up Solr, indexes a number of collections, runs search and outputs the trec_eval results, and tears down Solr.

The name of the collections to run on should be configurable (the `generator` and `collection` can be fixed like [here](https://github.com/osirrc/anserini-docker/blob/master/index)) and we should be able to either specify an existing Solr server (i.e., via a `--solr` parameter) or setup/teardown a new one (as above) based on the Solrini instructions.

**Comment by lintool** [comment]
Ref #922

**Comment by lintool** [comment]
Closed by #922
