### ISSUE TITLE
Add integation test for Elastirini

### ISSUE THREAD

**Issue by r-clancy** [castorini/anserini#819]
We need to create an end-to-end integration testing script written in Python that: sets up Solr, indexes a number of collections, runs search and outputs the trec_eval results, and tears down Solr.

The name of the collections to run on should be configurable (the `generator` and `collection` can be fixed like [here](https://github.com/osirrc/anserini-docker/blob/master/index)) and we should be able to either specify an existing Solr server (i.e., via a `--solr` parameter) or setup/teardown a new one (as above) based on the Solrini instructions.

**Comment by lintool** [comment]
For this, we need a non-Docker solution to starting up ES. Once we've figured this out, docs [here](https://github.com/castorini/anserini/blob/master/docs/elastirini.md) should be updated to provide an alternative.

**Comment by lintool** [comment]
Might be useful: https://www.elastic.co/guide/en/elasticsearch/reference/current/integration-tests.html

**Comment by lintool** [comment]
Closed by #911
