### ISSUE TITLE
What is the problem?

### ISSUE THREAD

**Issue by demeiyan** [castorini/anserini#820]
I have encountered an error when I run the command "mvn  clean package appassembler:assemble" after I clone the repo.

![image](https://user-images.githubusercontent.com/12872156/66366198-3a25e500-e9c2-11e9-9720-17c94aef046c.png)

**Comment by Peilin-Yang** [comment]
I guess this is because of the dependency versions 

From REAME.md:
```
Anserini was recently upgraded to Java 11 at commit 17b702d (7/11/2019) from Java 8. Maven 3.3+ is also required.
```

**Comment by demeiyan** [comment]
ok,thanks,I will try old version.

**Comment by demeiyan** [comment]
Hi, the problems is Apache Maven Compiler Plugin's configuration in pom.xml .
![image](https://user-images.githubusercontent.com/12872156/66381723-71a98700-e9ec-11e9-88fa-f63135b68166.png)

**Comment by lintool** [comment]
@demeiyan did you roll back to commit `17b702d`?

**Comment by demeiyan** [comment]
@Peilin-Yang @lintool  ok,thanks ! I have solved the above problems. I need Anserini Retriever , mainly retrieve top-k passage from passage collection given a question (I have passage collection) , like [https://arxiv.org/pdf/1902.01718.pdf](End-to-End Open-Domain Question Answering with BERTserini) . I try [https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md](BM25 Baselines on MS MARCO (Passage)) , but always failed when download  msmarco-passage. Is there any better guide I can try? Thanks!

**Comment by lintool** [comment]
What do you mean? This seems to work fine for me...

```
wget https://msmarco.blob.core.windows.net/msmarcoranking/collectionandqueries.tar.gz
```

GWF issue?

**Comment by demeiyan** [comment]
yes! maybe GWF, I need better IR experiments I can try to use anserini and then I can apply to my dataset.

**Comment by lintool** [comment]
@demeiyan I don't understand what you are trying to ask... Anserini should work for any of the collections listed in the README.

**Comment by lintool** [comment]
Hearing no further follow-up, closing issue.
