### ISSUE TITLE
Questions about parameters of your Results 

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/anserini#824]
Dear Sir 
Thank you for you nice work 
I would like to compare your results with mine using different Lucene Tool
Can you tell me which parameters you use to get these MAP results in BM25 ( without additions )
which b value you used ? 
which k value you used ? 
what are the TokenFilters used for indexing and retrival ?
Regards

**Comment by lintool** [comment]
Which results are you talking about in particular?

See default search parameters here:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SearchArgs.java

See indexing implementation here: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexCollection.java

**Comment by ABDULAZIZALQATAN** [comment]
Thank you sir 
I checked it >>> is this correct or did I miss something? >>> 
Standard Tokenizer - B = 0.4 - K = 0.9 - porterStem - Stop TokenFilter 
I tried to rerun the experiment with these filters but the results were different

**Comment by ABDULAZIZALQATAN** [comment]
Thank you sir
I checked it >>> is this correct or did I miss something? >>>
Standard Tokenizer - BM25 - B = 0.4 - K = 0.9 - porterStem - Stop TokenFilter
I tried to rerun the experiment with these filters but the results were different

**Comment by lintool** [comment]
What do you mean? Please provide more details - which collection, exactly what code, etc.?

There's more to an end-to-end experiment than the configuration you mentioned above.

**Comment by ABDULAZIZALQATAN** [comment]
Dear Sir 
Thanks for your cooperation and support
Collection : AQUAINT and CommonCore 2017
Tool :  [Lucene8IR](https://github.com/lucene4ir/lucene4ir8)
This tools uses XML Files as input 
we ran many experiments on AQUAINT to get your results 
![Aquaaint-B0 4Map Comparison](https://user-images.githubusercontent.com/47518534/66863985-19462c80-ef8c-11e9-8fdc-f23818aa1625.jpg)

The best file we have until now is this 
![1](https://user-images.githubusercontent.com/47518534/66863942-ffa4e500-ef8b-11e9-8aa8-d441ae839d6b.jpg)

The indexing for AQUAINT is different between Lucene8IR and Anserini >> these are LUKE results for both
![Anserini - AQUAINT INDEX](https://user-images.githubusercontent.com/47518534/66864063-4692da80-ef8c-11e9-8eec-265aad452d99.jpg)
![Lucene8IR-AQUAINT INDEX](https://user-images.githubusercontent.com/47518534/66864071-4a266180-ef8c-11e9-9906-8524c6150e75.jpg)

I think that the difference in indexes caused this slight difference in MAP values 

As a result for all of this , Your main token filters are : 
1- Tokenizer : Standard 
2- Token Filters : Stop (remove stop words ) - lower ( for porterStem ) - porter 
is this right ? or do you have extra filters I did not notice 

Thanks sir and I hope my little experiments to compare between both tools help other perople even you

**Comment by lintool** [comment]
There are probably minor differences in the tokenization pipeline, such as XML cleaning, etc. You'll have to take a look at https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/generator/LuceneDocumentGenerator.java for the actual details.

However, your scores are close enough that I don't think there's anything interesting here.

**Comment by ABDULAZIZALQATAN** [comment]
Thanks sir 
I made a full comparison for B = 0.1 to B = 0.9 --- K = 1.2 not 0.9 and I had these results 

![AnseriniVSLucene8IR](https://user-images.githubusercontent.com/47518534/66880001-d0589d00-efb8-11e9-88b9-15497ddf1a47.jpg)

**Comment by lintool** [comment]
See no further follow-up, closing issue.
