### ISSUE TITLE
Switching from pyjnius to py4j

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#833]
There doesn't seem to be much activity around the pyjnius project re: features, maintenance, etc.
Recently, we had breakage #832 - and similar issues are going to crop up more and more frequently.

Should we consider switching to [py4j](https://www.py4j.org/)? One reason we didn't adopt it was that it required starting up your own JVM.

It's less likely that py4j will become abandoned... for one, it has a huge customer in Spark, in that py4j lies at the heart of PySpark.

FWIW, it appears that PySpark starts up it own JVM automatically - https://github.com/apache/spark/blob/master/python/pyspark/java_gateway.py

**Comment by Chriskamphuis** [comment]
I think requiring starting up your own JVM is undesirable, however Pyjnius can not be relied on and Pyserini should not be dependent on it. So, py4j would be my preference.

**Comment by lintool** [comment]
@Chriskamphuis there's also performance overhead to consider, since py4j communicates via sockets...

**Comment by Victor0118** [comment]
I prefer py4j for the reasons above.

**Comment by arjenpdevries** [comment]
As long as it is only calling functions that operate on large sets, overhead costs are amortized.

**Comment by lintool** [comment]
We seem to have a reasonable resolution for #832. I think pyserini remains fine, but we'll definitely want to keep our options open...
