### ISSUE TITLE
Exception when importing pyserini

### ISSUE THREAD

**Issue by tingkai-zhang** [castorini/anserini#843]
Hi I follow the instructions of pyserini to set up the environment and run the example script.
The exception I have when running teh example pyserini script copied from readme is:
```
Exception                                 Traceback (most recent call last)
<ipython-input-18-fed52f7bef12> in <module>()
----> 1 from pyserini.search import pysearch
      2 
      3 searcher = pysearch.SimpleSearcher('lucene-index.robust04.pos+docvectors+rawdocs')
      4 
      5 # To additionally configure search options, such as using BM25+RM3:

2 frames
/content/anserini/src/main/python/pyserini/setup.py in configure_classpath(anserini_root)
     35                                    'anserini-*-fatjar.jar'))
     36     if not paths:
---> 37         raise Exception('No matching jar file found in target')
     38 
     39     latest = max(paths, key=os.path.getctime)

Exception: No matching jar file found in target
```
I installed and ran it on colab, python 3.

**Comment by lintool** [comment]
Did you follow the instructions to run and build the jar? https://github.com/castorini/anserini#getting-started

**Comment by tingkai-zhang** [comment]
> Did you follow the instructions to run and build the jar? https://github.com/castorini/anserini#getting-started

I follow the demo colab notebook to set up the environment.
To reproduce it, I have create a notebook here.
https://colab.research.google.com/drive/1gAtadmMw-4hAsYM-YmM-q2VJR6vnTquT

**Comment by lintool** [comment]
Check out: https://colab.research.google.com/drive/1GOCyWyYW_fwJMKy5FVWdYHEC2IlvpqZN

Reopen issue if you're still having problems.
