### ISSUE TITLE
how to read the old index file with the latest pyserini?

### ISSUE THREAD

**Issue by Huhao123** [castorini/anserini#931]
i installed the latest version of  pyserini. The program tells me that i forget to add lucene-backward-codecs.jar when i read the old index file, which was indexed from lucene 7.6. The error code is as follows:
`JavaException                             Traceback (most recent call last)
<ipython-input-3-2ec28dcbe032> in <module>
     14                 print('{} queries completed'.format(cnt))
     15 
---> 16 searcher = pysearch.SimpleSearcher(base_data_path+'/index/index-gov2')
     17 # topic = pysearch.get_topics('robust04')
     18 print('test 1 ')

~/anaconda3/envs/python36/lib/python3.6/site-packages/pyserini/search/pysearch.py in __init__(self, index_dir)
     35 
     36     def __init__(self, index_dir):
---> 37         self.object = JSearcher(JString(index_dir))
     38 
     39     def search(self, q, k=10, t=-1):

jnius/jnius_export_class.pxi in jnius.JavaClass.__init__()

jnius/jnius_export_class.pxi in jnius.JavaClass.call_constructor()

jnius/jnius_utils.pxi in jnius.check_exception()

JavaException: JVM exception occurred: Could not load codec 'Lucene70'.  Did you forget to add lucene-backward-codecs.jar?`

So i add the dependence of lucene-backward-codecs.jar to the pom.xml and repackage the anserini.
But the error persists. 
So i wonder how to read the old index file with the latest pyserini?

**Comment by lintool** [comment]
Hi @Huhao123 - unfortunately, we've moved beyond Lucene 7.6 since June 2019: https://github.com/castorini/anserini/commit/75e36f97f7037d1ceb20fa9c91582eac5e974131

You'll have to rebuild the index.

**Comment by Huhao123** [comment]
OK. Thank you!
