### ISSUE TITLE
Modularize

### ISSUE THREAD

**Issue by heinrichreimer** [castorini/anserini#940]
The Anserini framework currently has a huge list of dependencies (and transitive dependencies).
Especially the dependency on Lucene and Elasticsearch is likely to cause version conflicts, as Elasticsearch requires the Java library version to match the cluster's version.
That way it is currently not possible to use Anserini and own Elasticsearch Java API applications on the same classpath.
Modularizing the Anserini framework to decoupled libraries could prevent such version conflicts.

**Comment by lintool** [comment]
Hi @heinrichreimer, thanks for the comment!

Yes, in principle I agree this would be a good thing to do... however, realistically the priority is rather low, at least in the short term, especially with SIGIR deadline etc. coming up.

However, a near term reasonable task might be to prune the pom of any dependencies that aren't absolutely necessary...

**Comment by heinrichreimer** [comment]
Thanks for your honest opinion. I will think about possibilities of modularization in the meantime and come back to you with ideas and feedback.
The general idea would be to have a base "model" on which search, LTR etc. are built.

However, pruning dependencies is a very good start!
