### ISSUE TITLE
Reproducing "The Simplest Thing That Can Possibly Work:Pseudo-Relevance Feedback Using Text Classification"

### ISSUE THREAD

**Issue by lambdaofgod** [castorini/anserini#958]
How to run rerank.py?
The paper directs to commit from 19.01.2019, but I can't find any mention of its title in the whole project.

When I try to run rerank.py
`python rerank.py --config config.ccrf.core18.json `
I get 
```
Traceback (most recent call last):
  File "rerank.py", line 150, in <module>
    assert os.path.isdir(working_directory)
AssertionError
```

Other than that, how can I get vocabulary size of your BM25 representations? Because what I've got by running BM25 on my data has huge vocabulary, which I don't think will work good with default LogisticRegression (in the paper there is at most 60 examples, and the vocabulary I get has couple hundred thousands of items)

**Comment by lintool** [comment]
Hi @lambdaofgod - check out https://github.com/castorini/anserini/blob/master/docs/runbook-ecir2019-ccrf.md

The paper you referenced uses the same code base.

**Comment by lintool** [comment]
> Other than that, how can I get vocabulary size of your BM25 representations? Because what I've got by running BM25 on my data has huge vocabulary, which I don't think will work good with default LogisticRegression (in the paper there is at most 60 examples, and the vocabulary I get has couple hundred thousands of items)

Also, not sure I understand this point... yes, I was using the entire vocab space as features to LR in the referenced paper.

> in the paper there is at most 60 examples

No, that's the number of _topics_. Classification is performed on a per-topic basis.

**Comment by lambdaofgod** [comment]
> No, that's the number of topics. Classification is performed on a per-topic basis.
I'm confused. Could you explain that further? I don't understand the concept of topic in this paper.
In the paper you didn't explicitly define classification target.
What I understood is: per each query you trained model on positive examples (relevant articles, top k from 100 articles retrieved by BM25) and negative examples (last k from 100 articles retrieved by BM25).

**Comment by lintool** [comment]
A "topic" correspond to a query in TREC parlance. Your understanding is basically correct.

**Comment by lambdaofgod** [comment]
Thanks. Can you tell me what is the vocabulary size for these datasets? Does your standard pipeline use stemming by default?

I'd like to run your code myself but it would take a couple of weeks to get the TREC datasets...

**Comment by lintool** [comment]
I only have the number for Robust04 off hand: there are 923,436 unique terms in the collection.
