### ISSUE TITLE
Is the document length used in language model accurate?

### ISSUE THREAD

**Issue by nsndimt** [castorini/anserini#959]
Anserini has BM25 and AccurateBM25, two implementations of BM25. I think the word  "accurate" meaning the implementation uses uncompressed document length during the computation. 
If so, which kind of document length do the other similarities,  like qld_mu,  use?  Compressed or Uncompressed?  And can we also provide both versions for all other similarities?

**Comment by lintool** [comment]
hi @nsndimt - take a look at this: https://cs.uwaterloo.ca/~jimmylin/publications/Kamphuis_etal_ECIR2020_preprint.pdf

If you want to use accurate lengths in BM25, use this `-bm25.accurate`:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SearchArgs.java#L125

@Chriskamphuis can provide more details if you wish to replicate above ECIR paper.

No, we haven't done the same for QL.

If you wish to extract the accurate doclengths, use:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/util/ExtractDocumentLengths.java

Note that this requires indexing the docvector.

Hope this helps!

**Comment by lintool** [comment]
Not having heard any follow up, closing issue. Please re-open otherwise.
