### ISSUE TITLE
Index using `JsonCollection` fails when JSON document has no `contents` field.

### ISSUE THREAD

**Issue by bevankoopman** [castorini/anserini#961]
When indexing using JsonCollection, the indexer fails with nondescript NullPointer if the source document does not contain a field with name `contents`.

**Comment by nikhilro** [comment]
Hey @bevankoopman, thanks for creating an issue for this. I'll take a look and send a fix

**Comment by lintool** [comment]
Hi @bevankoopman thanks for reporting this issue. #964 should take care of it. please reopen issue if otherwise.

**Comment by bevankoopman** [comment]
Oh, cool. Thanks. Sorry, didn't see that other issue.
