### ISSUE TITLE
Ingest scientific abstracts into Solr

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#971]
We have a bunch of hydrology bibtex entries that have been formatted into the CORE format. We should be able to take these and ingest into Anserini.

If that works, we should then likewise be able to stuff into Solr and expose a REST API for interactive search. Let's make this happen.

Assigning to @nikhilro @edwinzhng

**Comment by lintool** [comment]
Generalizing this issue. We can just as easily throw ACL anthology into Solr also: https://www.aclweb.org/anthology/

Bibtex -> CORE conversion can be done with a simple Python script, then we can reuse our existing machinery...

**Comment by nikhilro** [comment]
#994 PR merged
