### ISSUE TITLE
Implement generator for bibtex entries

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#984]
cf. #971 

Given that a lot of scientific articles are going to be available in bibtex, should we just write a native document generator that takes bibtex? Currently, we'd write a simple Python script that reformats to Core, and then use the Core ingester...

Is bibtex a common enough use case that we're just better off writing its own dedicated ingester?

Poking around, this seems reasonable? https://github.com/jbibtex/jbibtex

With this, we can take the ACL anthology data and directly ingest into Anserini? https://www.aclweb.org/anthology/

@nikhilro @edwinzhng thoughts?

**Comment by edwinzhng** [comment]
Seems reasonable to me, especially if other papers will be using BibTeX

**Comment by nikhilro** [comment]
#994 PR merged
