### ISSUE TITLE
Ingest ACL Anthology into Anserini and then Solrini

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#986]
ACL Anthology: https://www.aclweb.org/anthology/

Once we implement indexer of bibtex files ref:  #984 this should be very easy.

Anthology data, in raw XML: https://github.com/acl-org/acl-anthology/tree/master/data/xml
Conversion script to bibtext: https://github.com/acl-org/acl-anthology/blob/master/bin/create_bibtex.py

**Comment by lintool** [comment]
The code for this is done for #994.

We should write up documentation for doing this, since ACL anthology is publicly available. Probably a single page, something like "Ingesting the ACL Anthology into Anserini and Solrini".

The goal when I write documentation is that someone should be able to replicate the results just by copy and pasting the commands.

**Comment by edwinzhng** [comment]
> The code for this is done for #994.
> 
> We should write up documentation for doing this, since ACL anthology is publicly available. Probably a single page, something like "Ingesting the ACL Anthology into Anserini and Solrini".
> 
> The goal when I write documentation is that someone should be able to replicate the results just by copy and pasting the commands.

Will add in the next PR

**Comment by edwinzhng** [comment]
Closing, addressed by #1005
