### ISSUE TITLE
Build AclGenerator to Support Author, Venue, and SIG facets

### ISSUE THREAD

**Issue by edwinzhng** [castorini/anserini#995]
Building the [acl-anthology](https://github.com/acl-org/acl-anthology) data from the source code provides a nice directory with YAML files containing data for papers and volumes.

We want to:

1.  Support Lucene document generation using the YAML files for papers (this contains more information than Bibtex)
  * It would be good to create a new `AclGenerator` for these YAML files in addition to the existing `BibtextGenerator`
2. Add facet fields for the author, venue, and SIG fields

**Comment by lintool** [comment]
Yes, please `BibtextGenerator` alone, as it's general-purpose for scientific collections.

**Comment by nikhilro** [comment]
For the `BibtexGenerator`, we should still add a doc on how would one potentially use it, right? Now that `acl-anthology` ingestion doc will be for `AclGenerator`, what's the best place and way to provide some reference for `BibtexGenerator` @lintool?

**Comment by lintool** [comment]
Let's focus on documentation for ACL (i.e., `AclGenerator`) for now. We'll document `BibtexGenerator` when we have a good public collection to demonstrate it on.

**Comment by lintool** [comment]
Would it help if we created a repo, something like `https://github.com/castorini/acl-anthology-yaml` where you directly check in the pre-compiled YAML files. So that the documentation can directly `wget` from it or something like that?

**Comment by edwinzhng** [comment]
It could help, but might be overkill since generating them from scratch is just:
1. Clone the `acl-anthology` repo
2. Install dependencies `pip install -r requirements.txt`
3. Generate files with `python3 bin/create_hugo_yaml.py`

I can include this in documentation? Otherwise we would need to periodically update our own repository once new papers get added etc

**Comment by lintool** [comment]
hey @edwinzhng @nikhilro - yup, just include those invocations in our docs, and we should be good.

Also, can you refactor your unit tests using the same abstraction in your next PR?

Thanks!

**Comment by edwinzhng** [comment]
Closing since this was addressed by #1005
